gendai.ismedia.jp
AdguardTeam/AdguardFilters pull request #103293
Opened 2021-12-15 15:58 UTC by SKEIDs

#102167

2021-12-20 21:43 UTC, zloyden requested changes

2021-12-20 21:43 UTC, zloyden commented on JapaneseFilter/sections/specific.txt
> +gendai.ismedia.jp##.blockContainer > aside[style="min-height:250px;"]
I only see it in the mobile version of the website. Please move it to the `Mobile filter - specific_web`.

2021-12-21 10:00 UTC, Yuki2718 commented
Fixed directly https://github.com/AdguardTeam/AdguardFilters/commit/69ab2f84680e532182b2e18f1ecc759582ff1f0b

2021-12-21 10:00 UTC, closed without merging

2021-12-21 12:01 UTC, SKEIDs commented
> Fixed directly [69ab2f8](https://github.com/AdguardTeam/AdguardFilters/commit/69ab2f84680e532182b2e18f1ecc759582ff1f0b)

thank you