shyteentube.com
AdguardTeam/AdguardFilters pull request #103426
Opened 2021-12-16 15:24 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/102417

2021-12-16 19:38 UTC, Sergey-Lyapin requested changes

2021-12-16 19:38 UTC, Sergey-Lyapin commented on SpanishFilter/sections/specific.txt
> +shyteentube.com##.hor_bs
В базовый фильтр

2021-12-16 19:38 UTC, Sergey-Lyapin commented on SpanishFilter/sections/specific.txt
> +shyteentube.com##.video_av_bl
Не могу найти этот элемент

2021-12-17 10:02 UTC, jellizaveta commented on SpanishFilter/sections/specific.txt
> +shyteentube.com##.video_av_bl
<details><summary>Screenshot:</summary>

![Снимок экрана 2021-12-17 в 13 01 00](https://user-images.githubusercontent.com/91964807/146526791-48a9de0d-cd43-461a-84e5-b7bf5280d3d5.png)

</details><br/>

2021-12-17 13:53 UTC, merged