otomelab.com
AdguardTeam/AdguardFilters pull request #103745
Opened 2021-12-19 09:01 UTC by SKEIDs

https://github.com/AdguardTeam/AdguardFilters/issues/103646

2021-12-20 17:30 UTC, Sergey-Lyapin requested changes

2021-12-20 17:30 UTC, Sergey-Lyapin commented on SocialFilter/sections/specific.txt
> +otomelab.com##.hidari
This rule hides useful headings, it's better to use ext-CSS here:
`otomelab.com#?##article > div.hidari:contains(この記事をシェア)`

2021-12-20 17:32 UTC, Sergey-Lyapin commented
but anyway this site has only 2,480 visitors a month.
https://pr-cy.io/otomelab.com/

2021-12-20 17:32 UTC, closed without merging

2021-12-21 12:00 UTC, SKEIDs commented on SocialFilter/sections/specific.txt
> +otomelab.com##.hidari
I see.