www.businessinsider.jp
AdguardTeam/AdguardFilters pull request #103859
Opened 2021-12-20 09:46 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/102407

<details><summary>Screenshot:</summary>

![Снимок экрана 2021-12-20 в 12 45 25](https://user-images.githubusercontent.com/91964807/146746878-72a2da9d-060f-4d11-953c-70b33a274acd.png)

![Снимок экрана 2021-12-20 в 12 46 12](https://user-images.githubusercontent.com/91964807/146746962-3b1e48fd-b2c8-49f8-807f-bfb2a4280cf4.png)

</details><br/>

2021-12-20 21:22 UTC, zloyden requested changes

2021-12-20 21:22 UTC, zloyden commented on JapaneseFilter/sections/specific.txt
> +businessinsider.jp##.p-mailmag
Not an ad. `Annoyances - self-promo`.

2021-12-21 08:39 UTC, Yuki2718 approved these changes

2021-12-21 08:41 UTC, zloyden approved these changes

2021-12-21 08:41 UTC, merged