rint-gakufu.com
AdguardTeam/AdguardFilters pull request #104373
Opened 2021-12-24 11:46 UTC by gork7777

issue: #104343

2021-12-24 17:28 UTC, Yuki2718 commented
Those banners are self-promo. I guess `##.block-top-banner` in particular should not be blocked even in Annoyances.

2021-12-24 17:29 UTC, Yuki2718 requested changes
Remove all the rules in JPF and instead add `print-gakufu.com##.banner` to Annoyances > self-promo.

2021-12-24 17:35 UTC, Yuki2718 approved these changes

2021-12-26 21:25 UTC, zloyden approved these changes

2021-12-26 21:26 UTC, merged