asuka-xp.com
AdguardTeam/AdguardFilters pull request #104326
Opened 2021-12-24 03:51 UTC by SKEIDs

#104299

2021-12-24 17:48 UTC, Yuki2718 requested changes

2021-12-24 17:48 UTC, Yuki2718 commented on SocialFilter/sections/specific.txt
> +asuka-xp.com,sportnews.to,indir.vip###custom_html-4
It seems this rule does nothing.

2021-12-25 14:08 UTC, SKEIDs commented on SocialFilter/sections/specific.txt
> +asuka-xp.com,sportnews.to,indir.vip###custom_html-4
delete the space above "カテゴリー".
Is this an unnecessary rule?
@Yuki2718

2021-12-25 18:02 UTC, Yuki2718 commented on SocialFilter/sections/specific.txt
> +asuka-xp.com,sportnews.to,indir.vip###custom_html-4
Do you see visual difference by this rule?

2021-12-25 18:03 UTC, Yuki2718 commented on SocialFilter/sections/specific.txt
> +asuka-xp.com,sportnews.to,indir.vip###custom_html-4
Possibly I have to check with AG app than AG extension. On my Chromium + AG Ext. there's no difference.

2021-12-25 18:13 UTC, SKEIDs commented on SocialFilter/sections/specific.txt
> +asuka-xp.com,sportnews.to,indir.vip###custom_html-4
I delete this domain from that rule.

2021-12-28 17:01 UTC, merged