colonist.io
AdguardTeam/AdguardFilters pull request #104329
Opened 2021-12-24 04:10 UTC by SKEIDs

#104316

2021-12-24 17:45 UTC, Yuki2718 requested changes
Yours is okay, but I opened PR in EasyList so if they're quick to merge you may need to remove these rules (no need to do currently). Until then please replace `||colonist.io/dist/images/binance*x*.jpg` with `||colonist.io/dist/images/ab_`.

2021-12-25 14:13 UTC, SKEIDs commented
@Yuki2718 
OK.Done.

2021-12-25 18:03 UTC, Yuki2718 approved these changes

2021-12-26 21:31 UTC, zloyden approved these changes

2021-12-26 21:31 UTC, merged