kamigame.jp
AdguardTeam/AdguardFilters pull request #104495
Opened 2021-12-25 14:01 UTC by SKEIDs

#104484

2021-12-25 18:33 UTC, Yuki2718 requested changes
Please change to `kamigame.jp##div[id^="overlay_ad_"]` although I don't see this overlay on mobile.

2021-12-25 18:37 UTC, SKEIDs commented
> 



> Please change to `kamigame.jp##div[id^="overlay_ad_"]` although I don't see this overlay on mobile.

done.

2021-12-25 18:39 UTC, Yuki2718 approved these changes

2021-12-26 21:21 UTC, zloyden approved these changes

2021-12-26 21:21 UTC, merged