cyberwaters.com
AdguardTeam/AdguardFilters pull request #104918
Opened 2021-12-28 13:33 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/101698

<details><summary>Screenshot:</summary>

![Снимок экрана 2021-12-28 в 16 32 41](https://user-images.githubusercontent.com/91964807/147571405-31692624-78b9-4a84-abb8-92201139eb72.png)

![Снимок экрана 2021-12-28 в 16 32 52](https://user-images.githubusercontent.com/91964807/147571420-cc4e4f7e-f97f-4779-839d-5741ffe711fc.png)

</details><br/>

2021-12-29 15:24 UTC, Alex-302 requested changes

2021-12-29 15:24 UTC, Alex-302 commented on EnglishFilter/sections/specific.txt
> +cyberwaters.com##aside[id^="custom_html-6"]
Можно просто `cyberwaters.com###custom_html-6`. `^` тут точно лишнее.

2021-12-29 16:26 UTC, jellizaveta commented on EnglishFilter/sections/specific.txt
> +cyberwaters.com##aside[id^="custom_html-6"]
Остается промежуток от рекламы 

<details><summary>Screenshot:</summary>

![Снимок экрана 2021-12-29 в 19 24 39](https://user-images.githubusercontent.com/91964807/147683016-0aed8da8-1a65-43d7-b622-4b8143c8569c.png)

</details><br/>

2022-01-04 16:02 UTC, Alex-302 approved these changes

2022-01-04 16:03 UTC, merged