manga.line.me
AdguardTeam/AdguardFilters pull request #105250
Opened 2022-01-01 07:00 UTC by SKEIDs

this is mobile rule. `manga.line.me##.mdGHD01Share`
fix #105240

2022-01-01 17:23 UTC, Yuki2718 requested changes
Please add `manga.line.me##.MdCMN09App` to Annoyances > mobile-app.

2022-01-02 00:44 UTC, SKEIDs commented
done

2022-01-02 22:26 UTC, Yuki2718 approved these changes

2022-01-09 22:10 UTC, Divine-Frog approved these changes

2022-01-09 22:11 UTC, merged