sugorokuya.jp
AdguardTeam/AdguardFilters pull request #105796
Opened 2022-01-05 11:41 UTC by SKEIDs

fix #105675

2022-01-05 14:53 UTC, Yuki2718 requested changes

2022-01-05 14:53 UTC, Yuki2718 commented on SocialFilter/sections/specific.txt
> +sugorokuya.jp##.my-4
This rule doesn't hide "このページを伝える" leftover. Can you remove this and instead add
```
! https://github.com/AdguardTeam/AdguardFilters/issues/105675
sugorokuya.jp#?#.sns-share:upward(1)
to css_extended?
```

2022-01-06 02:54 UTC, SKEIDs commented on SocialFilter/sections/specific.txt
> +sugorokuya.jp##.my-4
ok.done

2022-01-06 09:56 UTC, Yuki2718 approved these changes

2022-01-10 21:20 UTC, Divine-Frog approved these changes

2022-01-10 21:20 UTC, merged