j-net21.smrj.go.jp
AdguardTeam/AdguardFilters pull request #105805
Opened 2022-01-05 13:34 UTC by spiri-leo

Issue: #105778

2022-01-05 13:45 UTC, gork7777 requested changes
It's better use `j-net21.smrj.go.jp###esodan-banner`
And this probably should be added on popup filter

2022-01-05 14:26 UTC, Yuki2718 approved these changes

2022-01-05 14:27 UTC, Yuki2718 commented
Hmm, but this seems to be rather a chat widget.

2022-01-10 21:22 UTC, Divine-Frog approved these changes

2022-01-10 21:22 UTC, Divine-Frog commented on AnnoyancesFilter/sections/popups.txt
> +j-net21.smrj.go.jp###esodan-banner
It's more popup than a chat widget.

2022-01-10 21:23 UTC, merged