so-net.ne.jp
AdguardTeam/AdguardFilters pull request #106140
Opened 2022-01-08 04:27 UTC by SKEIDs

fix #105970

2022-01-08 17:22 UTC, Yuki2718 requested changes
Please move the rule to popup.txt.

2022-01-09 05:06 UTC, SKEIDs commented
> Please move the rule to popup.txt.

ok.fixed

2022-01-09 17:41 UTC, Yuki2718 approved these changes

2022-01-09 21:56 UTC, Divine-Frog approved these changes

2022-01-09 21:56 UTC, merged