coursef.com
AdguardTeam/AdguardFilters pull request #106262
Opened 2022-01-10 05:16 UTC by spiri-leo

Issue: #106236

2022-01-19 09:30 UTC, Sergey-Lyapin requested changes
там еще остатки остались

2022-01-19 10:42 UTC, spiri-leo commented
> там еще остатки остались

Исправил.

2022-01-19 14:55 UTC, Sergey-Lyapin commented
@spiri-leo странно, но у меня все остатки кроме того, что в правой колонке, пропали

2022-01-21 11:37 UTC, Sergey-Lyapin commented
@spiri-leo Они изменили верстку, эти правила больше не актуальны. Похоже класс w-100 используется только для рекламы, можно с ним правило сделать.

2022-01-24 10:05 UTC, Sergey-Lyapin commented
`##.adslabel` больше не нужен, `##div[style="min-height: 250px"]` больше не работает

2022-01-24 10:14 UTC, spiri-leo commented
> @spiri-leo `##.adslabel` больше не нужен, `##div[style="min-height: 250px"]` больше не работает

Убрал.

2022-01-24 10:28 UTC, Sergey-Lyapin commented
А это добавить:
`coursef.com##div[style="min-height: 250px !important"]`

2022-01-24 10:29 UTC, merged