www.bulletin.com
AdguardTeam/AdguardFilters pull request #106305
Opened 2022-01-10 13:56 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/103495

<details><summary>Screenshot:</summary>

![Снимок экрана 2022-01-10 в 16 55 45](https://user-images.githubusercontent.com/91964807/148777581-b9e0c649-7628-482a-8e95-2a1c3db8d696.png)

</details><br/>

2022-01-10 21:38 UTC, Alex-302 requested changes

2022-01-10 21:38 UTC, Alex-302 commented on AnnoyancesFilter/sections/cookies_specific.txt
> +bulletin.com##body > .__fb-light-mode
Этот класс у многих элементов сайта. Лучше иначе сделать.

2022-01-12 12:47 UTC, Alex-302 commented on AnnoyancesFilter/sections/cookies_specific.txt
> +bulletin.com##body > .__fb-light-mode
А сейчас не повторяется.
Оно сейчас рабочее?

2022-01-12 13:28 UTC, jellizaveta commented on AnnoyancesFilter/sections/cookies_specific.txt
> +bulletin.com##body > .__fb-light-mode
Да, у меня с Австрийским ip высвечивается

2022-01-12 16:13 UTC, Alex-302 approved these changes

2022-01-12 16:13 UTC, merged