www.karaoke.ru
AdguardTeam/AdguardFilters pull request #106304
Opened 2022-01-10 13:42 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/103374

<details><summary>Screenshot:</summary>

![Снимок экрана 2022-01-10 в 16 42 09](https://user-images.githubusercontent.com/91964807/148775759-7a39ab6e-1e89-43db-94bd-91b9385ee0c7.png)

</details><br/>

2022-01-10 21:27 UTC, Alex-302 requested changes

2022-01-10 21:27 UTC, Alex-302 commented on RussianFilter/sections/specific.txt
> +||static.wi-fi.ru/mtt/banners$domain=~auth.wi-fi.ru|~karaoke.ru
Исключение надо. Сайт никак не связан с wi-fi.ru

2022-01-11 10:01 UTC, Divine-Frog commented on RussianFilter/sections/whitelist.txt
> +@@||static.wi-fi.ru/mtt/banners/*$domain=karaoke.ru
`*` нужна для чего? Иначе лишнее тут.

2022-01-11 10:19 UTC, Divine-Frog approved these changes

2022-01-11 10:20 UTC, merged