fastpic.org
AdguardTeam/AdguardFilters pull request #106321
Opened 2022-01-10 16:44 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/103585

<details><summary>Screenshot:</summary>

[Screen 1](https://imgur.com/X8eZ4mu)
[Screen 2](https://imgur.com/P4ycJBf)

</details><br/>

2022-01-10 21:35 UTC, Alex-302 requested changes

2022-01-10 21:35 UTC, Alex-302 commented on EnglishFilter/sections/specific.txt
> +fastpic.org##.image-box > a[class]:last-child
Лучше избегать таких псевдо-классов. Там есть к чему привязаться по-нормальному(span у посматриваемого изображения, или отличный от него адрес баннера, сравни адреса).

2022-01-10 21:38 UTC, Divine-Frog requested changes

2022-01-10 21:38 UTC, Divine-Frog commented on EnglishFilter/sections/specific.txt
> +fastpic.org##.image-box > a[class]:last-child
Попробуй `fastpic.ru,fastpic.org##div[class^="spinner"] a[id]:last-child` и добавь его к
```
! fastpic.ru
```

2022-01-10 21:52 UTC, Divine-Frog commented on EnglishFilter/sections/specific.txt
> +fastpic.org##.image-box > a[class]:last-child
> Лучше избегать таких псевдо-классов. Там есть к чему привязаться по-нормальному(span у посматриваемого изображения, или отличный от него адрес баннера, сравни адреса).


В принципе выше правила достаточно в текущей верстке. Можно поточней сделать через скрытие `img` или ext-css, но последнее думаю излишне и не везде работать будет.

2022-01-11 08:50 UTC, Divine-Frog approved these changes

2022-01-11 08:51 UTC, merged