leverageedu.com
AdguardTeam/AdguardFilters pull request #106646
Opened 2022-01-13 12:58 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/100623

<details><summary>Screenshot:</summary>

![Снимок экрана 2022-01-13 в 15 57 12](https://user-images.githubusercontent.com/91964807/149334377-24352bb8-1488-4058-ac67-1785dd2afb46.png)

![Снимок экрана 2022-01-13 в 15 57 43](https://user-images.githubusercontent.com/91964807/149334462-487994b1-6f9c-4214-bd86-726a5fdb4325.png)

![Снимок экрана 2022-01-13 в 15 56 56](https://user-images.githubusercontent.com/91964807/149334336-f26683e9-9e5a-4c1c-a98a-513e5ed87520.png)

![Снимок экрана 2022-01-13 в 15 58 02](https://user-images.githubusercontent.com/91964807/149334492-2c44df37-8522-4fc4-b7e7-9afe906d3eb0.png)

</details><br/>

2022-01-18 09:37 UTC, Alex-302 commented
Just hide this only
![image](https://user-images.githubusercontent.com/8361299/149910403-36b3aa8f-964b-4fdb-8c5d-67f820f04676.png)
![image](https://user-images.githubusercontent.com/8361299/149910646-e1c4ee23-5548-4cec-82cc-4033b1e4e1e9.png)

2022-01-19 21:49 UTC, zloyden requested changes

2022-01-19 21:49 UTC, zloyden commented on AnnoyancesFilter/sections/mobile-app.txt
> +leverageedu.com##div[class$="course"]
You can either create two rules
```
leverageedu.com##.webcourse
leverageedu.com##.mobilecourse
```
or improve yours.
```
leverageedu.com##.show-content > p ~ div[class$="course"]
```

2022-01-20 10:06 UTC, zloyden approved these changes

2022-01-20 10:06 UTC, merged