magazine.kinto-jp.com
AdguardTeam/AdguardFilters pull request #107023
Opened 2022-01-17 08:06 UTC by SKEIDs

Fix magazine.kinto-jp.com

<details><summary>screenshot</summary>

![](https://a.pomf.cat/fvoqkz.png)
</details><br/>

<details><summary>screenshot</summary>

![](https://a.pomf.cat/tgxzda.png)
</details><br/>

2022-01-17 15:22 UTC, Yuki2718 requested changes
`magazine.kinto-jp.com##div[class$="_share"]`

2022-01-17 15:51 UTC, SKEIDs commented
> `magazine.kinto-jp.com##div[class$="_share"]`

Fixed

2022-01-17 15:55 UTC, Yuki2718 approved these changes

2022-01-18 21:13 UTC, zloyden approved these changes

2022-01-18 21:13 UTC, merged