www.banki.ru
AdguardTeam/AdguardFilters pull request #107034
Opened 2022-01-17 11:21 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/103804

<details><summary>Screenshot:</summary>

![Снимок экрана 2022-01-17 в 14 14 22](https://user-images.githubusercontent.com/91964807/149759930-8b69f989-39d7-4f32-aa88-f1d528bb0175.png)

![Снимок экрана 2022-01-17 в 14 14 35](https://user-images.githubusercontent.com/91964807/149759965-f858c4df-f9ed-47e7-aa3d-22ff092716e5.png)

![Снимок экрана 2022-01-17 в 14 17 39](https://user-images.githubusercontent.com/91964807/149760618-6909c7a4-c114-4bb3-a9de-6cade46afaa3.png)

</details><br/>

2022-01-17 11:39 UTC, zloyden requested changes

2022-01-17 11:39 UTC, zloyden commented on AnnoyancesFilter/sections/popups.txt
> +banki.ru#$#.ReactModalPortal { display: none !important; }
С этим правилом ломается логин на сайте.
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/149763104-a0f7ce67-8f13-4a6d-8a97-afda18102fcb.png)

</details><br/>

2022-01-18 10:00 UTC, Alex-302 commented on AnnoyancesFilter/sections/popups.txt
> +banki.ru#$?#div > .npvhb:has(> div:not([class*="padding"])){ display: none !important; }
стрёмные правила. 
Попробуй заблокировать https://www.banki.ru/ng/api/v1.0/public/banners

2022-01-18 21:29 UTC, zloyden requested changes

2022-01-18 21:29 UTC, zloyden commented on AnnoyancesFilter/sections/popups.txt
> +||banki.ru/ng/api/v1.0/public/banners
`v1.0` -> `v*`.

2022-01-19 10:13 UTC, zloyden approved these changes

2022-01-19 10:13 UTC, merged