www.stardoll.com
AdguardTeam/AdguardFilters pull request #107041
Opened 2022-01-17 12:26 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/104184

<details><summary>Screenshot:</summary>

![Снимок экрана 2022-01-17 в 15 26 28](https://user-images.githubusercontent.com/91964807/149769275-3b8ba898-4bb7-4965-bd79-bdd72d503e40.png)

</details><br/>

2022-01-17 15:16 UTC, Sergey-Lyapin requested changes
@jellizaveta 
Там еще есть остатки от рекламы на странице регистрации и после регистрации вверху

2022-01-17 15:16 UTC, Sergey-Lyapin commented on AnnoyancesFilter/sections/cookies_specific.txt
> +stardoll.com###consentMainPopup
Можно объединить в одно правило

2022-01-17 17:17 UTC, Sergey-Lyapin requested changes

2022-01-17 17:17 UTC, Sergey-Lyapin commented on EnglishFilter/sections/css_extended.txt
> +stardoll.com##.col > div.smb:has(> div.sdadinfo)
Можно без расширенного обойтись, например так:
`stardoll.com##div[class*="sdad"]`

2022-01-17 17:51 UTC, Alex-302 commented on EnglishFilter/sections/css_extended.txt
> +stardoll.com##.col > div.smb:has(> div.sdadinfo)
Или двумя. На популярных сайтах это не страшно.
```
stardoll.com##.sdadinfo
stardoll.com##.stardollads
```

2022-01-18 11:04 UTC, Sergey-Lyapin commented
@jellizaveta 
Вот еще incorrect blocking нашел:
http://www.stardoll.com/en/ после регистрации
![gf](https://user-images.githubusercontent.com/18536328/149925205-e0c520f2-34d5-4fa6-b6d3-202c259c7196.png)

2022-01-18 11:06 UTC, Sergey-Lyapin commented
Соцвиджеты и остатки от них:
![gfd](https://user-images.githubusercontent.com/18536328/149925935-7b0a4b19-fa9d-4f00-8c72-a1f3a7ea8bdc.png)

2022-01-20 13:38 UTC, Alex-302 commented on AnnoyancesFilter/sections/widgets.txt
> +stardoll.com##.twitter_container
Use these rules: 
https://github.com/AdguardTeam/AdguardFilters/blob/81806de2112491a782865fb3a7625b5df152d3cc/SocialFilter/sections/specific.txt#L48-L50

2022-01-20 13:41 UTC, Alex-302 approved these changes

2022-01-20 14:11 UTC, Alex-302 approved these changes

2022-01-20 14:12 UTC, merged