game.watch.impress.co.jp
AdguardTeam/AdguardFilters pull request #107021
Opened 2022-01-17 07:54 UTC by SKEIDs

Fix #103845

2022-01-17 14:46 UTC, Yuki2718 requested changes
Add `watch.impress.co.jp` to `#?#li > ._popIn_recommend_article_ad:upward(1)` rule in JPF > css_extended and also add `watch.impress.co.jp##.extension > aside.special` to Annoyances > self-promo.

2022-01-17 14:46 UTC, Yuki2718 commented on MobileFilter/sections/specific_web.txt
> +game.watch.impress.co.jp##aside[class^="ad"]
This rule has false positive on desktop site (viewable on mobile too). Please change to `watch.impress.co.jp##.ad.movie`.

2022-01-17 14:46 UTC, Yuki2718 commented on MobileFilter/sections/specific_web.txt
> +game.watch.impress.co.jp###sp-floating-layer
Please drop `game.` subdomain.

2022-01-17 15:58 UTC, SKEIDs commented
Fixed all

2022-01-17 16:01 UTC, Yuki2718 approved these changes

2022-01-18 21:15 UTC, zloyden approved these changes

2022-01-18 21:15 UTC, merged