jp.cyberlink.com
AdguardTeam/AdguardFilters pull request #107058
Opened 2022-01-17 15:32 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/104716

<details><summary>Screenshot:</summary>

![Снимок экрана 2022-01-17 в 18 23 02](https://user-images.githubusercontent.com/91964807/149796684-afa78266-bace-45fb-a0b9-a4aeaf7cd623.png)

![Снимок экрана 2022-01-17 в 18 27 23](https://user-images.githubusercontent.com/91964807/149797378-d611f30f-8781-4fa2-b2e9-876b97671ea5.png)

![Снимок экрана 2022-01-17 в 18 23 22](https://user-images.githubusercontent.com/91964807/149796741-b2e44fff-45a1-405a-869b-e95d99838bd3.png)

![Снимок экрана 2022-01-17 в 18 31 15](https://user-images.githubusercontent.com/91964807/149798015-cb89a062-7520-491c-916a-57644ce56309.png)

</details><br/>

2022-01-17 15:40 UTC, Yuki2718 requested changes
You can drop jp subdomain from all the rules. The site is multi-national e.g. `https://tw.cyberlink.com/index_zh_TW.html`

2022-01-17 15:40 UTC, Yuki2718 commented on JapaneseFilter/sections/specific.txt
> +jp.cyberlink.com###faceme_a
Why do you block this? It's their product. I won't block even in Annoyances.

2022-01-17 15:40 UTC, Yuki2718 commented on SocialFilter/sections/specific.txt
> +jp.cyberlink.com##.news_nav > :not([class="backUrl"])
I don't see this in the page.

2022-01-17 15:40 UTC, Yuki2718 commented on AnnoyancesFilter/sections/popups.txt
> +jp.cyberlink.com#$#.modal-open { overflow: auto !important; }
Are these for Mac? I don't see.

2022-01-17 15:57 UTC, jellizaveta commented on SocialFilter/sections/specific.txt
> +jp.cyberlink.com##.news_nav > :not([class="backUrl"])
https://jp.cyberlink.com/jpn/press_room/view_4797.html

<details><summary>Screenshot:</summary>

![Снимок экрана 2022-01-17 в 18 56 36](https://user-images.githubusercontent.com/91964807/149802039-9c672f45-b030-49d3-9635-0d7bb794c8a5.png)

</details><br/>

2022-01-17 15:58 UTC, Yuki2718 commented on SocialFilter/sections/specific.txt
> +jp.cyberlink.com##.news_nav > :not([class="backUrl"])
Okay, nice pick!

2022-01-17 16:00 UTC, Yuki2718 commented
Maybe `||cyberlink.com^$removeparam=affid` can be added: `https://jp.cyberlink.com/blog/youtube/261/guide-to-audio-for-youtube?affid=2581_1572_730_49856_0_JPN`

2022-01-18 10:17 UTC, Alex-302 approved these changes

2022-01-18 10:17 UTC, merged