i.factor.ua
AdguardTeam/AdguardFilters pull request #107132
Opened 2022-01-18 12:08 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/105606

<details><summary>Screenshot:</summary>

<img width="474" alt="Снимок экрана 2022-01-18 в 15 07 20" src="https://user-images.githubusercontent.com/91964807/149934595-db7419dd-24f5-4813-bc0e-65f4f14d1baf.png">

<img width="1792" alt="Снимок экрана 2022-01-18 в 15 07 31" src="https://user-images.githubusercontent.com/91964807/149934620-cf40ad6b-5854-418e-9b89-5b0a559f17c6.png">

<img width="1792" alt="Снимок экрана 2022-01-18 в 15 07 48" src="https://user-images.githubusercontent.com/91964807/149934657-b91d36a0-c153-4fee-bf96-f3f0e57a154d.png">

</details><br/>

2022-01-20 14:34 UTC, Alex-302 requested changes

2022-01-20 14:34 UTC, Alex-302 commented on RussianFilter/sections/specific.txt
> +i.factor.ua###place
Already hidden by `i.factor.ua##.b-nav__overlay + div[data-place-block="head"]`

2022-01-20 14:34 UTC, Alex-302 commented on RussianFilter/sections/specific.txt
> +i.factor.ua###slogan
self-promo

2022-01-20 14:34 UTC, Alex-302 commented on RussianFilter/sections/specific.txt
> +i.factor.ua##div[data-ad="active"]
Hidden by `i.factor.ua##div[data-ad]`

2022-01-20 14:35 UTC, Alex-302 commented
Юзер жалуется на рекламу, т.к. у него не установлена Экстра
![image](https://user-images.githubusercontent.com/8361299/150359137-407bf2a6-902c-4395-a0e2-26f789df4097.png)

2022-01-26 18:38 UTC, Alex-302 requested changes

2022-01-26 18:38 UTC, Alex-302 commented on EnglishFilter/sections/antiadblock.txt
> +i.factor.ua,filmvilag.me,liderendeportes.com,serieskao.tv,freefilm.to,ac24.cz,downloads-anymovies.com,nsfwyoutube.com,jpblow.info,hesgoal.com,filmisub.com,igg-games.com,ruwhite.info,slones.info,ukhel
Почти. Но не то. Вот правильный вариант
https://github.com/AdguardTeam/AdguardFilters/commit/f5aabab77a3f90ad5108f490b905aa8070168e2b#diff-1d00385f25e1eb023d803d55e3a5300872221d993f75597cecb9b6886ebf9bf1R586
Тот, который в базовом фильтре - для похожей рекламы, но с попапом(`##pp`). Т.е. тебе нужно просто к одному правилу дописать домен.

2022-01-27 09:54 UTC, zloyden approved these changes

2022-01-27 09:56 UTC, merged