live.nicovideo.jp
AdguardTeam/AdguardFilters pull request #107473
Opened 2022-01-20 17:34 UTC by SKEIDs

Fix #107456

2022-01-20 22:41 UTC, gork7777 commented
your `##ul[class^="___menu-dock___"]` rule is blocking other useful elements.
Let's use these and these are better I guess.

For social: `live.nicovideo.jp##a[class*="local-anchor"]`
For banner: `live.nicovideo.jp##a[class*="app-download-banner"]`

2022-01-21 16:12 UTC, SKEIDs commented
> 

OK. Thank you for tell me the rule.

2022-01-21 16:12 UTC, SKEIDs commented
@gork7777 
 OK. Thank you for tell me the rule.

2022-01-29 17:17 UTC, Yuki2718 requested changes

2022-01-29 17:17 UTC, Yuki2718 commented on AnnoyancesFilter/sections/mobile-app.txt
> +live.nicovideo.jp##a[class*="app-download-banner"]
Better `live.nicovideo.jp##a[class^="___app-download-banner"]`

2022-01-29 17:17 UTC, Yuki2718 commented on JapaneseFilter/sections/specific.txt
> +live.nicovideo.jp##aside[class*="banner-ad"]
`live.nicovideo.jp##aside[class^="___banner-ad"]`

2022-01-29 17:35 UTC, SKEIDs commented
sorry, Why is "___" necessary?

2022-01-29 17:37 UTC, Yuki2718 commented
> sorry, Why is "___" necessary?

The point is rather `^=` is prefered to `*=` as is more accurate and more efficient.

2022-01-29 17:39 UTC, SKEIDs commented
> The point is rather ^= is prefered to *= as is more accurate and more efficient.

I see . thank you.

2022-01-29 17:43 UTC, SKEIDs commented
> If they changed the class name so that `^=` doesn't apply any more, it's good to switch to `*=`.

I see. that is good.

2022-01-29 17:52 UTC, Yuki2718 commented
But for now use `^=`

2022-01-29 18:03 UTC, Yuki2718 approved these changes

2022-01-29 18:04 UTC, Yuki2718 commented
Whoops, this one `live.nicovideo.jp##a[class^="local-anchor"]` doesn't work. Revert to the original your filter.

2022-01-29 18:10 UTC, SKEIDs commented
> Whoops, this one `live.nicovideo.jp##a[class^="local-anchor"]` doesn't work. Revert to the original your filter.

OK. Is it `*=` except `live.nicovideo.jp##a[class^="local-anchor"]`?

2022-01-29 18:16 UTC, Yuki2718 commented
Sorry I was not clear but you figured it out correctly.

2022-01-29 18:19 UTC, SKEIDs commented
> Sorry I was not clear but you figured it out correctly.

thank you so much.

2022-01-30 21:36 UTC, zloyden approved these changes

2022-01-30 21:36 UTC, merged