Fix icodrops.com
AdguardTeam/AdguardFilters pull request #107701
Opened 2022-01-21 21:33 UTC by bkrucarci

https://github.com/AdguardTeam/AdguardFilters/issues/107699

2022-01-22 11:28 UTC, gork7777 requested changes
Also there's share title, you can add it here:
`##.share-title`

2022-01-24 14:55 UTC, Sergey-Lyapin commented
@bkrucarci
I can't reproduce this ad, do you still see it?

2022-01-24 18:52 UTC, bkrucarci commented
> @bkrucarci I can't reproduce this ad, do you still see it?

The website seems clean now, but just for now! These ICO Drops happen between two date. If the sponsored ICO's end, then they have to be removed. But if you close this thread as "not reproduced" after some time another sponsored ICO may happen. I left it to your decision.

2022-01-25 17:46 UTC, Alex-302 approved these changes

2022-01-25 17:46 UTC, merged