zn.ua
AdguardTeam/AdguardFilters pull request #108065
Opened 2022-01-24 14:14 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/105584

<details><summary>Screenshot:</summary>

<img width="364" alt="Снимок экрана 2022-01-24 в 17 12 58" src="https://user-images.githubusercontent.com/91964807/150798673-68a9ff2f-2263-4e56-9ef1-b61955ed8618.png">

<img width="362" alt="Снимок экрана 2022-01-24 в 17 13 07" src="https://user-images.githubusercontent.com/91964807/150798693-0d73dd9b-5c25-42a5-a6e7-ffdf465b420a.png">

<img width="1015" alt="Снимок экрана 2022-01-24 в 17 13 20" src="https://user-images.githubusercontent.com/91964807/150798753-6f6126e2-10fd-488e-875c-e8be2b422b23.png">

</details><br/>

2022-01-26 18:58 UTC, Alex-302 requested changes

2022-01-26 18:58 UTC, Alex-302 commented on AnnoyancesFilter/sections/widgets.txt
> +zn.ua##.youtube-box
Слишком много блокируется. Видео не нужно гасить. Максимум - по `.youtube-box__top`

2022-01-26 18:58 UTC, Alex-302 commented on SocialFilter/sections/specific.txt
> +zn.ua##.left_socials
Это ссылки на блоги.

2022-01-26 18:58 UTC, Alex-302 commented on SocialFilter/sections/specific.txt
> +zn.ua##.news_item[href^="https://www.youtube.com"]
Можно же просто картинку заблокировать.

2022-01-27 18:51 UTC, Alex-302 commented on SocialFilter/sections/specific.txt
> +||zn.ua/user/img/special/zn-youtube.png
||zn.ua/user/img/special/zn-youtube.png

Это же раздражитель.

2022-01-27 18:51 UTC, Alex-302 commented on AnnoyancesFilter/sections/widgets.txt
> +zn.ua##.youtube-box
?

2022-01-28 18:59 UTC, Alex-302 approved these changes

2022-01-28 18:59 UTC, merged

2022-01-29 14:40 UTC, zubrRB commented on SocialFilter/sections/specific.txt
> +zn.ua##.left_socials
<details><summary>Screenshot:</summary>

![-](https://user-images.githubusercontent.com/50718960/151665124-f0656d47-9702-4f7c-ad6e-367df2f62110.png)
</details><br/>