www.blogto.com
AdguardTeam/AdguardFilters pull request #108255
Opened 2022-01-26 12:52 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/106166

<details><summary>Screenshot:</summary>

<img width="520" alt="Снимок экрана 2022-01-26 в 15 51 51" src="https://user-images.githubusercontent.com/91964807/151166136-ff268c20-bdbb-48b6-aebb-440fa0ca4725.png">

<img width="131" alt="Снимок экрана 2022-01-26 в 15 52 04" src="https://user-images.githubusercontent.com/91964807/151166172-82f03ca3-dc5f-41af-b59e-24eef31a793e.png">

<img width="374" alt="Снимок экрана 2022-01-26 в 15 52 19" src="https://user-images.githubusercontent.com/91964807/151166205-96a6970e-698b-4bf3-b76c-0fb23222c5da.png">

<img width="1117" alt="Снимок экрана 2022-01-26 в 15 52 31" src="https://user-images.githubusercontent.com/91964807/151166226-6679abef-ca4e-45c2-816b-75d54f068bda.png">

</details><br/>

2022-01-27 19:29 UTC, Alex-302 requested changes
В мобильном режиме снизу остатки плавающей рекламы
`.blogto-sticky-banner`

2022-01-27 19:29 UTC, Alex-302 commented on SocialFilter/sections/specific.txt
> +blogto.com##.twitter-round-control
Рядом есть дублирующая кнопка, а снизу - третья) Плавающее можно одним правилом убрать.

2022-01-27 19:29 UTC, Alex-302 commented on AnnoyancesFilter/sections/popups.txt
> +blogto.com##[style^="--dndwrpr-position:fixed;"]
Не вижу, для чего это правило.

2022-02-07 09:11 UTC, jellizaveta commented on AnnoyancesFilter/sections/popups.txt
> +blogto.com##[style^="--dndwrpr-position:fixed;"]
для попапа видео 

<details><summary>Screenshot:</summary>

![Снимок экрана 2022-02-07 в 12 03 07](https://user-images.githubusercontent.com/91964807/152757273-fc4db240-9aed-44c7-99d2-660a4c96681e.png)

</details><br/>

2022-02-08 13:09 UTC, Alex-302 approved these changes

2022-02-08 13:10 UTC, Alex-302 approved these changes

2022-02-08 14:11 UTC, Alex-302 approved these changes

2022-02-08 14:11 UTC, merged