m.mirkorma.ru
AdguardTeam/AdguardFilters pull request #108732
Opened 2022-01-30 08:28 UTC by spiri-leo

Issue: #108726

2022-01-30 08:37 UTC, spiri-leo commented on AnnoyancesFilter/sections/subscriptions.txt
> +mirkorma.ru,guvi.in,burmistr.ru##.section-subscribe
Этот правило блокирует баннер на десктопе:

![image](https://i.imgur.com/0L9K3xO.png)

2022-01-31 08:34 UTC, zloyden requested changes

2022-01-31 08:34 UTC, zloyden commented on AnnoyancesFilter/sections/subscriptions.txt
> +mirkorma.ru,guvi.in,burmistr.ru##.section-subscribe
Почему бы не сделать одно правило вместо двух `mirkorma.ru##div[class^="section-subscribe"]`?
Скриншоты под спойлер надо убирать.

2022-01-31 10:48 UTC, spiri-leo commented on AnnoyancesFilter/sections/subscriptions.txt
> +mirkorma.ru,guvi.in,burmistr.ru##.section-subscribe
> Почему бы не сделать одно правило вместо двух `mirkorma.ru##div[class^="section-subscribe"]`? Скриншоты под спойлер надо убирать.

Уже исправил.

2022-01-31 11:35 UTC, zloyden approved these changes

2022-01-31 11:35 UTC, merged