feanor184.ru
AdguardTeam/AdguardFilters pull request #108877
Opened 2022-01-31 13:01 UTC by spiri-leo

Issue: #108876

2022-01-31 19:02 UTC, Sergey-Lyapin requested changes

2022-02-01 03:36 UTC, spiri-leo commented on RussianFilter/sections/specific.txt
> +feanor184.ru##.adsence_verh_banner
> Там еще внизу есть подобный остаток и остаток от шарилок

Уже исправил.

2022-02-01 11:18 UTC, Sergey-Lyapin commented on RussianFilter/sections/specific.txt
> +feanor184.ru##.adsence_verh_banner
@spiri-leo 
Лучше в одно правило:
`feanor184.ru##div[class^="adsence_"]`
Для остатка от кнопок "поделиться":
`feanor184.ru#?#article > div.header_text:has(> h3:contains(Поделиться))`

2022-02-01 11:36 UTC, spiri-leo commented on RussianFilter/sections/specific.txt
> +feanor184.ru##.adsence_verh_banner
> @spiri-leo Лучше в одно правило: `feanor184.ru##div[class^="adsence_"]` Для остатка от кнопок "поделиться": `feanor184.ru#?#article > div.header_text:has(> h3:contains(Поделиться))`

Уже исправил.

2022-02-01 11:38 UTC, merged