www.leitermann.de
AdguardTeam/AdguardFilters pull request #109530
Opened 2022-02-06 03:49 UTC by spiri-leo

Issue: #109483

2022-02-07 16:20 UTC, Sergey-Lyapin requested changes

2022-02-07 16:20 UTC, Sergey-Lyapin commented on AnnoyancesFilter/sections/cookies_specific.txt
> +leitermann.de##.cookie-permission-container
@spiri-leo 
к существующему правилу

2022-02-07 16:22 UTC, Sergey-Lyapin commented on AnnoyancesFilter/sections/cookies_specific.txt
> +leitermann.de##.cookie-permission-container
`leitermann.de##.flix-sb` для шарилки

2022-02-08 08:19 UTC, spiri-leo commented on AnnoyancesFilter/sections/cookies_specific.txt
> +leitermann.de##.cookie-permission-container
> @spiri-leo к существующему правилу

> `leitermann.de##.flix-sb` для шарилки

Уже исправил.

2022-02-08 10:37 UTC, merged