www.appbank.net
AdguardTeam/AdguardFilters pull request #109718
Opened 2022-02-07 13:16 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/106832

<details><summary>Screenshot:</summary>

![Снимок экрана 2022-02-07 в 16 16 19](https://user-images.githubusercontent.com/91964807/152795105-0a3b1f04-d6d4-450f-af78-25b539cec2bd.png)

</details><br/>

2022-02-07 17:18 UTC, Yuki2718 commented on JapaneseFilter/sections/specific.txt
> +appbank.net##a[href^="https://ja.appa"]
Why not `appbank.net##a[href="https://ja.appa.pe/"]`?

2022-02-08 08:51 UTC, zloyden approved these changes

2022-02-08 08:59 UTC, zloyden requested changes

2022-02-08 08:59 UTC, zloyden commented on JapaneseFilter/sections/specific.txt
> +appbank.net##a[href="https://ja.appa.pe/"]
Btw, it seems that the link of this image is stable.
We can remove it via `||appbank.net/wp-content/uploads/*/appape.png`.

2022-02-08 10:19 UTC, zloyden approved these changes

2022-02-08 10:20 UTC, merged