energy.rakuten.co.jp
AdguardTeam/AdguardFilters pull request #110670
Opened 2022-02-16 17:03 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/107686#event-6083777497

<details><summary>Screenshot:</summary>

![Снимок экрана 2022-02-16 в 20 03 21](https://user-images.githubusercontent.com/91964807/154317509-6adf0594-84e1-41ee-b140-67e865b969b1.png)

</details><br/>

2022-02-16 21:18 UTC, zloyden requested changes

2022-02-16 21:18 UTC, zloyden commented on JapaneseFilter/sections/specific.txt
> +energy.rakuten.co.jp##.banner--layout--wrapper
According to the previous report, there is a leftover `.banner--layout--wrapper` and you block `.banner--layout--wrapper`.
I suggest doing a one common rule `energy.rakuten.co.jp##div[class^="banner--layout"]` will be good for current code or `energy.rakuten.co.jp##div[class^="banner-"]`.

2022-02-16 21:22 UTC, zloyden commented on JapaneseFilter/sections/specific.txt
> +energy.rakuten.co.jp##.banner--layout--wrapper
Btw, second rule will be good for other sites with a similar banner.

2022-02-17 10:07 UTC, zloyden approved these changes

2022-02-17 10:07 UTC, merged

2022-02-17 10:21 UTC, Yuki2718 commented
Sorry for late reply. This actually is self-promo.

2022-02-17 10:29 UTC, zloyden commented
Oh really? I had an ad on my end, but now it redirects to their subdomain.