Fix #110896 fashionunited.com
AdguardTeam/AdguardFilters pull request #110897
Opened 2022-02-18 18:49 UTC by Morku

Fix #110896

Page exist in multiple language, e.g. fashionunited.es, fashionunited.fr, fashionunited.com, fashionunited.ch and so on, so I made it more general.

2022-02-19 06:59 UTC, Yuki2718 requested changes
Better `fashionunited.*##.adunitContainer:upward(3)`
and add the domain to `ahaan.co.uk,afteracademy.com,shoppingcidademaringa.com.br##.MuiSnackbar-anchorOriginBottomCenter` in cookies-specific.txt

2022-02-19 10:09 UTC, Morku commented
@Yuki2718 
Rule works fine on Homepage, but will leave a placeholder on https://fashionunited.com/just-in (Screenshot 3 of my report). Thats why I created the second rule with `class^="MuiGrid-root css-".` Any idea how to block both placeholders with one rule?

2022-02-19 16:06 UTC, Yuki2718 commented
Well, actually at first I saw them so suggested `fashionunited.*##.MuiGrid-root > div.MuiGrid-root[padding] > div[class^="css"] > div > div[class^="css"] > div.adunitContainer:upward(4)` as well before editing my comment but then didn't see - now I see agian, strange.

2022-02-19 16:25 UTC, Morku reviewed
update

2022-02-19 16:41 UTC, Yuki2718 approved these changes

2022-02-20 21:38 UTC, zloyden requested changes

2022-02-20 21:38 UTC, zloyden commented on EnglishFilter/sections/specific.txt
> +fashionunited.*##.adunitContainer:upward(3)
@Morku It has to be in `css_extended` file and written via `#?#` - will move it.
As I can see, it works fine on the website.
Btw, we have added comments at the headers of the each file - please read them.

2022-02-20 21:39 UTC, zloyden approved these changes

2022-02-20 21:40 UTC, merged