Fix #110936 www.nivea.de
AdguardTeam/AdguardFilters pull request #110937
Opened 2022-02-19 13:32 UTC by Morku

Fix #110936

2022-02-19 14:00 UTC, Morku reviewed
checked other language pages, too

2022-02-19 17:13 UTC, gork7777 commented on AnnoyancesFilter/sections/cookies_specific.txt
> +nivea.sk,nivea.si,nivea.se,nivea.rs,nivea.ro,nivea.pt,nivea.pl,nivea.no,nivea.nl,nivea.lv,nivea.lt,nivea.it,nivea.gr,nivea.hr,nivea.hu,nivea.fr,nivea.fi,nivea.es,nivea.ee,nivea.dk,nivea.cz,nivea.bg,n
It's better use `nivea.*` rule.

2022-02-25 11:41 UTC, zloyden requested changes

2022-02-25 11:41 UTC, zloyden commented on AnnoyancesFilter/sections/cookies_specific.txt
> +nivea.sk,nivea.si,nivea.se,nivea.rs,nivea.ro,nivea.pt,nivea.pl,nivea.no,nivea.nl,nivea.lv,nivea.lt,nivea.it,nivea.gr,nivea.hr,nivea.hu,nivea.fr,nivea.fi,nivea.es,nivea.ee,nivea.dk,nivea.cz,nivea.bg,n
@Morku I agree about the rule above.
```
nivea.*,absolventa.de,porzellanhandel24.de,blastbrigade.com,blic.rs,queer.de,inqa.de,bmas.de,mail.ru###cmpbox
```

2022-02-25 11:41 UTC, zloyden commented on AnnoyancesFilter/sections/cookies_specific.txt
> +nivea.com.au,nivea-ir.com,nivea-me.com,nivea.az,nivea.be,nivea.by,nivea.ca,nivea.ch,nivea.cl,nivea.co.id,nivea.co.il,nivea.co.ke,nivea.co.kr,nivea.co.th,nivea.co.uk,nivea.co.za,nivea.com.ar,nivea.com
@Morku you can also improve the rule here.
```
nivea.*##.nx-cookie-policy-popup
```

2022-02-25 11:45 UTC, Morku reviewed
update

2022-02-25 11:46 UTC, zloyden approved these changes

2022-02-25 11:47 UTC, merged

2022-02-25 11:48 UTC, zloyden commented
> update

Thank you! I will be glad to see you in futher pull requests :)

2022-02-25 12:19 UTC, Morku commented
@zloyden 
Thank you. I will try :) but my knowledge is still very limited and still don't know like when using blocking rule or extended css. Also still a lot of try and error by comparing with examples.

2022-02-25 12:22 UTC, gork7777 commented
@Morku You can also check this: [Syntax Meanings](https://github.com/DandelionSprout/adfilt/blob/master/Wiki/SyntaxMeaningsThatAreActuallyHumanReadable.md)

2022-02-25 12:49 UTC, zloyden commented
@Morku [this ](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters) can help you in creating rules.

> still don't know like when using blocking rule or extended css

Well, in general, it will be much easier for you when you create a lot of rules.
There is a golden rule "the simpler the rule, the better it is".
We use extended css when the HTML code is not simple and / or cosmetic `##` rules may break the website.