mayukitchen.com
AdguardTeam/AdguardFilters pull request #111083
Opened 2022-02-21 16:48 UTC by SKEIDs

Fix #108812

2022-02-23 09:53 UTC, Yuki2718 requested changes
Add the domain to an existing rule `p[style="color:#666;margin-bottom:5px;"]`.

2022-02-24 02:00 UTC, SKEIDs commented
> Add the domain to an existing rule `p[style="color:#666;margin-bottom:5px;"]`.

Done

2022-02-24 10:31 UTC, Yuki2718 approved these changes

2022-02-24 21:08 UTC, zloyden approved these changes

2022-02-24 21:08 UTC, merged