ubr.ua
AdguardTeam/AdguardFilters pull request #111066
Opened 2022-02-21 13:34 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/109814

<details><summary>Screenshot:</summary>

![Снимок экрана 2022-02-21 в 16 34 18](https://user-images.githubusercontent.com/91964807/154965265-2f6805b8-725f-446d-a67a-d4706cd0fa11.png)

</details><br/>

2022-02-24 05:49 UTC, Sergey-Lyapin requested changes

2022-02-24 05:49 UTC, Sergey-Lyapin commented on RussianFilter/sections/specific.txt
> +ubr.ua##div[class^="adubr"]
Добавь еще для этих `ubr.ua##.ubrads`
![adubr](https://user-images.githubusercontent.com/18536328/155465305-afda0b71-99c4-4d8b-9226-5b1fb91caafd.png)

2022-02-24 05:50 UTC, Sergey-Lyapin commented
@jellizaveta там еще реклама от LuckyAds появилась, посмотри, пожалуйста.

2022-02-25 09:31 UTC, zloyden approved these changes

2022-02-25 09:32 UTC, merged