spb.aptekamos.ru
AdguardTeam/AdguardFilters pull request #111144
Opened 2022-02-22 13:21 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/109360

<details><summary>Screenshot:</summary>

![Снимок экрана 2022-02-22 в 16 21 02](https://user-images.githubusercontent.com/91964807/155140631-96fb5d06-5165-4ec0-bbe3-d3c2d6815fd3.png)

</details><br/>

2022-02-22 13:59 UTC, zloyden requested changes

2022-02-22 13:59 UTC, zloyden commented on RussianFilter/sections/specific.txt
> +||aptekamos.ru/Services/WImages/getImage
Блокируется не только реклама. Я б оставил только правила скрытия.
На главной есть реклама `aptekamos.ru###data-column-center-adv`.

2022-02-22 13:59 UTC, zloyden commented on RussianFilter/sections/specific.txt
> +spb.aptekamos.ru##.orgs-adv-c
В мобильной верстке не применится, к тому же правило нужно для всего домена. Попробуй ниже
```
aptekamos.ru##div[class*="-adv-"]
```

2022-02-22 17:00 UTC, Alex-302 requested changes

2022-02-22 17:00 UTC, Alex-302 commented on RussianFilter/sections/specific.txt
> +spb.aptekamos.ru##.orgs-adv-c
Поддомен тоже убрать нужно
![image](https://user-images.githubusercontent.com/8361299/155181194-5ccffadc-835a-4731-95ff-bc30201a1c17.png)

2022-02-23 21:18 UTC, zloyden requested changes

2022-02-23 21:18 UTC, zloyden commented on RussianFilter/sections/specific.txt
> +spb.aptekamos.ru##.orgs-adv-c
Это правило не нужно из-за выше имеющегося.

2022-02-24 11:07 UTC, zloyden approved these changes

2022-02-24 11:08 UTC, merged