up-load.io
AdguardTeam/AdguardFilters pull request #111138
Opened 2022-02-22 11:13 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/107900

<details><summary>Screenshot:</summary>

![Снимок экрана 2022-02-22 в 14 13 27](https://user-images.githubusercontent.com/91964807/155121270-2d10d73e-dfbd-419c-9629-6b4e86f4c880.png)

</details><br/>

2022-02-22 16:52 UTC, Alex-302 requested changes
Ещё пропущен кликандер и пуш-уведомление.

2022-02-22 16:52 UTC, Alex-302 commented on AnnoyancesFilter/sections/popups.txt
> +up-load.io##a[href][style^="position: fixed; z-index: 43926454"]
У себя такого не наблюдаю. Для чего оно?

2022-02-24 09:43 UTC, jellizaveta commented on AnnoyancesFilter/sections/popups.txt
> +up-load.io##a[href][style^="position: fixed; z-index: 43926454"]
Для кликандера на сайте

2022-02-25 12:08 UTC, Alex-302 commented on AnnoyancesFilter/sections/popups.txt
> +up-load.io##a[href][style^="position: fixed; z-index: 43926454"]
А покажи код. Может его сторонний скрипт создаёт?

2022-02-25 12:12 UTC, Alex-302 requested changes

2022-02-25 12:12 UTC, Alex-302 commented on AnnoyancesFilter/sections/popups.txt
> +up-load.io##a[href][style^="position: fixed; z-index: 43926454"]
Да, именно так.
Для пуш уведомлений:
`||up-load.io/sw.js`
Для кликандера:
`up-load.io#%#//scriptlet("abort-current-inline-script", "document.createElement", "delete window")`
Для куки
`up-load.io###gdpr-cookie-notice`

2022-02-28 18:53 UTC, Alex-302 approved these changes

2022-02-28 18:54 UTC, merged