www.seatguru.com
AdguardTeam/AdguardFilters pull request #111396
Opened 2022-02-25 10:24 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/109861

<details><summary>Screenshot:</summary>

![Снимок экрана 2022-02-25 в 13 23 49](https://user-images.githubusercontent.com/91964807/155698756-dc3e653f-b661-4a00-89db-afb4c3f15642.png)

</details><br/>

2022-02-25 10:47 UTC, zloyden requested changes

2022-02-25 10:47 UTC, zloyden commented on SpanishFilter/sections/specific.txt
> +seatguru.com,elcorillord.com,taringamp3.com,teledeporteshd.com###TB_window
Not an ad, please move the rules to the subscrtipion file.
```
seatguru.com###TB_overlay
seatguru.com###TB_window
```

2022-02-28 19:13 UTC, Alex-302 approved these changes

2022-02-28 19:14 UTC, Alex-302 requested changes
Из испанского удалить надо ж.

2022-03-01 09:35 UTC, zloyden approved these changes

2022-03-01 09:35 UTC, merged