Various cookie fixes
AdguardTeam/AdguardFilters pull request #111387
Opened 2022-02-25 08:39 UTC by Fisherman-Ulysses

```
aecom.com
ao.com
crecipe.com
gezondheidsplein.nl
gorillas.io
hampel-auctions.com
infomir.eu
litmind.com
lucidsamples.com
moomoo.io
rogerfederer.com
rohan.co.uk
rome2rio.com
routerchart.com,droidchart.com
shannons.com.au
skargards.com
spbtv.online
thebanker.com
tinder.com
tvgids24.nl
```

2022-02-25 10:19 UTC, Alex-302 requested changes

2022-02-25 10:19 UTC, Alex-302 commented on AnnoyancesFilter/sections/cookies_specific.txt
> -litmind.es###bottom_notice
It is still necessary.

2022-02-25 10:29 UTC, Fisherman-Ulysses commented on AnnoyancesFilter/sections/cookies_specific.txt
> -litmind.es###bottom_notice
Repaired.

2022-04-04 12:39 UTC, Alex-302 requested changes

2022-04-04 12:39 UTC, Alex-302 commented on AnnoyancesFilter/sections/cookies_specific.txt
> -tinder.com###___gatsby > div.Pos\(f\).Start\(0\).End\(0\).Bxsh\(\$bxsh-4-way-spread\).B\(0\)
`tinder.com###___gatsby > div.Pos\(f\).Start\(0\).End\(0\).Bxsh\(\$bxsh-4-way-spread\).B\(0\)`
still used on mobile.

2022-04-08 10:19 UTC, Alex-302 approved these changes

2022-04-08 10:24 UTC, merged