news.ru
AdguardTeam/AdguardFilters pull request #111437
Opened 2022-02-25 16:03 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/110187

<details><summary>Screenshot:</summary>

![Снимок экрана 2022-02-25 в 19 03 26](https://user-images.githubusercontent.com/91964807/155747509-7fca136a-b01c-4e1e-a2ee-11f334705817.png)

</details><br/>

2022-02-27 21:12 UTC, zloyden requested changes

2022-02-27 21:12 UTC, zloyden commented on RussianFilter/sections/specific.txt
> +news.ru,interfax-russia.ru,kursk-izvestia.ru,dp.ru,lentv24.ru,runews24.ru,bfm.ru,starhit.ru,ctnews.ru,kp40.ru,politring.com,ura.news,osnmedia.ru,interfax.by,lifehacker.ru,miasskiy.ru,eadaily.com,golo
Не работает. Для начала добавь домен к правилу `##div[id^="unit_"]` и убери остаток.

2022-02-28 10:51 UTC, zloyden commented on RussianFilter/sections/specific.txt
> +news.ru##.white-block
https://news.ru/music/vmesto-yurkissa-gudkov-lyusya-chebotina-udivila-novoj-pesnej-aeroekspress/ здесь у этого элемента другой класс, проверь другие разделы.
Попробуй это
```
news.ru#?#.post-wrapper > div[class]:has(> div.container > div.row > div[class^="col-"] > div[id^="adfox_"])
```

2022-02-28 11:23 UTC, jellizaveta commented on RussianFilter/sections/specific.txt
> +news.ru##.white-block
может быть :
`news.ru##.post-wrapper > div[class^="white-"]`

2022-02-28 12:04 UTC, zloyden commented on RussianFilter/sections/specific.txt
> +news.ru##.white-block
Там был еще `.blocks-wrapper` и верстка менялась - сейчас сайт недоступен.
Лучше подобное через расширенный CSS убрать - добавь правило выше.
Также в specific можешь внести ниже правила.
```
news.ru##.post-wrapper > div[class^="white-"]
news.ru##.post-wrapper > div.default-block
news.ru##.post-wrapper > div.blocks-wrapper
```

2022-02-28 12:37 UTC, zloyden approved these changes

2022-02-28 12:37 UTC, merged