suumo.jp
AdguardTeam/AdguardFilters pull request #111411
Opened 2022-02-25 13:17 UTC by gork7777

issue: #111346

2022-02-25 13:26 UTC, Yuki2718 requested changes

2022-02-25 13:26 UTC, Yuki2718 commented on JapaneseFilter/sections/specific.txt
> +suumo.jp##div[class^="pr-banner-"]
This is not ad or even annoyance,  plz remove this rule.

2022-02-25 13:36 UTC, Yuki2718 approved these changes

2022-02-27 21:25 UTC, zloyden approved these changes

2022-02-27 21:25 UTC, merged