sp.nicovideo.jp
AdguardTeam/AdguardFilters pull request #111565
Opened 2022-02-28 01:59 UTC by SKEIDs

Fix #111334

2022-03-24 14:40 UTC, Alex-302 requested changes

2022-03-24 14:40 UTC, Alex-302 commented on SocialFilter/sections/specific.txt
> +sp.nicovideo.jp##.siteWide-Sheet_Contents > div.siteWide-SheetContent:contains(共有)
to css_extended.txt

2022-03-24 15:33 UTC, SKEIDs commented on AnnoyancesFilter/sections/annoyances.txt
> +sp.nicovideo.jp###jsBlockedPremiumMiddleBannerContainer
okay

2022-03-24 15:34 UTC, SKEIDs commented on SocialFilter/sections/specific.txt
> +sp.nicovideo.jp##.siteWide-Sheet_Contents > div.siteWide-SheetContent:contains(共有)
okay

2022-04-04 11:55 UTC, Alex-302 approved these changes

2022-04-04 11:59 UTC, merged