www.xlarge.com
AdguardTeam/AdguardFilters pull request #111766
Opened 2022-03-02 17:26 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/110005

<details><summary>Screenshot:</summary>

![Снимок экрана 2022-03-02 в 20 26 03](https://user-images.githubusercontent.com/91964807/156415073-31ec2fbd-a58e-40fb-8c44-724cb0d72c81.png)

![Снимок экрана 2022-03-02 в 20 26 25](https://user-images.githubusercontent.com/91964807/156415136-6c542f64-7d53-4ecf-9504-1305a90def35.png)

</details><br/>

2022-03-02 21:20 UTC, zloyden requested changes

2022-03-02 21:20 UTC, zloyden commented on AnnoyancesFilter/sections/subscriptions.txt
> +xlarge.com#$#.modal-backdrop
`xlarge.com#$#.modal-backdrop { display: none !important; }`

2022-03-02 21:20 UTC, zloyden commented on AnnoyancesFilter/sections/subscriptions.txt
> +xlarge.com#$#body.modal-open { overflow: auto !important; }
`xlarge.com#$#body.modal-open { overflow: auto !important; padding-right: 0 !important; }
`

2022-03-02 22:00 UTC, Alex-302 commented on AnnoyancesFilter/sections/subscriptions.txt
> +xlarge.com#$#body.modal-open { overflow: auto !important; }
Напиши ж, что `padding-right: 0 !important;` - чтобы сдвига страницы не было.

2022-03-03 08:38 UTC, zloyden commented on AnnoyancesFilter/sections/subscriptions.txt
> +xlarge.com#$#body.modal-open { overflow: auto !important; }
Это уже объяснялось.

2022-03-03 08:43 UTC, zloyden approved these changes

2022-03-03 08:43 UTC, merged