www.eigeki.com
AdguardTeam/AdguardFilters pull request #111823
Opened 2022-03-03 12:18 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/110099

<details><summary>Screenshot:</summary>

![Снимок экрана 2022-03-03 в 15 16 43](https://user-images.githubusercontent.com/91964807/156563108-612a040c-c5e6-4b28-8a31-960cb9ad1ca5.png)

![Снимок экрана 2022-03-03 в 15 16 07](https://user-images.githubusercontent.com/91964807/156563032-71c322d8-159f-4020-870e-ae78417070dc.png)

</details><br/>

2022-03-03 15:08 UTC, Alex-302 requested changes

2022-03-03 15:08 UTC, Alex-302 commented on SocialFilter/sections/specific.txt
> +eigeki.com##.list-social
Судя по publicwww, можно сделать общим правило
`bilemezsin.com##a[href^="javascript:window.open('http://www.facebook.com/sharer.php"]`

2022-03-05 07:41 UTC, zloyden commented on SocialFilter/sections/specific.txt
> +eigeki.com,bilemezsin.com##a[href^="javascript:window.open('http://www.facebook.com/sharer.php"]
Так понимаю `сделать общим` имелось в виду это правило рядом с похожими
```
~facebook.com##a[href^="javascript:window.open('http://www.facebook.com/sharer.php"]
```

2022-03-05 14:41 UTC, Alex-302 commented on SocialFilter/sections/specific.txt
> +eigeki.com,bilemezsin.com##a[href^="javascript:window.open('http://www.facebook.com/sharer.php"]
@jellizaveta Да. В generichide без доменов перенеси(facebook.com исключать не надо, там такое не используется).

2022-03-05 15:01 UTC, zloyden approved these changes

2022-03-05 15:05 UTC, Alex-302 approved these changes

2022-03-05 15:05 UTC, merged