Fix #112571 city-advisor.de
AdguardTeam/AdguardFilters pull request #112573
Opened 2022-03-11 14:09 UTC by Morku

Fix #112571

2022-03-11 14:52 UTC, Morku reviewed
Update to make a short rule which also works fine

2022-03-14 06:38 UTC, zloyden requested changes

2022-03-14 06:38 UTC, zloyden commented on GermanFilter/sections/specific.txt
> +city-advisor.de##div[style^="min-height:"]
Better `city-advisor.de##center > div[style^="min-height:"]`

2022-03-14 06:39 UTC, zloyden approved these changes

2022-03-14 06:39 UTC, merged