tokai.hostlove.com
AdguardTeam/AdguardFilters pull request #112576
Opened 2022-03-11 14:20 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/111255

<details><summary>Screenshot:</summary>

<img width="773" alt="Снимок экрана 2022-03-11 в 16 20 01" src="https://user-images.githubusercontent.com/91964807/157885298-0bba54ca-c525-4112-b150-7f5f0def7003.png">

</details><br/>

2022-03-11 17:07 UTC, Yuki2718 requested changes

2022-03-11 17:07 UTC, Yuki2718 commented on JapaneseFilter/sections/specific.txt
> +tokai.hostlove.com###sub
This is self-promo.

2022-03-11 17:07 UTC, Yuki2718 commented on SocialFilter/sections/specific.txt
> +tokai.hostlove.com##aside:not(.foot) > .line-button
The one in the foot can also be blocked.

2022-03-14 14:56 UTC, Yuki2718 approved these changes

2022-03-14 14:57 UTC, zloyden approved these changes

2022-03-14 14:57 UTC, merged