twitch.tv promoted streams
AdguardTeam/AdguardFilters pull request #112714
Opened 2022-03-12 16:14 UTC by zopieux

[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: Removes tiles with a *Promoted* tag.
* **Current behaviour**: twitch.tv obnoxiously displays irrelevant *Promoted* streams

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/81353/158025590-e1c4cfe8-16d5-48ec-a0f9-af918afc09f1.png)

</details><br/>

* **Expected behaviour**: the landing page has no *Promoted* streams

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

(same as above but without the first "Promoted" tile)

</details><br/>

***Steps to reproduce the problem***:

* Browse to https://twitch.tv, you might want to be logged-in

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

Irrelevant. uBlock Origin.

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Browser:                               | irrelevant, Firefox

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

2022-03-14 13:52 UTC, Alex-302 requested changes

2022-03-25 17:23 UTC, zopieux commented on EnglishFilter/sections/specific.txt
> +twitch.tv##div.tw-tower > div:has(div.promoted-card-stat__promotion)
Where should this rule go if it's just an annoyance?

2022-03-28 11:51 UTC, Alex-302 commented on EnglishFilter/sections/specific.txt
> +twitch.tv##div.tw-tower > div:has(div.promoted-card-stat__promotion)
`annoyances.txt` with a comment
`! https://github.com/AdguardTeam/AdguardFilters/pull/112714`

2022-04-15 11:35 UTC, zloyden commented on EnglishFilter/sections/specific.txt
> +twitch.tv##div.tw-tower > div:has(div.promoted-card-stat__promotion)
Not reproduced on my end even with VPN. If it's still needed, just let us know and provide the HTML code of the element via screenshot.

2022-04-15 11:35 UTC, closed without merging

2022-04-15 13:46 UTC, zopieux commented
Screenshot without the proposed rule active:

![image](https://user-images.githubusercontent.com/81353/163576033-958de7f5-76f0-45fc-b58d-c1b378a8232e.png)

Note the *Promoted* tag on the first tile.

<details><summary>Full CSS path of the "Promoted" tag inside the tile</summary>

```
html.tw-root--hover.js-focus-visible.tw-root--theme-dark body.logged-in.dark-theme div#root.root div.Layout-sc-nxg1ff-0.eoQePv div.Layout-sc-nxg1ff-0.qViOJ div.Layout-sc-nxg1ff-0.kXaHWh main.HIDMu.InjectLayout-sc-588ddc-0.twilight-main div.root-scrollable.scrollable-area.scrollable-area--suppress-scroll-x div.simplebar-scroll-content div.simplebar-content.root-scrollable__content div.Layout-sc-nxg1ff-0.ixIPwG.root-scrollable__wrapper div.Layout-sc-nxg1ff-0.gSrRkc div.Layout-sc-nxg1ff-0.htdeQe div.common-centered-column div.Layout-sc-nxg1ff-0.kFmUXF div.Layout-sc-nxg1ff-0.jtfskf div div.Layout-sc-nxg1ff-0.jMIEhW.find-me div div.InjectLayout-sc-588ddc-0.kSsaPb.tw-transition-group div.ScTower-sc-1dei8tr-0.lfgJSv.tw-tower div.ScTransitionBase-sc-eg1bd7-0.hvzifB.tw-transition div.shelf-card__impression-wrapper div.Layout-sc-nxg1ff-0.rFxYs article.Layout-sc-nxg1ff-0.hTbBzX div.ScWrapper-sc-uo2e2v-0.dfkSfj.tw-hover-accent-effect div.ScTransformWrapper-sc-uo2e2v-1.icKHub a.ScCoreLink-sc-udwpw5-0.hUIOdd.tw-link div.Layout-sc-nxg1ff-0.bcTnJT div.ScPositionCorner-sc-1iiybo2-1.fIveqX div.Layout-sc-nxg1ff-0.dCnCm.preview-card-stat.promoted-card-stat__promotion p.CoreText-sc-cpl358-0.cheZRZ
```

XPath for convenience:

```
/html/body/div[1]/div/div[2]/div[1]/main/div[2]/div[3]/div/div/div/div[2]/div/div/div[1]/div[1]/div/div[2]/div[1]/div/div[1]/div/div/article/div[2]/div[5]/a/div/div[3]/div/p
```
</details>

<details><summary>Full HTML code of the "Live channels we think you'll like" section</summary>

```
<div aria-labelledby="eae37bf3375bda8c"><div class="InjectLayout-sc-588ddc-0 kSsaPb tw-transition-group"><div class="ScTower-sc-1dei8tr-0 lfgJSv tw-tower"><div style="transition-property: transform, opacity; transition-timing-function: ease;" class="ScTransitionBase-sc-eg1bd7-0 hvzifB tw-transition"><div class="shelf-card__impression-wrapper"><div data-test-selector="shelf-card-selector" class="Layout-sc-nxg1ff-0 rFxYs"><article class="Layout-sc-nxg1ff-0 hTbBzX"><div class="Layout-sc-nxg1ff-0 gIDgyI"><div class="Layout-sc-nxg1ff-0 iTDkvD"><div class="ScTextWrapper-sc-14f6evl-1 cndMhY"><div class="ScTextMargin-sc-14f6evl-2 feEGBq"><div class="Layout-sc-nxg1ff-0 AjNUj"><a lines="1" data-a-target="preview-card-title-link" class="ScCoreLink-sc-udwpw5-0 iwYxXk ScCoreLink-sc-ybxm10-0 iEEhdE tw-link" href="/sephijin"><h3 title="AR 59 | Fin de l'Event d'inazuma ? 🔥 Guide Ayato !ayato 🔥 Ayaka J-4 | Flex/Conseils/Entraide 🔥" class="CoreText-sc-cpl358-0 hkccBP">AR 59 | Fin de l'Event d'inazuma ? 🔥 Guide Ayato !ayato 🔥 Ayaka J-4 | Flex/Conseils/Entraide 🔥</h3></a></div></div><div class="ScTextMargin-sc-14f6evl-2 feEGBq"><p class="CoreText-sc-cpl358-0 gzYAzs"><a data-test-selector="ChannelLink" data-a-target="preview-card-channel-link" class="ScCoreLink-sc-udwpw5-0 iwYxXk tw-link" href="/sephijin">Sephijin</a></p><p class="CoreText-sc-cpl358-0 gzYAzs"><a data-test-selector="GameLink" data-a-target="preview-card-game-link" class="ScCoreLink-sc-udwpw5-0 iwYxXk tw-link" href="/directory/game/Genshin%20Impact">Genshin Impact</a></p></div><div class="Layout-sc-nxg1ff-0 gwFCeO"><div class="InjectLayout-sc-588ddc-0 bFhJdp"><div class="InjectLayout-sc-588ddc-0 hoDLKA"><a class="ScTag-sc-xzp4i-0 hrkHJN tw-tag" aria-label="French" data-a-target="French" href="/directory/all/tags/6f655045-9989-4ef7-8f85-1edcec42d648"><div class="ScTagContent-sc-xzp4i-1 iYcwjl">French</div></a></div></div></div></div><div class="ScImageWrapper-sc-14f6evl-0 eBvtgw"><a data-test-selector="preview-card-avatar" class="ScCoreLink-sc-udwpw5-0 hUIOdd tw-link" href="/sephijin"><div class="ScAspectRatio-sc-1sw3lwy-1 flFnOO tw-aspect"><div class="ScAspectSpacer-sc-1sw3lwy-0 giUbvo"></div><figure aria-label="Sephijin" class="ScAvatar-sc-12nlgut-0 hnnsXF tw-avatar"><img class="InjectLayout-sc-588ddc-0 bxsmXn tw-image tw-image-avatar" alt="Sephijin" src="https://static-cdn.jtvnw.net/jtv_user_pictures/e59b8fa3-72ae-421c-9ed7-50ceafc50e48-profile_image-50x50.png"></figure></div></a></div><div class="Layout-sc-nxg1ff-0 juqWgS"><div class="Layout-sc-nxg1ff-0 jmNaht"><div class="InjectLayout-sc-588ddc-0 gcUMwz"><div class="Layout-sc-nxg1ff-0 feedback-card"><div data-toggle-balloon-id="e562d527-65a8-43ac-8ef6-2d761f9933e0" class="Layout-sc-nxg1ff-0 jMIEhW"><div style="display: inherit;" data-test-selector="toggle-balloon-wrapper__mouse-enter-detector"><button class="ScCoreButton-sc-1qn4ixc-0 eHLLjG ScButtonIcon-sc-o7ndmn-0 cvGRzc" aria-label="Recommendation feedback" data-a-target="rec-feedback-card-button"><div class="ButtonIconFigure-sc-1ttmz5m-0 hsbiRb"><div class="ScIconLayout-sc-1bgeryd-0 dPgmNu"><div class="ScAspectRatio-sc-1sw3lwy-1 dJaMsL tw-aspect"><div class="ScAspectSpacer-sc-1sw3lwy-0 giUbvo"></div><svg width="100%" height="100%" version="1.1" viewBox="0 0 20 20" x="0px" y="0px" class="ScIconSVG-sc-1bgeryd-1 hcjcOH"><g><path d="M10 18a2 2 0 110-4 2 2 0 010 4zM10 12a2 2 0 110-4 2 2 0 010 4zM8 4a2 2 0 104 0 2 2 0 00-4 0z"></path></g></svg></div></div></div></button></div></div></div></div></div></div></div></div><div class="ScWrapper-sc-uo2e2v-0 dfkSfj tw-hover-accent-effect"><div class="ScTransformWrapper-sc-uo2e2v-1 ScCornerTop-sc-uo2e2v-2 dKYJaX eXxFuv"></div><div class="ScTransformWrapper-sc-uo2e2v-1 ScCornerBottom-sc-uo2e2v-3 bNOuEj dzSwHO"></div><div class="ScTransformWrapper-sc-uo2e2v-1 ScEdgeLeft-sc-uo2e2v-4 kIKqjn cdcwLw"></div><div class="ScTransformWrapper-sc-uo2e2v-1 ScEdgeBottom-sc-uo2e2v-5 cuGbfn geiifk"></div><div class="ScTransformWrapper-sc-uo2e2v-1 icKHub"><a data-a-target="preview-card-image-link" class="ScCoreLink-sc-udwpw5-0 hUIOdd tw-link" href="/sephijin"><div class="Layout-sc-nxg1ff-0 bcTnJT"><div class="ScAspectRatio-sc-1sw3lwy-1 dJaMsL tw-aspect"><div class="ScAspectSpacer-sc-1sw3lwy-0 lnBtND"></div><img alt="AR 59 | Fin de l'Event d'inazuma ? 🔥 Guide Ayato !ayato 🔥 Ayaka J-4 | Flex/Conseils/Entraide 🔥" class="tw-image" src="https://static-cdn.jtvnw.net/previews-ttv/live_user_sephijin-440x248.jpg"></div><div class="ScPositionCorner-sc-1iiybo2-1 ibaFTb"><div class="ScChannelStatusTextIndicator-sc-1f5ghgf-0 cbXzwD tw-channel-status-text-indicator" font-size="font-size-6"><p class="CoreText-sc-cpl358-0 joOBZx">LIVE</p></div></div><div class="ScPositionCorner-sc-1iiybo2-1 fIveqX"><div class="Layout-sc-nxg1ff-0 dCnCm preview-card-stat promoted-card-stat__promotion"><p data-a-target="PROMOTION" class="CoreText-sc-cpl358-0 cheZRZ">Promoted</p></div></div></div></a></div></div></article></div></div></div><div style="transition-property: transform, opacity; transition-timing-function: ease;" class="ScTransitionBase-sc-eg1bd7-0 hvzifB tw-transition"><div class="shelf-card__impression-wrapper"><div data-test-selector="shelf-card-selector" class="Layout-sc-nxg1ff-0 rFxYs"><article class="Layout-sc-nxg1ff-0 hTbBzX"><div class="Layout-sc-nxg1ff-0 gIDgyI"><div class="Layout-sc-nxg1ff-0 iTDkvD"><div class="ScTextWrapper-sc-14f6evl-1 cndMhY"><div class="ScTextMargin-sc-14f6evl-2 feEGBq"><div class="Layout-sc-nxg1ff-0 AjNUj"><a lines="1" data-a-target="preview-card-title-link" class="ScCoreLink-sc-udwpw5-0 iwYxXk ScCoreLink-sc-ybxm10-0 iEEhdE tw-link" href="/kennystream"><h3 title="Trackmania - Est-ce que je reprend la guitare ?" class="CoreText-sc-cpl358-0 hkccBP">Trackmania - Est-ce que je reprend la guitare ?</h3></a></div></div><div class="ScTextMargin-sc-14f6evl-2 feEGBq"><p class="CoreText-sc-cpl358-0 gzYAzs"><a data-test-selector="ChannelLink" data-a-target="preview-card-channel-link" class="ScCoreLink-sc-udwpw5-0 iwYxXk tw-link" href="/kennystream">KennyStream</a></p><p class="CoreText-sc-cpl358-0 gzYAzs"><a data-test-selector="GameLink" data-a-target="preview-card-game-link" class="ScCoreLink-sc-udwpw5-0 iwYxXk t [...]

2022-04-15 13:46 UTC, zopieux commented on EnglishFilter/sections/specific.txt
> +twitch.tv##div.tw-tower > div:has(div.promoted-card-stat__promotion)
Twitch might have differential rollout policies per country, per account (A/B testing), and such. Please consider this when closing PRs that are not 100% reproducible. Moved the filter to `annoyances.txt` as requested and provided more details in a reply.

2022-04-15 13:47 UTC, zopieux commented
It seems like GitHub does not update the UI when a branch is pushed while a PR is closed. @zloyden can you reopen please?

2022-04-15 13:54 UTC, zloyden commented
It seems I also cannot reopen the pull request, but added your rule directly https://github.com/AdguardTeam/AdguardFilters/commit/721d1328f4a8b9171a271e6dcabf797b3820677d

2022-04-15 14:21 UTC, zopieux commented
Great, thanks!