copytoon248.com
AdguardTeam/AdguardFilters pull request #112835
Opened 2022-03-14 12:11 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/111638

<details><summary>Screenshot:</summary>

<img width="1044" alt="Снимок экрана 2022-03-14 в 14 10 00" src="https://user-images.githubusercontent.com/91964807/158169310-ddd5e0ae-14d4-4306-8595-ea7a191551c7.png">

![image](%screenshot_url%)
</details><br/>

2022-03-16 13:16 UTC, Alex-302 requested changes

2022-03-16 13:16 UTC, Alex-302 commented on EnglishFilter/sections/foreign.txt
> +||cloudaaaa.com/a/*.gif
this is ad server, user for banners only

2022-03-16 13:16 UTC, Alex-302 commented on EnglishFilter/sections/foreign.txt
> +copytoon251.com##.banner_m
they change domains from time to time. You can add smth like that: `##a[href^="https://copytoon"][href*="/bannerhit.php?bn_id="]`

2022-03-17 06:41 UTC, zloyden requested changes

2022-03-17 06:41 UTC, zloyden commented on EnglishFilter/sections/foreign.txt
> +copytoon251.com##.banner_m
Please revert the task link.

2022-03-17 09:30 UTC, zloyden approved these changes

2022-03-17 09:31 UTC, merged