freetp.org
AdguardTeam/AdguardFilters pull request #112815
Opened 2022-03-14 08:07 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/111736

<details><summary>Screenshot:</summary>

<img width="1790" alt="Снимок экрана 2022-03-14 в 10 07 39" src="https://user-images.githubusercontent.com/91964807/158130406-6eb9ae0b-1fb3-42df-95f6-9a4505919c11.png">

</details><br/>

2022-03-14 10:59 UTC, Alex-302 approved these changes

2022-03-14 10:59 UTC, Alex-302 commented
А реклама?
![image](https://user-images.githubusercontent.com/8361299/158159121-de2954dd-aa0f-4edb-baf1-e904240deadd.png)

2022-03-15 07:22 UTC, zloyden requested changes

2022-03-15 07:22 UTC, zloyden commented on RussianFilter/sections/specific.txt
> +freetp.org##a[href^="https://mysoftrotate.ru"][target="_blank"] > img
Одного из этих правил достаточно - оставь блокировку по запросу.

2022-03-15 10:14 UTC, zloyden approved these changes

2022-03-15 10:15 UTC, merged