markezine.jp
AdguardTeam/AdguardFilters pull request #112958
Opened 2022-03-15 15:20 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/112415

<details><summary>Screenshot:</summary>

<img width="494" alt="Снимок экрана 2022-03-15 в 17 17 55" src="https://user-images.githubusercontent.com/91964807/158410659-1f50cceb-2f1b-4f14-be8a-9a689d785513.png">

<img width="391" alt="Снимок экрана 2022-03-15 в 17 18 55" src="https://user-images.githubusercontent.com/91964807/158410867-2a76d1cb-217a-4326-a0b7-c50ff3ef40e6.png">

<img width="467" alt="Снимок экрана 2022-03-15 в 17 18 06" src="https://user-images.githubusercontent.com/91964807/158410692-615bc971-912e-4680-a27a-e98ed4d4b954.png">

</details><br/>

2022-03-15 16:37 UTC, Yuki2718 requested changes

2022-03-16 14:05 UTC, Alex-302 requested changes

2022-03-16 14:05 UTC, Alex-302 commented on JapaneseFilter/sections/css_extended.txt
> +markezine.jp##.l-sidebar_inner > .c-secondarysection:has(> .c-secondarysection_header > p.c-secondarysection_heading:contains(スポンサーサイト))
`#?#`

2022-03-16 14:05 UTC, Alex-302 commented on SocialFilter/sections/specific.txt
> +markezine.jp##li[class^="c-article"] > a[href^="https://note.com/"]
Agree.

2022-03-16 14:29 UTC, zloyden requested changes

2022-03-16 14:29 UTC, zloyden commented on AnnoyancesFilter/sections/tweaks.txt
> +markezine.jp#$#.l-sidebar_inner > .ad-job-board-wrap + .c-secondarysection  { margin-top: 0px !important; }
As I can see, there are typo and missed tags in the rule.
`markezine.jp#$#.l-sidebar_inner > div.ad-job-board-wrap + div.c-secondarysection { margin-top: 0px !important; }`

2022-03-16 14:29 UTC, zloyden commented on JapaneseFilter/sections/css_extended.txt
> +markezine.jp##.l-sidebar_inner > .c-secondarysection:has(> .c-secondarysection_header > p.c-secondarysection_heading:contains(スポンサーサイト))
Missed tags after `>`

2022-03-16 14:29 UTC, zloyden commented on SocialFilter/sections/specific.txt
> +markezine.jp##li[class^="c-article"] > a[href^="https://note.com/"]
@Yuki2718 I would say that your rule is ok here

2022-03-17 06:36 UTC, zloyden approved these changes

2022-03-17 06:37 UTC, merged