theins.ru
AdguardTeam/AdguardFilters pull request #112968
Opened 2022-03-15 16:35 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/112137

<details><summary>Screenshot:</summary>

<img width="1091" alt="Снимок экрана 2022-03-15 в 18 34 29" src="https://user-images.githubusercontent.com/91964807/158426711-8af81810-42ee-442e-b2fd-2deba182a58c.png">

<img width="491" alt="Снимок экрана 2022-03-15 в 18 34 46" src="https://user-images.githubusercontent.com/91964807/158426762-470370db-621e-4e71-b566-f551d7ce28d3.png">

</details><br/>

2022-03-16 13:40 UTC, slavaleleka requested changes
extended css rules should be marked as `#?#`

2022-03-16 13:57 UTC, Alex-302 requested changes

2022-03-16 13:57 UTC, Alex-302 commented on AnnoyancesFilter/sections/self-promo.txt
> +theins.ru###articleContainer > div:has(> a[href="http://donate.theins.ru/"])
Донаты убирать не надо. Только явно броские.

2022-03-16 13:57 UTC, Alex-302 commented on AnnoyancesFilter/sections/self-promo.txt
> +theins.ru##main > div[class] > div[class] > div:has(> div[class] > h2:contains(Понравился наш материал?))
Не наблюдаю.

2022-03-17 06:21 UTC, zloyden approved these changes

2022-03-17 06:23 UTC, merged