ticketjam.jp
AdguardTeam/AdguardFilters pull request #113022
Opened 2022-03-16 08:57 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/112549

<details><summary>Screenshot:</summary>

<img width="848" alt="Снимок экрана 2022-03-16 в 10 56 58" src="https://user-images.githubusercontent.com/91964807/158553276-db7a6d57-e81d-4e11-9ae7-634061213f7d.png">

</details><br/>

2022-03-17 12:02 UTC, Yuki2718 requested changes

2022-03-17 12:02 UTC, Yuki2718 commented on JapaneseFilter/sections/specific.txt
> +ticketjam.jp##.l-section
Do not block this, it just happened to be empty on the posted page but shows useful tags on other pages such as `https://ticketjam.jp/magazine/music/singer-song-writer/15520`.

2022-03-17 15:22 UTC, Yuki2718 approved these changes

2022-03-18 06:28 UTC, zloyden approved these changes

2022-03-18 06:29 UTC, merged