blog.jp
AdguardTeam/AdguardFilters pull request #113522
Opened 2022-03-22 17:25 UTC by gork7777

issue: #113443

2022-03-23 12:16 UTC, Yuki2718 requested changes

2022-03-23 12:16 UTC, Yuki2718 commented on JapaneseFilter/sections/specific.txt
> +nokuo.blog.jp##.rss-blogroll
Move to an existing `##.rss-blogroll` rule in Annoyances > widgets.

2022-03-23 12:16 UTC, Yuki2718 commented on JapaneseFilter/sections/specific.txt
> +nokuo.blog.jp,negisoku.com##.plugin-memo
`##.plugin-memo` is used by thousands of `blog.jp` sites both for ads and for legitimate contents. To cover as much sites as possible without false positve, remove this line and then change an existing rule in css-extended `sunri2525.blog.jp,akb48rompen.com,hattatu-matome.ldblog.jp,blog.livedoor.jp#?#.plugin-memo > div.side > ins.adsbygoogle:upward(2)` to `blog.jp,akb48rompen.com,ldblog.jp,blog.livedoor.jp#?#.plugin-memo > div.side > ins.adsbygoogle:upward(2)`.

2022-03-24 09:38 UTC, zloyden reviewed
I've done it directly.

2022-03-24 09:38 UTC, closed without merging