limia.jp
AdguardTeam/AdguardFilters pull request #113643
Opened 2022-03-23 19:31 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/112309

<details><summary>Screenshot:</summary>

<img width="320" alt="Снимок экрана 2022-03-23 в 21 30 20" src="https://user-images.githubusercontent.com/91964807/159780775-4be257c3-bf98-4705-ac4e-e00c3969d7c1.png">

<img width="318" alt="Снимок экрана 2022-03-23 в 21 31 06" src="https://user-images.githubusercontent.com/91964807/159780896-03cba62c-2bdc-46c9-8e63-1c2a8ae6a67e.png">

</details><br/>

2022-03-25 03:27 UTC, Yuki2718 commented on JapaneseFilter/sections/specific.txt
> +limia.jp##.Post > div.u-textCenter[style="min-height: 160px;"]
I see this only on mobile so maybe Mobile filter?

2022-03-25 03:27 UTC, Yuki2718 commented on JapaneseFilter/sections/specific.txt
> +limia.jp##.Post > div.u-textCenter[style="min-height: 160px;"]
Also `limia.jp#?#.Section > div.OUTBRAIN:upward(1)`

2022-03-25 16:17 UTC, Yuki2718 requested changes

2022-03-25 16:17 UTC, Yuki2718 commented on MobileFilter/sections/specific_web.txt
> +limia.jp#?#.Section > div.OUTBRAIN:upward(1)
This should be in css_exended.

2022-03-25 17:25 UTC, Yuki2718 approved these changes

2022-03-28 06:22 UTC, zloyden approved these changes

2022-03-28 06:23 UTC, merged