shop.driveplaza.com
AdguardTeam/AdguardFilters pull request #113646
Opened 2022-03-23 19:42 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/112316

<details><summary>Screenshot:</summary>

<img width="323" alt="Снимок экрана 2022-03-23 в 21 41 17" src="https://user-images.githubusercontent.com/91964807/159782473-e5a261bb-f559-45bb-b501-0d0a6332082a.png">

<img width="320" alt="Снимок экрана 2022-03-23 в 21 41 38" src="https://user-images.githubusercontent.com/91964807/159782527-062c6818-4681-4a22-996d-897aba11d38d.png">

<img width="406" alt="Снимок экрана 2022-03-23 в 21 40 59" src="https://user-images.githubusercontent.com/91964807/159782414-9d3df086-5d09-499d-9e23-0731537dcbb2.png">

</details><br/>

2022-03-26 11:33 UTC, Yuki2718 requested changes

2022-03-26 11:33 UTC, Yuki2718 commented on JapaneseFilter/sections/specific.txt
> +shop.driveplaza.com###sideBnrArea
These are self-promo. If banners link to their own sites, suspect self-promo.

2022-03-26 11:33 UTC, Yuki2718 commented on MobileFilter/sections/specific_web.txt
> +shop.driveplaza.com###topBnrArea
I don't see this element, where you found?

2022-03-28 09:16 UTC, jellizaveta commented on MobileFilter/sections/specific_web.txt
> +shop.driveplaza.com###topBnrArea
On mobile screen

<details><summary>Screenshot:</summary>

<img width="323" alt="Снимок экрана 2022-03-28 в 12 14 45" src="https://user-images.githubusercontent.com/91964807/160366460-a80ce014-e172-43b3-a20d-4cbbb841df02.png">

</details><br/>

2022-03-28 13:47 UTC, Yuki2718 commented on MobileFilter/sections/specific_web.txt
> +shop.driveplaza.com###topBnrArea
Found thanks, they look to be self-promo.

2022-03-28 13:48 UTC, Yuki2718 approved these changes

2022-03-29 07:26 UTC, zloyden approved these changes

2022-03-29 07:26 UTC, merged