cookien.com
AdguardTeam/AdguardFilters pull request #113724
Opened 2022-03-24 13:38 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/112462

<details><summary>Screenshot:</summary>

<img width="320" alt="Снимок экрана 2022-03-24 в 15 37 40" src="https://user-images.githubusercontent.com/91964807/159928304-3c4477e8-c358-4e3e-84d1-ed7f8bf753f8.png">

<img width="317" alt="Снимок экрана 2022-03-24 в 15 38 41" src="https://user-images.githubusercontent.com/91964807/159928475-6ad26a2d-7c33-4cd2-9c11-8d1df8a54737.png">

</details><br/>

2022-03-24 16:35 UTC, Yuki2718 requested changes

2022-03-24 16:35 UTC, Yuki2718 commented on JapaneseFilter/sections/general_extensions.txt
> +! https://github.com/AdguardTeam/AdguardFilters/issues/112462
Self-promo

2022-03-25 12:50 UTC, Yuki2718 approved these changes

2022-03-25 14:27 UTC, zloyden commented on AnnoyancesFilter/sections/self-promo.txt
> +cookien.com#$#hgroup { top: 0px !important; }
`0px` - `px` is not necessary here

2022-03-28 06:19 UTC, zloyden approved these changes

2022-03-28 06:21 UTC, merged