healthylives.tw
AdguardTeam/AdguardFilters pull request #114923
Opened 2022-04-07 20:30 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/114750

<details><summary>Screenshot:</summary>

<img width="1436" alt="Снимок экрана 2022-04-07 в 23 29 25" src="https://user-images.githubusercontent.com/91964807/162290520-8646567f-0499-4172-9efe-7a0687c00819.png">

<img width="442" alt="Снимок экрана 2022-04-07 в 23 29 38" src="https://user-images.githubusercontent.com/91964807/162290554-1c0613c7-3bdf-43ed-8082-baefd272f3ad.png">

<img width="941" alt="Снимок экрана 2022-04-07 в 23 29 51" src="https://user-images.githubusercontent.com/91964807/162290590-e3ed97e4-a539-4c7a-b6ac-57321d07200f.png">

</details><br/>

2022-04-07 21:36 UTC, Alex-302 requested changes

2022-04-07 21:36 UTC, Alex-302 commented on ChineseFilter/sections/specific.txt
> +healthylives.tw###contentBox > div[style="width:336px;height: 280px;"]
Style is a bit different on my end. `^` is required.(`div[style^="width:336px;height: 280px;"]`)

2022-04-07 21:36 UTC, Alex-302 commented on AnnoyancesFilter/sections/widgets.txt
> +healthylives.tw###fbVideo
You can remove element using extended CSS(`#$?# *** { remove: true; }`) to avoid loading of video(+3.5 MB).

2022-04-08 10:26 UTC, zloyden approved these changes

2022-04-08 10:27 UTC, merged