spots.ru
AdguardTeam/AdguardFilters pull request #115383
Opened 2022-04-12 19:06 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/115151

2022-04-12 19:40 UTC, Alex-302 commented on RussianFilter/sections/adservers.txt
> +||spots.ru^
Тут видимо про рекламные редиректы речь. Их лучше блокировать с `$all`, т.к. без модификатора программы и полноценные расширения по умолчанию не блокируют главный фрейм.

2022-04-13 05:37 UTC, zloyden requested changes

2022-04-13 05:37 UTC, zloyden commented on RussianFilter/sections/adservers.txt
> +||spots.ru^
Ага, именно так. Без модификатора `$all` тут не обойтись - в текущем виде ты просто ограничиваешь загрузку ресурсов с и на этот сайт.

2022-04-13 12:35 UTC, Alex-302 approved these changes

2022-04-13 12:35 UTC, merged