www.standard.co.uk
AdguardTeam/AdguardFilters pull request #115921
Opened 2022-04-18 11:38 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/115751

2022-04-18 17:36 UTC, Alex-302 requested changes
Так сломается плеер. Нужно кликать JS-ным правилом.

Ещё ты скрываешь попап обычным правилом, а прокрутку разблокируешь скриптлетом. В контент блокере будет проблема(вернее была бы, если бы этот вариант был применим без поломки плеера).

2022-04-19 10:31 UTC, jellizaveta commented
У меня не получается больше воспроизвести куки сообщение

2022-04-19 10:36 UTC, zloyden approved these changes

2022-04-19 10:39 UTC, Alex-302 commented
У меня повторилось с Голландским IP. Поправил.

2022-04-19 10:39 UTC, merged