theswagsports.com
AdguardTeam/AdguardFilters pull request #116633
Opened 2022-04-26 18:30 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/116615

<details><summary>Screenshot:</summary>

<img width="817" alt="Снимок экрана 2022-04-26 в 21 29 50" src="https://user-images.githubusercontent.com/91964807/165367953-71e693f0-a67e-4e0d-b6ff-986376877dcf.png">

</details><br/>

2022-04-26 20:38 UTC, Alex-302 requested changes

2022-04-26 20:38 UTC, Alex-302 commented on AnnoyancesFilter/sections/push-notifications.txt
> +||theswagsports.com/aud/message
Not working on my end. Just not shown after page refresh, until service-workers are stopped.
`/firebase-messaging.js$domain=` will help.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/165386347-0d2a41c7-6c0b-454c-97fc-33bfccabed5d.png)

</details>

2022-04-26 20:38 UTC, Alex-302 commented on EnglishFilter/sections/specific.txt
> +theswagsports.com,cinereporters.com##div[id^="HP_P_"][name="Homepage-Paid-Top-1-Desktop"]
Да на такие мелочи можно не обращать внимания(по крайней мере у меня пустота уменьшается очень незначительно).

2022-04-27 09:24 UTC, zloyden approved these changes

2022-04-27 10:41 UTC, Alex-302 approved these changes

2022-04-27 10:41 UTC, merged