teroradio.com
AdguardTeam/AdguardFilters pull request #117830
Opened 2022-05-06 17:58 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/117754

<details><summary>Screenshot:</summary>

<img width="1792" alt="Снимок экрана 2022-05-06 в 20 58 01" src="https://user-images.githubusercontent.com/91964807/167190535-4dca937f-f7c8-4934-9141-20fefcb0b024.png">

</details><br/>

2022-05-06 18:36 UTC, Alex-302 requested changes

2022-05-06 18:36 UTC, Alex-302 commented on EnglishFilter/sections/foreign.txt
> +teroradio.com,becteroradio.com##body #head-1
It block login buttons
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/167197382-9e1bfc3a-b053-4d30-9751-a7bbf96e765c.png)

</details>

```
teroradio.com#$##leaderboard-billboard { visibility: hidden !important; height: 0 !important; }
teroradio.com###leaderboard
```

2022-05-11 09:25 UTC, zloyden approved these changes

2022-05-11 09:32 UTC, Alex-302 approved these changes

2022-05-11 09:32 UTC, merged