Changed domains
AdguardTeam/AdguardFilters pull request #117934
Opened 2022-05-07 14:09 UTC by terlancenablari

bestdizi.com -> bestdizi.net
dizison.com -> dizison.pw
hdrealfilmizleme.com --> realfilmizleme.com
elzemfilmizle.cc --> elzemfilmizle.org
filmmom.net --> filmmom.pro
fullhdfilmizleabi.com --> fullhdabifilm.com
yukfilmizle.com --> bamfilmizle.com

### Please include a summary of the change and which issue is fixed.
### If the related issue does not exist in our repository, please create it before making pool request.
### It is highly recommended to use our [Web Reporting Tool](https://kb.adguard.com/en/technical-support/reporting-tool) instead of creating an issue on GitHub directly.
### Please note, that we verify every pull request manually, so it may take time to apply it.

---

### Prerequisites
##### To avoid invalid pull requests, please check and confirm following checkboxes:

        
  - [ ] This is not an ad/bug report;
  - [ ] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
  - [ ] I have performed a self-review of my own changes;
  - [ ] My changes do not break web sites, apps and files structure.

### What problem does the pull request fix?
##### If the problem does not fall under any category that is listed here, please contact our tech support: `support@adguard.com`

  - [ ] Missed ads or ad leftovers;
  - [ ] Website or app doesn't work properly;
  - [ ] AdGuard gets detected on a website;
  - [ ] Missed analytics or tracker;
  - [ ] Social media buttons — share, like, tweet, etc;
  - [ ] Annoyances — pop-ups, cookie warnings, etc.
  
### What issue is being fixed?
##### Enter the issue address:

Example: https://github.com/AdguardTeam/AdguardFilters/issues/100000

### Add your comment and screenshots
##### If possible, a screenshot of a page or application should not be cropped too much. Otherwise, it is not always clear where the element is located.

**0.** **DO NOT** upload screenshots with sexually explicit material on GitHub directly. Instead, upload it to a third-party image hosting and post the link to it without preview (!) here. Also, mention if the link leads to NSFW content;

**1.** Add screenshots of the problem. You can drag and drop images or paste them from clipboard;

Use `<details> </details>` tag to hide screenshots under the spoiler; 

**2.** Describe the issue in detail until it is absolutely clear from the screenshot what the problem is;

You can also indicate any other information that you think the developers should know.

**Warning:** Please remove personal information before uploading screenshots!

**1.** `Write a comment here`

**2.** Screenshots

<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Terms

  - [ ] By submitting this issue, I agree that pull request does not contain private info and all conditions are met.

2022-05-08 05:32 UTC, Yuki2718 approved these changes

2022-05-09 21:37 UTC, Alex-302 requested changes

2022-05-09 21:37 UTC, Alex-302 commented on TurkishFilter/sections/specific.txt
> +://i.hizliresim.com^$domain=trdublajfilmler.com|bestdizi.*|filmizle.movie|iddaanet.com|bifilmizlesene.net|dizison.*|fulldiziizleyin.org|fanfilmizle.com|gameinsano.com|diziizleyin.org|sozlerisozu.com|
please avoid unnecessary `*` in TLDs. These sites are not even popular.

2022-05-10 10:42 UTC, Alex-302 approved these changes

2022-05-10 10:43 UTC, merged