milligazete.com.tr
AdguardTeam/AdguardFilters pull request #119528
Opened 2022-05-22 12:26 UTC by gork7777

### Prerequisites
##### To avoid invalid pull requests, please check and confirm following checkboxes:

  - [x] This is not an ad/bug report;
  - [x] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
  - [x] I have performed a self-review of my own changes;
  - [x] My changes do not break web sites, apps and files structure.

### What problem does the pull request fix?
##### If the problem does not fall under any category that is listed here, please write a comment below in corresponding section

  - [x] Missed ads or ad leftovers;
  - [ ] Website or app doesn't work properly;
  - [ ] AdGuard gets detected on a website;
  - [ ] Missed analytics or tracker;
  - [ ] Social media buttons — share, like, tweet, etc;
  - [x] Annoyances — pop-ups, cookie warnings, etc;
  - [ ] Filters maintenance.

### What issue is being fixed?
https://github.com/AdguardTeam/AdguardFilters/issues/119501

### Terms

  - [x] By submitting this issue, I agree that pull request does not contain private info and all conditions are met.

2022-05-23 18:56 UTC, Sergey-Lyapin requested changes

2022-05-23 18:56 UTC, Sergey-Lyapin commented on AnnoyancesFilter/sections/subscriptions.txt
> -ozgunkocaeli.com.tr,milligazete.com.tr##.google-news-button
This rule is still works for me

2022-05-23 18:56 UTC, Sergey-Lyapin commented on TurkishFilter/sections/specific.txt
> +||cloudflare.com/*/videojs-contrib-ads/*/videojs.ads.js$domain=ozgunkocaeli.com.tr|seskocaeli.com|yenialanya.com|milligazete.com.tr
Let's make:
||cloudflare.com/*/videojs-contrib-ads/$domain=ozgunkocaeli.com.tr|seskocaeli.com|yenialanya.com|milligazete.com.tr
And there would be no need for a separate rule for CSS.

2022-05-24 14:28 UTC, zloyden approved these changes

2022-05-24 14:32 UTC, merged