www.minhaconexao.com.br
AdguardTeam/AdguardFilters pull request #119652
Opened 2022-05-23 16:10 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/119314

<details><summary>Screenshot:</summary>

![Снимок экрана 2022-05-23 в 19 10 43](https://user-images.githubusercontent.com/91964807/169862009-c2ecadf5-3d70-4e5a-8b06-4062e21a7153.png)

</details><br/>

2022-05-24 20:23 UTC, Alex-302 approved these changes

2022-05-24 20:27 UTC, Alex-302 commented
Пропущен трекер
https://cdn.melhorplano.net/scripts/tracker/mpt.min.js
и для DNS
t.melhorplano.net

2022-05-25 07:17 UTC, zloyden requested changes

2022-05-25 07:17 UTC, zloyden commented on SpanishFilter/sections/css_extended.txt
> +minhaconexao.com.br##body > section[class]:has(> div[class] > div[class] > div[id] > [style^="height:"])
I see only div elements, so it should be
```
minhaconexao.com.br##body > section[class^="c"]:has(> div[class] > div[class] > div[id] > div[style^="height:"])
```

2022-05-25 07:19 UTC, zloyden commented on SpanishFilter/sections/css_extended.txt
> +minhaconexao.com.br##body > section[class]:has(> div[class] > div[class] > div[id] > [style^="height:"])
I've already added trackers, so just do a small fix.

2022-05-25 09:32 UTC, zloyden approved these changes

2022-05-25 09:33 UTC, merged

2022-06-06 18:04 UTC, Agronault commented
👀

2022-06-06 18:04 UTC, JordanAmaralVicente commented
👀 👎🏻

2022-06-07 11:00 UTC, Sergey-Lyapin commented
![FQM](https://user-images.githubusercontent.com/18536328/172363833-22a84781-74c8-4614-92fb-cfb0c1212ef8.gif)