brestcity.com
AdguardTeam/AdguardFilters pull request #119697
Opened 2022-05-24 10:24 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/119421

<details><summary>Screenshot:</summary>

<img width="408" alt="Снимок экрана 2022-05-24 в 13 23 40" src="https://user-images.githubusercontent.com/91964807/170010264-6cc4320a-6970-4b19-81a3-69ce2c0bd288.png">

</details><br/>

2022-05-24 19:59 UTC, Alex-302 requested changes

2022-05-24 19:59 UTC, Alex-302 commented on RussianFilter/sections/specific.txt
> +brestcity.com###page > div[style="margin-top:5px"]
Они регулярно переделывают баннеры. Старые правила нужно заменить или удалить.

2022-05-25 09:36 UTC, zloyden commented on SocialFilter/sections/specific.txt
> +brestcity.com,ganc-chas.by,podfm.ru###vk_recommended
Не вижу этот элемент. Где это нужно?

2022-05-25 10:39 UTC, jellizaveta commented on SocialFilter/sections/specific.txt
> +brestcity.com,ganc-chas.by,podfm.ru###vk_recommended
[на мобильной версии](https://brestcity.com/blog/best)

<details><summary>Screenshot:</summary>

![Снимок экрана 2022-05-25 в 13 38 25](https://user-images.githubusercontent.com/91964807/170243637-b73e37cb-2213-4d0b-9e04-b4c8fabd65c4.png)

</details><br/>

2022-05-25 10:40 UTC, zloyden approved these changes

2022-05-25 10:40 UTC, merged