www.dtac.co.th
AdguardTeam/AdguardFilters pull request #119650
Opened 2022-05-23 15:08 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/119271

<details><summary>Screenshot:</summary>

![Снимок экрана 2022-05-23 в 18 06 49](https://user-images.githubusercontent.com/91964807/169849868-074fd0c5-b824-4c2e-9675-55e9520b4003.png)

</details><br/>

2022-05-24 20:03 UTC, Alex-302 commented on AnnoyancesFilter/sections/popups.txt
> +dtac.co.th#$#.modal-open { overflow: hidden !important; }
Is `hidden ` correct?

2022-05-25 09:26 UTC, zloyden requested changes

2022-05-25 09:26 UTC, zloyden commented on AnnoyancesFilter/sections/popups.txt
> +dtac.co.th#$#.modal-open { overflow: auto !important; }
It should be like below and I don't see the popup on desktop.
```
dtac.co.th#$##gridSystemModal { display: none !important; }
dtac.co.th#$#.modal-backdrop { display: none !important; }
dtac.co.th#$#body.modal-open { overflow: auto !important; padding-right: 0 !important; }
```

2022-05-25 09:31 UTC, zloyden requested changes
Also remove this
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/170230613-b62fc788-d93d-4d22-a4e7-3f9a782dac30.png)

</details><br/>

2022-05-25 10:57 UTC, zloyden requested changes

2022-05-25 10:57 UTC, zloyden commented on MobileFilter/sections/specific_web.txt
> +dtac.co.th#$#body.modal-open { overflow: auto !important; padding-right: 0 !important; }
Wrong file.

2022-05-25 11:03 UTC, jellizaveta commented on MobileFilter/sections/specific_web.txt
> +dtac.co.th#$#body.modal-open { overflow: auto !important; padding-right: 0 !important; }
In which file should I moved this rule?

2022-05-25 11:06 UTC, zloyden approved these changes

2022-05-25 11:06 UTC, merged