www.flaschenpost.de
AdguardTeam/AdguardFilters pull request #119732
Opened 2022-05-24 15:55 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/119643

<details><summary>Screenshot:</summary>

![Снимок экрана 2022-05-24 в 18 55 29](https://user-images.githubusercontent.com/91964807/170079616-c155cd6d-1530-49d0-acf6-d69b06ac82a1.png)

</details><br/>

2022-05-24 20:15 UTC, Alex-302 requested changes

2022-05-24 20:15 UTC, Alex-302 commented on AnnoyancesFilter/sections/popups.txt
> +flaschenpost.de##.fp_modal
Same popup is used for delivery address check
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/170124197-1778fad7-964f-4e5f-a98a-11095e0f9ce1.png)

</details>

2022-05-26 14:58 UTC, zloyden reviewed
Fixed this directly.

2022-05-26 15:58 UTC, zloyden commented on AnnoyancesFilter/sections/cookies_specific.txt
> +flaschenpost.de#%#AG_onLoad(function(){var a=new MutationObserver(function(){var b=$('button.fp_button_primary:contains("Geht klar")');b&&b.click()});a.observe(document,{childList:!0,subtree:!0});set
Yep, I have also found that the clicking rule is ok here, but you need additional check.
Anyway, now it's fixed.

2022-05-26 15:58 UTC, closed without merging