yugen.to
AdguardTeam/AdguardFilters pull request #119734
Opened 2022-05-24 16:11 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/119666

<details><summary>Screenshot:</summary>

![Снимок экрана 2022-05-24 в 19 11 09](https://user-images.githubusercontent.com/91964807/170082725-e9fe58c3-c687-41d9-ad82-a34c84bee83c.png)

</details><br/>

2022-05-24 19:56 UTC, Alex-302 requested changes

2022-05-24 19:56 UTC, Alex-302 commented on EnglishFilter/sections/specific.txt
> +yugen.to##iframe[style^="width: 100%"][style*="height:"][style*="opacity:"][style*="z-index:"]
Please take a look to HTML.
If a scriptlet does not help on ios/safari, you rule can be usen for these platforms.

2022-05-25 16:44 UTC, zloyden requested changes

2022-05-26 10:03 UTC, zloyden approved these changes

2022-05-26 10:06 UTC, merged