labaq.com
AdguardTeam/AdguardFilters pull request #120369
Opened 2022-05-30 13:46 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/120321

<details><summary>Screenshot:</summary>

<img width="372" alt="Снимок экрана 2022-05-30 в 16 46 19" src="https://user-images.githubusercontent.com/91964807/171005316-e5da614d-585c-4700-b2bb-a6f8bad3633f.png">

</details><br/>

2022-05-30 16:41 UTC, Yuki2718 approved these changes

2022-05-30 16:42 UTC, Yuki2718 commented
`labaq.com##div[class] > div > div[style^="text-align:center"]` can be in Mobile filter tho (no hit on PC).

2022-05-31 07:08 UTC, zloyden requested changes

2022-05-31 07:08 UTC, zloyden commented on JapaneseFilter/sections/specific.txt
> +labaq.com##div[class] > div > div[style^="text-align:center"]
Please move this to the AdGuard Mobile filter.

2022-05-31 08:11 UTC, zloyden approved these changes

2022-05-31 08:12 UTC, merged