yaraon-blog.com
AdguardTeam/AdguardFilters pull request #120370
Opened 2022-05-30 14:05 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/120318

<details><summary>Screenshot:</summary>

![Снимок экрана 2022-05-30 в 17 04 58](https://user-images.githubusercontent.com/91964807/171008721-404256bd-0138-406d-89f3-05defdcf5607.png)

![Снимок экрана 2022-05-30 в 17 05 36](https://user-images.githubusercontent.com/91964807/171008817-d50f360c-d967-4bf7-a937-7f48e703a220.png)

</details><br/>

2022-05-30 16:22 UTC, Yuki2718 requested changes

2022-05-30 16:22 UTC, Yuki2718 commented on MobileFilter/sections/specific_web.txt
> +yaraon-blog.com##article > div.widgetarea
Okay but I prefer `###widgetarea_single_undertopimage_sp`. `###widgetarea_underpager_sp` (top page) is anyway needed as not under `article`. Note `###widgetarea_undercommentform_sp` can not be hidden.

2022-05-30 16:24 UTC, Yuki2718 requested changes

2022-05-30 16:24 UTC, Yuki2718 commented on MobileFilter/sections/specific_web.txt
> +yaraon-blog.com##article > div.widgetarea
Please change `yaraon-blog.com##article > div.widgetarea` to `yaraon-blog.com###widgetarea_single_undertopimage_sp` and add `yaraon-blog.com###widgetarea_underpager_sp`.

2022-05-30 16:27 UTC, Yuki2718 commented
Optional: `yaraon-blog.com##.searcharea + p + center`

2022-05-30 16:31 UTC, Yuki2718 requested changes
Also add `||js.mulan.cloud^` to Japanese adserver for DNS (caught by regex in Base).

2022-05-30 16:33 UTC, Yuki2718 commented
Please also check on PC, there are some missed ads on left side.

2022-05-31 08:36 UTC, zloyden approved these changes

2022-05-31 08:38 UTC, zloyden approved these changes

2022-05-31 08:38 UTC, merged