www.tecnoandroid.it
AdguardTeam/AdguardFilters pull request #120588
Opened 2022-06-01 18:35 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/120200

<details><summary>Screenshot:</summary>

![Снимок экрана 2022-06-01 в 21 35 09](https://user-images.githubusercontent.com/91964807/171477628-913c3312-ada9-4008-8d6f-1e57223931b5.png)

</details><br/>

2022-06-01 20:03 UTC, Alex-302 requested changes

2022-06-01 20:03 UTC, Alex-302 commented on EnglishFilter/sections/general_extensions.txt
> +tecnoandroid.it#$#body.td-background-link { cursor: auto !important; }
Italian - to foreign.txt
the same for 
```
||tecnoandroid.it/wp-content/uploads/2022/04/vivo
||assets.evolutionadv.it/tecnoandroid_it/tecnoandroid_it.new.js
```

2022-06-02 07:12 UTC, zloyden requested changes

2022-06-02 07:12 UTC, zloyden commented on EnglishFilter/sections/general_extensions.txt
> +tecnoandroid.it#$#body.td-background-link { cursor: auto !important; }
Yep, this is an Italian website

2022-06-02 08:58 UTC, zloyden requested changes

2022-06-02 08:58 UTC, zloyden commented on EnglishFilter/sections/specific.txt
> +||tecnoandroid.it/wp-content/uploads/2022/04/vivo
`2022/04/` is not necessary

2022-06-02 08:58 UTC, zloyden commented on EnglishFilter/sections/specific.txt
> +||assets.evolutionadv.it/tecnoandroid_it/tecnoandroid_it.new.js
Where do you need this?
Also move these rules to the `Italian` section

2022-06-02 09:12 UTC, zloyden approved these changes

2022-06-02 09:12 UTC, merged