oceans.tokyo.jp
AdguardTeam/AdguardFilters pull request #121047
Opened 2022-06-06 15:45 UTC by SKEIDs

Fix #120986

2022-06-06 16:12 UTC, Yuki2718 requested changes

2022-06-06 16:17 UTC, SKEIDs commented on JapaneseFilter/sections/specific.txt
> +oceans.tokyo.jp,cinema.ne.jp,jma.go.jp##.ad-pc
ok, I edited rule.

2022-06-06 16:20 UTC, Yuki2718 commented
Each of suggested rule has existing one e.g. `zaikai.jp,driver-web.jp,rollingstonejapan.com##.addHead`

2022-06-06 16:23 UTC, SKEIDs commented
> Each of suggested rule has existing one e.g. `zaikai.jp,driver-web.jp,rollingstonejapan.com##.addHead`

oh sorry, done

2022-06-06 16:23 UTC, Yuki2718 approved these changes

2022-06-07 07:10 UTC, zloyden approved these changes

2022-06-07 07:11 UTC, merged