withonline.jp
AdguardTeam/AdguardFilters pull request #121032
Opened 2022-06-06 12:43 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/120750

<details><summary>Screenshot:</summary>

<img width="375" alt="Снимок экрана 2022-06-06 в 15 42 59" src="https://user-images.githubusercontent.com/91964807/172162757-fb9b03ad-04c9-4fb1-b327-5a3c26049cf6.png">

</details><br/>

2022-06-06 16:56 UTC, Yuki2718 reviewed
Probably we should replace
```
withonline.jp##div[id$="_inread"]
withonline.jp##div[id$="_InArticle-1"]
```
with `withonline.jp##div[id^="TW_"]`. Not sure if the extended rule is still needed then (on PC covered by `withonline.jp##div[style="max-width:970px;min-height:90px;text-align:center;margin:0 auto;"]`).

2022-06-06 17:19 UTC, Alex-302 requested changes

2022-06-06 17:19 UTC, Alex-302 commented on JapaneseFilter/sections/css_extended.txt
> +withonline.jp#?##TW_PC_Billboard:upward(1)
Можно обычным правилом, т.к. 970*90 - часто используемый размер баннеров
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/172212030-4f479f87-8c6b-4b99-b854-4ec3687d11a9.png)

</details>

2022-06-06 17:51 UTC, Yuki2718 commented on JapaneseFilter/sections/css_extended.txt
> +withonline.jp#?##TW_PC_Billboard:upward(1)
We already have `withonline.jp##div[style="max-width:970px;min-height:90px;text-align:center;margin:0 auto;"]`.

2022-06-07 08:42 UTC, zloyden requested changes

2022-06-07 08:42 UTC, zloyden commented on JapaneseFilter/sections/css_extended.txt
> +withonline.jp#?##TW_PC_Billboard:upward(1)
Actually, we do not need the rule as @Yuki2718 said.

2022-06-07 08:47 UTC, zloyden reviewed
> Probably we should replace

According to the their code, it only affects the leftovers. I have changed the rules.

2022-06-07 10:43 UTC, zloyden commented on SocialFilter/sections/specific.txt
> +withonline.jp##.pattern_other > div.other-box:has(> div.heading-area > p:contains(SHARE))
Check this
```
withonline.jp##.pattern_other > div.other-box:has(> ul[class^="share-"])
```

2022-06-07 13:54 UTC, zloyden requested changes

2022-06-07 13:54 UTC, zloyden commented on SocialFilter/sections/specific.txt
> +withonline.jp##.pattern_other > div.other-box:has(> ul[class^="share-"])
```
withonline.jp#?#.pattern_other > div.other-box:has(> ul[class^="share-"])
```
Should be in `css_extended`

2022-06-07 14:58 UTC, closed without merging