news.hoken-mammoth.jp
AdguardTeam/AdguardFilters pull request #121043
Opened 2022-06-06 15:33 UTC by SKEIDs

Fix  #120968

2022-06-06 16:17 UTC, Yuki2718 requested changes
Add `news.hoken-mammoth.jp##.sideAD` to JPF - they look like as if self-promo but actually are ads.

2022-06-06 16:19 UTC, SKEIDs commented
done

2022-06-06 16:21 UTC, Yuki2718 approved these changes

2022-06-07 07:12 UTC, zloyden approved these changes

2022-06-07 07:13 UTC, merged