web.goout.jp
AdguardTeam/AdguardFilters pull request #121049
Opened 2022-06-06 15:58 UTC by SKEIDs

Fix #120995

2022-06-06 16:07 UTC, Yuki2718 requested changes

2022-06-06 16:07 UTC, Yuki2718 commented on MobileFilter/sections/specific_web.txt
> +web.goout.jp##.bx-ad
This hides self-promo too. Maybe
```
web.goout.jp###secondary > div.bx-ad:first-child
web.goout.jp##.bx-ad.mb-10
web.goout.jp##.bx-ad.my-10
```

2022-06-06 16:11 UTC, SKEIDs commented on MobileFilter/sections/specific_web.txt
> +web.goout.jp##.bx-ad
I will fix it.

2022-06-06 16:14 UTC, Yuki2718 approved these changes

2022-06-07 07:08 UTC, zloyden approved these changes

2022-06-07 07:08 UTC, merged