javpro.cc
AdguardTeam/AdguardFilters pull request #121533
Opened 2022-06-11 13:40 UTC by SKEIDs

Fix #121389

2022-06-11 14:52 UTC, Yuki2718 requested changes
Use an exisiting rule `##div[style^="height: 250px;overflow: hidden;"]`

2022-06-11 15:03 UTC, SKEIDs commented
> Use an exisiting rule `##div[style^="height: 250px;overflow: hidden;"]`

I didn't know some can be omitt. I will fix it.

2022-06-11 15:24 UTC, Yuki2718 approved these changes

2022-06-13 17:15 UTC, Alex-302 approved these changes

2022-06-13 17:15 UTC, merged