update pull_request_template
AdguardTeam/AdguardFilters pull request #121782
Opened 2022-06-14 13:10 UTC by kaprielov

Added description of the filter-pr-checker steps

2022-06-14 13:25 UTC, Alex-302 commented
The most of pull requests are created for existing issues. We ask to link them.
If no such issue - user can send report from AdGuard directly and attach the link.

2022-06-14 13:42 UTC, maximtop requested changes
Let's wait until @ameshkov approves the action. Also, we should connect action in this PR as well.

2022-07-08 13:56 UTC, ameshkov approved these changes

2022-07-08 13:57 UTC, ameshkov requested changes
Well, according to the last task, we shouldn't force any special rules for the PR text

2022-07-14 08:51 UTC, closed without merging