telegraf.plus
AdguardTeam/AdguardFilters pull request #123214
Opened 2022-07-01 14:53 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/123201

<details><summary>Screenshot:</summary>

<img width="808" alt="Снимок экрана 2022-07-01 в 17 53 06" src="https://user-images.githubusercontent.com/91964807/176918434-ac723a56-c591-4f2b-98aa-d38fbc8babd2.png">

</details><br/>

2022-07-01 14:55 UTC, zloyden requested changes

2022-07-01 14:55 UTC, zloyden commented on RussianFilter/sections/adservers.txt
> +||pgusgyzdfpj.ru^
`4mlhn1ocg4.com` это ж `ads.bid`. Добавь домен к соответствующему правилу.

2022-07-01 14:59 UTC, zloyden commented on RussianFilter/sections/adservers.txt
> +||pgusgyzdfpj.ru^
`4mlhn1ocg4.com` есть реферер, добавь модификатор `$third-party`.
`pgusgyzdfpj.ru` у себя не вижу.

2022-07-01 15:15 UTC, Alex-302 commented on RussianFilter/sections/adservers.txt
> +||pgusgyzdfpj.ru^
> есть реферер

но нет контента при прямом посещении) Можно не добавлять, некоторые, в т.ч. изилист, давно так делают.

2022-07-01 15:26 UTC, zloyden commented on RussianFilter/sections/adservers.txt
> +||pgusgyzdfpj.ru^
Хорошо, @jellizaveta добавь только домен к выше правилу.

2022-07-04 11:47 UTC, Alex-302 approved these changes

2022-07-04 11:47 UTC, merged