biz-journal.jp
AdguardTeam/AdguardFilters pull request #124358
Opened 2022-07-15 12:47 UTC by SKEIDs

## Prerequisites

### To avoid invalid pull requests, please check and confirm following terms

- [x] This is not an ad/bug report;
- [x] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
- [x] I have performed a self-review of my own changes;
- [x] My changes do not break web sites, apps and files structure.

## What problem does the pull request fix?

### If the problem does not fall under any category that is listed here, please write a comment below in corresponding section

- [x] Missed ads or ad leftovers;
- [ ] Website or app doesn't work properly;
- [ ] AdGuard gets detected on a website;
- [ ] Missed analytics or tracker;
- [ ] Social media buttons — share, like, tweet, etc;
- [ ] Annoyances — pop-ups, cookie warnings, etc;
- [x] Filters maintenance.

## What issue is being fixed?

 https://biz-journal.jp/2022/07/post_307038.html

### Add your comment and screenshots

 <details><summary>screenshot</summary>

![](https://i.ibb.co/FswJ0cV/image.png)
</details><br/>

### Terms

- [x] By submitting this issue, I agree that pull request does not contain private info and all conditions are met

2022-07-17 16:33 UTC, Yuki2718 requested changes
```
biz-journal.jp##.rankpr
###aside > #publicity > a[target="_blank"] > img
```
These are obsolete, can be removed.

2022-07-17 16:35 UTC, Yuki2718 commented
Also as we have `##div[id^="ad"]`, the domain should be removed from `###ad1` and `###ad2`.

2022-07-18 02:22 UTC, SKEIDs commented
I see. done

2022-07-18 03:37 UTC, Yuki2718 approved these changes

2022-07-19 07:02 UTC, zloyden approved these changes

2022-07-19 07:03 UTC, merged