www.mapion.co.jp
AdguardTeam/AdguardFilters pull request #124363
Opened 2022-07-15 13:43 UTC by SKEIDs

Fix #124332

2022-07-17 16:24 UTC, Yuki2718 requested changes

2022-07-17 16:24 UTC, Yuki2718 commented on AnnoyancesFilter/sections/mobile-app.txt
> +mapion.co.jp##.btn-ptn2[href^="https://play.google.com"]
`mapion.co.jp##.btn-ptn2` is enough.

2022-07-18 02:25 UTC, SKEIDs commented on AnnoyancesFilter/sections/mobile-app.txt
> +mapion.co.jp##.btn-ptn2[href^="https://play.google.com"]
ok,fixed.

2022-07-18 03:36 UTC, Yuki2718 approved these changes

2022-07-19 07:02 UTC, zloyden approved these changes

2022-07-19 07:05 UTC, zloyden commented
We have new files in the Annoyances filter, fixed directly.

2022-07-19 07:05 UTC, closed without merging