alba.co.jp (social and others)
AdguardTeam/AdguardFilters pull request #124692
Opened 2022-07-18 08:15 UTC by SKEIDs

https://github.com/AdguardTeam/AdguardFilters/issues/124683 fixed only Screenshot 1

```
! https://www.alba.co.jp/sp/tour/news/article/no=185162
! Mobile
! Ad
alba.co.jp##.topbnrArea
! Social
alba.co.jp##.social-button
! https://www.alba.co.jp/tour/news/article/no=185162
! PC
! Ad
alba.co.jp###ad_rectangle03_04
```

<details><summary>screenshot</summary>

![](https://i.ibb.co/q9djBSL/3.png)

![](https://i.ibb.co/L6NLYvL/2.png)

![](https://i.ibb.co/8PPnsgg/1.png)
</details><br/>

2022-07-18 14:36 UTC, Yuki2718 requested changes

2022-07-19 12:32 UTC, SKEIDs commented on JapaneseFilter/sections/specific.txt
> +alba.co.jp###ad_rectangle03_04
ok,fixed

2022-07-19 14:05 UTC, Yuki2718 requested changes
There are also popIn ad leftover if Annoyances filter is turned off. Add the domain to `#?#li > ._popIn_recommend_article_ad_reserved:upward(1)` in JPF.

2022-07-19 14:23 UTC, Yuki2718 requested changes
No I mean add to an existing rule.

2022-07-19 14:28 UTC, SKEIDs commented
> No I mean add to an existing rule.
 I'm sorry. Fixed

2022-07-19 14:30 UTC, Yuki2718 approved these changes

2022-07-20 06:20 UTC, zloyden approved these changes

2022-07-20 06:20 UTC, merged