www.tumblr.com
AdguardTeam/AdguardFilters pull request #125111
Opened 2022-07-22 12:33 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/124899

<details><summary>Screenshot:</summary>

<img width="894" alt="Снимок экрана 2022-07-22 в 15 33 10" src="https://user-images.githubusercontent.com/91964807/180439958-14135774-b5a0-42af-a919-019b34d71c7a.png">

</details><br/>

2022-07-22 13:49 UTC, Alex-302 commented on AnnoyancesFilter/Cookies/sections/cookies_specific.txt
> +tumblr.com#%#AG_onLoad(function(){var b=new MutationObserver(function(){var a=document.querySelector('.is-primary');a&&a.click()});b.observe(document,{childList:!0,subtree:!0});setTimeout(function(){
селектор может поточнее? Вдруг такая же кнопка где-нибудь ещё используется.

2022-07-22 14:07 UTC, zloyden requested changes

2022-07-22 14:07 UTC, zloyden commented on AnnoyancesFilter/Cookies/sections/cookies_specific.txt
> +tumblr.com#%#AG_onLoad(function(){var b=new MutationObserver(function(){var a=document.querySelector('.is-primary');a&&a.click()});b.observe(document,{childList:!0,subtree:!0});setTimeout(function(){
С этим лучше `.cmp__dialog-footer-buttons > button.components-button.is-primary` и еще добавил б проверку куки.
```
tumblr.com#%#AG_onLoad(function(){if(-1===document.cookie.indexOf('euconsent-v2')){var b=new MutationObserver(function(){var a=document.querySelector('.cmp__dialog-footer-buttons > button.components-button.is-primary');a&&a.click()});b.observe(document,{childList:!0,subtree:!0});setTimeout(function(){b.disconnect()},1E4)}});
```

2022-07-25 06:31 UTC, zloyden approved these changes

2022-07-25 06:31 UTC, merged