www.aconvert.com
AdguardTeam/AdguardFilters pull request #125185
Opened 2022-07-23 14:09 UTC by SKEIDs

## Prerequisites

### To avoid invalid pull requests, please check and confirm following terms

- [x] This is not an ad/bug report;
- [x] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
- [x] I have performed a self-review of my own changes;
- [x] My changes do not break web sites, apps and files structure.

## What problem does the pull request fix?

### If the problem does not fall under any category that is listed here, please write a comment below in corresponding section

- [x] Missed ads or ad leftovers;
- [ ] Website or app doesn't work properly;
- [ ] AdGuard gets detected on a website;
- [ ] Missed analytics or tracker;
- [ ] Social media buttons — share, like, tweet, etc;
- [ ] Annoyances — pop-ups, cookie warnings, etc;
- [ ] Filters maintenance.

## What issue is being fixed?

### Enter the issue address

 Fix #125092 

### Add your comment and screenshots

 <details><summary>screenshot</summary>

![](https://i.ibb.co/vsd2SW8/image.png)

</details><br/>

### Terms

- [x] By submitting this issue, I agree that pull request does not contain private info and all conditions are met

2022-07-24 11:52 UTC, Yuki2718 requested changes

2022-07-24 11:52 UTC, Yuki2718 commented on EnglishFilter/sections/specific.txt
> +aconvert.com##.bluebg
Maybe a bit risky, `##.content > div.bluebg`

2022-07-24 12:45 UTC, SKEIDs commented on EnglishFilter/sections/specific.txt
> +aconvert.com##.bluebg
I will fix. ty.

2022-07-24 12:59 UTC, Yuki2718 approved these changes

2022-07-25 07:05 UTC, zloyden approved these changes

2022-07-25 07:05 UTC, merged