www.yakult-swallows.co.jp
AdguardTeam/AdguardFilters pull request #125533
Opened 2022-07-27 11:48 UTC by SKEIDs

## Prerequisites

### To avoid invalid pull requests, please check and confirm following terms

- [x] This is not an ad/bug report;
- [x] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
- [x] I have performed a self-review of my own changes;
- [x] My changes do not break web sites, apps and files structure.

## What problem does the pull request fix?

### If the problem does not fall under any category that is listed here, please write a comment below in corresponding section

- [ ] Missed ads or ad leftovers;
- [ ] Website or app doesn't work properly;
- [ ] AdGuard gets detected on a website;
- [ ] Missed analytics or tracker;
- [x] Social media buttons — share, like, tweet, etc;
- [ ] Annoyances — pop-ups, cookie warnings, etc;
- [ ] Filters maintenance.

## What issue is being fixed?

### Enter the issue address

Fix #125517 

### Add your comment and screenshots

<details><summary>screenshot</summary>

![](https://i.postimg.cc/FKbbt6xF/image.png)

</details><br/>

### Terms

- [x] By submitting this issue, I agree that pull request does not contain private info and all conditions are met

2022-07-27 12:57 UTC, Yuki2718 requested changes

2022-07-27 12:57 UTC, Yuki2718 commented on SocialFilter/sections/specific.txt
> +yakult-swallows.co.jp##.post-info > ul.socials:upward(1)
#?# and css_extended

2022-07-28 08:26 UTC, SKEIDs commented on SocialFilter/sections/specific.txt
> +yakult-swallows.co.jp##.post-info > ul.socials:upward(1)
fixed

2022-07-28 11:50 UTC, Yuki2718 approved these changes

2022-07-28 12:15 UTC, zloyden approved these changes

2022-07-28 12:16 UTC, merged