koushoku.org
AdguardTeam/AdguardFilters pull request #127625
Opened 2022-08-19 17:53 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/127617

[screen](https://imgur.com/zGkO1y0)

2022-08-22 10:17 UTC, Alex-302 commented on EnglishFilter/sections/whitelist.txt
> +koushoku.org#@#.exo-native-widget
С программой и расширением всё это нужно? (с ними ещё рекламный редирект на десктопе)

2022-08-22 10:46 UTC, Alex-302 requested changes

2022-08-22 10:46 UTC, Alex-302 commented on EnglishFilter/sections/whitelist.txt
> +@@||a.realsrv.com/popunder1000.js$domain=koushoku.org
Это вроде не нужно, без него картинки загружаются.

2022-08-22 10:46 UTC, Alex-302 commented on EnglishFilter/sections/whitelist.txt
> +@@||syndication.realsrv.com/$domain=koushoku.org
лучше ограничить по расширению.
Ещё можно добавить `koushoku.org#%#//scriptlet('prevent-xhr', '/cimp.php')`


Для рекламных картинок:
`||s3t3d2y8.afcdn.net^`

И редирект при переходе с главной.

2022-08-23 07:06 UTC, zloyden requested changes

2022-08-23 07:06 UTC, zloyden commented on EnglishFilter/sections/general_extensions.txt
> +!#if (adguard_ext_firefox || adguard_ext_opera || adguard_ext_edge || adguard_ext_safari)
Для одного правила директива не нужна - поменяй на `!+ PLATFORM`.

2022-08-23 11:56 UTC, zloyden approved these changes

2022-08-23 17:50 UTC, Alex-302 approved these changes

2022-08-23 17:57 UTC, jellizaveta commented
Closed via https://github.com/AdguardTeam/AdguardFilters/commit/8d42fe0836754ef8fb31607b652c7bf4e24e680f

2022-08-23 17:57 UTC, closed without merging