baomoi.com
AdguardTeam/AdguardFilters pull request #129142
Opened 2022-09-07 17:13 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/128906

2022-09-07 18:39 UTC, trmdi commented
It seems to work fine. Thank you.

2022-09-08 07:07 UTC, zloyden requested changes

2022-09-08 07:07 UTC, zloyden commented on EnglishFilter/sections/foreign.txt
> +||w-api.baomoi.com/api/v1/slave/ad/*
Just `||w-api.baomoi.com/api/*/ad/`

2022-09-08 07:07 UTC, zloyden commented on SpywareFilter/sections/specific.txt
> +||w-api.baomoi.com/api/v1/log/post
Here is the same `||w-api.baomoi.com/api/*/log/`

2022-09-08 10:09 UTC, zloyden approved these changes

2022-09-08 10:10 UTC, merged