blog.twitter.com
AdguardTeam/AdguardFilters pull request #129291
Opened 2022-09-09 13:03 UTC by SKEIDs

## Prerequisites

### To avoid invalid pull requests, please check and confirm following terms

- [x] This is not an ad/bug report;
- [x] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
- [x] I have performed a self-review of my own changes;
- [x] My changes do not break web sites, apps and files structure.

## What problem does the pull request fix?

### If the problem does not fall under any category that is listed here, please write a comment below in corresponding section

- [ ] Missed ads or ad leftovers;
- [ ] Website or app doesn't work properly;
- [ ] AdGuard gets detected on a website;
- [ ] Missed analytics or tracker;
- [x] Social media buttons — share, like, tweet, etc;
- [ ] Annoyances — pop-ups, cookie warnings, etc;
- [ ] Filters maintenance.

## What issue is being fixed?

### Enter the issue address

https://blog.twitter.com/ja_jp
 https://blog.twitter.com/ja_jp/topics/company/2022/world_suicide_prevention_day_event

### Add your comment and screenshots

#### If possible, a screenshot of a page or application should not be cropped too much. Otherwise, it is not always clear where the element is located

<details><summary>screenshot</summary>

![](https://i.postimg.cc/m2zr91wV/image.png)

</details><br/>

### Terms

- [x] By submitting this issue, I agree that pull request does not contain private info and all conditions are met

2022-09-10 16:48 UTC, Yuki2718 requested changes

2022-09-10 16:48 UTC, Yuki2718 commented on SocialFilter/sections/css_extended.txt
> +blog.twitter.com#?#.post > .post__share--icons:upward(1)
specify tag on child i.e. `#?#.post > div.post__share--icons:upward(1)`.

2022-09-10 16:48 UTC, Yuki2718 commented on SocialFilter/sections/specific.txt
> +blog.twitter.com##a[class^="sharing-popup-"]
`##.bl03-featured-masthead__share--icons` or `##div[class$="featured-masthead__share--icons"]`

2022-09-11 17:43 UTC, SKEIDs commented on SocialFilter/sections/css_extended.txt
> +blog.twitter.com#?#.post > .post__share--icons:upward(1)
ok

2022-09-11 17:44 UTC, SKEIDs commented on SocialFilter/sections/specific.txt
> +blog.twitter.com##a[class^="sharing-popup-"]
ok

2022-09-11 18:05 UTC, Yuki2718 approved these changes

2022-09-13 07:04 UTC, zloyden approved these changes

2022-09-13 07:04 UTC, merged