lightship.dev
AdguardTeam/AdguardFilters pull request #129377
Opened 2022-09-10 13:25 UTC by SKEIDs

# Creating the pull request

> Please include a summary of the change and which issue is fixed\
> If the related issue does not exist in our repository, please create it before making pull request\
> It is highly recommended to use our [Web Reporting Tool](https://kb.adguard.com/en/technical-support/reporting-tool) instead of creating an issue on GitHub directly\
> Please note, that we verify every pull request manually, so it may take time to apply it

## Prerequisites

### To avoid invalid pull requests, please check and confirm following terms

- [x] This is not an ad/bug report;
- [x] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
- [x] I have performed a self-review of my own changes;
- [x] My changes do not break web sites, apps and files structure.

## What problem does the pull request fix?

### If the problem does not fall under any category that is listed here, please write a comment below in corresponding section

- [ ] Missed ads or ad leftovers;
- [ ] Website or app doesn't work properly;
- [ ] AdGuard gets detected on a website;
- [ ] Missed analytics or tracker;
- [x] Social media buttons — share, like, tweet, etc;
- [ ] Annoyances — pop-ups, cookie warnings, etc;
- [ ] Filters maintenance.

## What issue is being fixed?

### Enter the issue address

 https://lightship.dev/blog/announcing-lightship-vps-world-tour/

### Add your comment and screenshots

<details><summary>screenshot</summary>

![](https://i.ibb.co/CbzJcDZ/image.png)

</details><br/>

### Terms

- [x] By submitting this issue, I agree that pull request does not contain private info and all conditions are met

2022-09-10 16:58 UTC, Yuki2718 requested changes

2022-09-10 16:58 UTC, Yuki2718 commented on SocialFilter/sections/specific.txt
> +lightship.dev##div[class$="layout__sidebar__share"]
`##.LayoutBlog__layout__sidebar__share`

2022-09-11 17:43 UTC, SKEIDs commented on SocialFilter/sections/specific.txt
> +lightship.dev##div[class$="layout__sidebar__share"]
ok

2022-09-11 18:04 UTC, Yuki2718 approved these changes

2022-09-12 14:17 UTC, Sergey-Lyapin approved these changes

2022-09-12 14:17 UTC, merged