seiga.nicovideo.jp
AdguardTeam/AdguardFilters pull request #130829
Opened 2022-09-27 13:07 UTC by SKEIDs

## Prerequisites

### To avoid invalid pull requests, please check and confirm following terms

- [x] This is not an ad/bug report;
- [x] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
- [x] I have performed a self-review of my own changes;
- [x] My changes do not break web sites, apps and files structure.

## What problem does the pull request fix?

### If the problem does not fall under any category that is listed here, please write a comment below in corresponding section

- [ ] Missed ads or ad leftovers;
- [ ] Website or app doesn't work properly;
- [ ] AdGuard gets detected on a website;
- [ ] Missed analytics or tracker;
- [ ] Social media buttons — share, like, tweet, etc;
- [x] Annoyances — pop-ups, cookie warnings, etc;
- [ ] Filters maintenance.

## What issue is being fixed?

### Enter the issue address

 https://seiga.nicovideo.jp/watch/mg657726

### Add your comment and screenshots

<details><summary>screenshot</summary>

![](https://i.ibb.co/3hwr584/image.png)

</details><br/>

### Terms

- [x] By submitting this issue, I agree that pull request does not contain private info and all conditions are met

2022-09-29 11:12 UTC, Sergey-Lyapin requested changes

2022-09-29 11:12 UTC, Sergey-Lyapin commented on AnnoyancesFilter/MobileApp/sections/mobile-app_specific.txt
> +seiga.nicovideo.jp#?#div[style^="margin-bottom: 20px;"] > a[href^="https://play.google.com/"]:upward(1)
I suppose:
`seiga.nicovideo.jp##.related_info_main > div[style*="lohas.nicoseiga.jp/material/"]`

2022-09-29 15:39 UTC, SKEIDs commented on AnnoyancesFilter/MobileApp/sections/mobile-app_specific.txt
> +seiga.nicovideo.jp#?#div[style^="margin-bottom: 20px;"] > a[href^="https://play.google.com/"]:upward(1)
I agree

2022-09-30 08:00 UTC, Alex-302 approved these changes

2022-09-30 15:04 UTC, merged