jp.ext.hp.com
AdguardTeam/AdguardFilters pull request #130830
Opened 2022-09-27 13:17 UTC by SKEIDs

## Prerequisites

### To avoid invalid pull requests, please check and confirm following terms

- [x] This is not an ad/bug report;
- [x] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
- [x] I have performed a self-review of my own changes;
- [x] My changes do not break web sites, apps and files structure.

## What problem does the pull request fix?

### If the problem does not fall under any category that is listed here, please write a comment below in corresponding section

- [ ] Missed ads or ad leftovers;
- [ ] Website or app doesn't work properly;
- [ ] AdGuard gets detected on a website;
- [ ] Missed analytics or tracker;
- [x] Social media buttons — share, like, tweet, etc;
- [x] Annoyances — pop-ups, cookie warnings, etc;
- [ ] Filters maintenance.

## What issue is being fixed?

### Enter the issue address

 https://jp.ext.hp.com/campaign/personal/others/gamingpc_choice/

### Add your comment and screenshots

<details><summary>screenshot</summary>

![](https://i.ibb.co/9vJx8Qp/image.png)
![](https://i.ibb.co/1L7kKJM/image.png)

</details><br/>

### Terms

- [x] By submitting this issue, I agree that pull request does not contain private info and all conditions are met

2022-09-29 08:21 UTC, Alex-302 requested changes

2022-09-29 08:21 UTC, Alex-302 commented on AnnoyancesFilter/Other/sections/self-promo.txt
> +||jp.ext.hp.com/content/dam/*/bnr980x80_buy_with_epos_card.png
Not annoying.

2022-09-29 15:36 UTC, SKEIDs commented on AnnoyancesFilter/Other/sections/self-promo.txt
> +||jp.ext.hp.com/content/dam/*/bnr980x80_buy_with_epos_card.png
ok

2022-09-30 07:41 UTC, Alex-302 approved these changes

2022-09-30 07:41 UTC, merged