sbapp.net
AdguardTeam/AdguardFilters pull request #134193
Opened 2022-11-05 13:13 UTC by SKEIDs

## Prerequisites

### To avoid invalid pull requests, please check and confirm following terms

- [x] This is not an ad/bug report;
- [x] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
- [x] I have performed a self-review of my own changes;
- [x] My changes do not break web sites, apps and files structure.

## What problem does the pull request fix?

### If the problem does not fall under any category that is listed here, please write a comment below in corresponding section

- [x] Missed ads or ad leftovers;
- [ ] Website or app doesn't work properly;
- [ ] AdGuard gets detected on a website;
- [ ] Missed analytics or tracker;
- [ ] Social media buttons — share, like, tweet, etc;
- [ ] Annoyances — pop-ups, cookie warnings, etc;
- [ ] Filters maintenance.

## What issue is being fixed?

### Enter the issue address

Fix #134091 

### Add your comment and screenshots

<details><summary>screenshot - PC</summary>

![](https://i.ibb.co/QYPChzd/PPPC.png)

</details><br/>

<details><summary>screenshot - mobile</summary>

![](https://i.ibb.co/FYgyNMG/m1.png)
![](https://i.ibb.co/8NkZRN1/m2.png)

</details><br/>

### Terms

- [x] By submitting this issue, I agree that pull request does not contain private info and all conditions are met

2022-11-05 16:23 UTC, Yuki2718 requested changes
In this case better
```
sbapp.net###text-50
sbapp.net##div[class^="gads-space"]
```
`###text-??` and `###custom_html-?` occasionally (not too often) cause breakage in the long run by site's redesign.

2022-11-06 14:24 UTC, SKEIDs commented
> ###text-?? and ###custom_html-? occasionally (not too often) cause breakage in the long run by site's redesign.

I agree.

2022-11-06 14:28 UTC, Yuki2718 approved these changes

2022-11-07 12:41 UTC, Alex-302 approved these changes

2022-11-07 12:41 UTC, merged