manwa.me
AdguardTeam/AdguardFilters pull request #138702
Opened 2022-12-29 16:51 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/138700

2022-12-29 17:19 UTC, Yuki2718 requested changes
Not enough, needing
```
||manwa.me/static/custom/files/300X250.gif$image,redirect=1x1-transparent.gif,important
@@||manwa.me/static/custom/files/300X250.gif
```

2022-12-29 17:26 UTC, Yuki2718 commented
How about a possible mitigation for CB (iOS free user) `manwa.me##.ad-area > a[target="_blank"]` ?

2022-12-29 21:34 UTC, Yuki2718 approved these changes

2022-12-30 06:15 UTC, zloyden commented on ChineseFilter/sections/antiadblock.txt
> +manwa.me#$#.ad-area { position: absolute!important; left: -3000px!important; }
Don't forget to add a space in values.

2022-12-30 06:16 UTC, zloyden approved these changes

2022-12-30 06:16 UTC, merged