manage.kmail-lists.com
AdguardTeam/AdguardFilters pull request #140635
Opened 2023-01-20 16:59 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/140633

2023-01-20 19:36 UTC, Alex-302 requested changes

2023-01-20 19:36 UTC, Alex-302 commented on SpywareFilter/sections/tracking_servers.txt
> +||a.klaviyo.com^$third-party
Я бы удалил это правило и исключил из DNS фильтра (и проверить потом, не появилось ли аналогичное).
Трекинговые домены и скрипт (в фильтр не добавлял):
`||telemetrics.klaviyo.com^`
`||static-tracking.klaviyo.com^`
`||fast.a.klaviyo.com/media/js/analytics/klaviyo_analytics.js`
Их дока
https://help.klaviyo.com/hc/en-us/articles/360034666712-Understanding-cookies-in-Klaviyo

2023-01-23 11:42 UTC, jellizaveta commented on SpywareFilter/sections/tracking_servers.txt
> +||a.klaviyo.com^$third-party
```
||telemetrics.klaviyo.com^
||static-tracking.klaviyo.com^
```
есть в фильтре

2023-01-23 13:17 UTC, Alex-302 approved these changes

2023-01-23 13:17 UTC, merged

2023-01-23 14:10 UTC, Alex-302 commented on SpywareFilter/sections/tracking_servers.txt
> +||a.klaviyo.com^$third-party
А с фильтром DNS что?