xeimg.yt
AdguardTeam/AdguardFilters pull request #141776
Opened 2023-02-02 12:54 UTC by piquark6046

## Prerequisites

### To avoid invalid pull requests, please check and confirm following terms

- [X] This is not an ad/bug report;
- [X] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
- [X] I have performed a self-review of my own changes;
- [X] My changes do not break web sites, apps and files structure.

## What problem does the pull request fix?

### If the problem does not fall under any category that is listed here, please write a comment below in corresponding section

- [ ] Missed ads or ad leftovers;
- [ ] Website or app doesn't work properly;
- [ ] AdGuard gets detected on a website;
- [ ] Missed analytics or tracker;
- [ ] Social media buttons — share, like, tweet, etc;
- [ ] Annoyances — pop-ups, cookie warnings, etc;
- [X] Filters maintenance.

## What issue is being fixed?

### Enter the issue address

 - https://github.com/AdguardTeam/AdguardFilters/issues/139027

### Add your comment and screenshots

 - The website is dead.

### Terms

- [X] By submitting this issue, I agree that pull request does not contain private info and all conditions are met

2023-02-02 13:42 UTC, Alex-302 requested changes

2023-02-02 13:42 UTC, Alex-302 commented on BaseFilter/sections/specific.txt
>  url.namaidani.com,coinsparty.com,bitlinks.pw,passgen.icu,xeimg.yt##iframe#frame
One missed
```suggestion
url.namaidani.com,coinsparty.com,bitlinks.pw,passgen.icu##iframe#frame
```

2023-02-02 13:51 UTC, piquark6046 commented on BaseFilter/sections/specific.txt
>  url.namaidani.com,coinsparty.com,bitlinks.pw,passgen.icu,xeimg.yt##iframe#frame
Removed.

2023-02-03 16:21 UTC, Alex-302 approved these changes

2023-02-03 16:21 UTC, merged