Fix #148493 anizle.com
AdguardTeam/AdguardFilters pull request #148630
Opened 2023-04-17 20:10 UTC by gork7777

## Prerequisites

### To avoid invalid pull requests, please check and confirm following terms

- [x] This is not an ad/bug report;
- [x] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
- [x] I have performed a self-review of my own changes;
- [x] My changes do not break web sites, apps and files structure.

## What problem does the pull request fix?

### If the problem does not fall under any category that is listed here, please write a comment below in corresponding section

- [x] Missed ads or ad leftovers;
- [ ] Website or app doesn't work properly;
- [ ] AdGuard gets detected on a website;
- [ ] Missed analytics or tracker;
- [ ] Social media buttons — share, like, tweet, etc;
- [ ] Annoyances — pop-ups, cookie warnings, etc;
- [ ] Filters maintenance.

## What issue is being fixed?

### Enter the issue address

https://github.com/AdguardTeam/AdguardFilters/issues/148493

### Terms

- [x] By submitting this issue, I agree that pull request does not contain private info and all conditions are met

2023-04-18 13:29 UTC, Alex-302 commented
Please do not create PRs for issues with `Lowest` priority.

2023-04-18 13:32 UTC, gork7777 commented
@Alex-302 Why?

2023-04-19 13:12 UTC, Alex-302 commented
We will decide how to handle them ourselves.

2023-04-19 13:14 UTC, Alex-302 requested changes

2023-04-19 13:14 UTC, Alex-302 commented on TurkishFilter/sections/specific.txt
> +/po-under.js$domain=anizle.com|anizm.net
Also please add a new domain to https://github.com/AdguardTeam/AdguardFilters/blob/c8a023cfa29a0a4ec1bb23e5c3440612cc01b89e/TurkishFilter/sections/general_extensions.txt#L15

2023-04-19 16:00 UTC, gork7777 commented
> We will decide how to handle them ourselves.

@Alex-302 There was no such decision before, why did you come to such a decision now?

2023-04-26 09:56 UTC, Alex-302 approved these changes

2023-04-26 09:56 UTC, merged

2023-04-26 09:58 UTC, Alex-302 commented
@gork7777 To save contributors from aimless work if we decide to close an issue without adding rules.