Block widespread push notification scam ads
AdguardTeam/AdguardFilters pull request #149610
Opened 2023-04-28 13:58 UTC by Yuki2718

## Prerequisites

### To avoid invalid pull requests, please check and confirm following terms

- [x] This is not an ad/bug report;
- [x] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
- [x] I have performed a self-review of my own changes;
- [x] My changes do not break web sites, apps and files structure.

## What problem does the pull request fix?

Push notification scam ads trying to fool user to subscribe their push notification which then deliver malicious ads.

### If the problem does not fall under any category that is listed here, please write a comment below in corresponding section

- [x] Missed ads or ad leftovers;
- [ ] Website or app doesn't work properly;
- [ ] AdGuard gets detected on a website;
- [ ] Missed analytics or tracker;
- [ ] Social media buttons — share, like, tweet, etc;
- [ ] Annoyances — pop-ups, cookie warnings, etc;
- [ ] Filters maintenance.

## What issue is being fixed?

NA

### Enter the issue address

NA

### Add your comment and screenshots

E.g. `https://adzmusic.com/ZLsNoEPrQn3DK8bMvPdo-gxu4H9USwHDKQ_StreN9jI/?clck=1d58d79744476eed686a0537d2a3bc86&sid=14892298`
`https://www.stonecarver.top/play-music-video/?pl=cY0ooXMxhEOdj-8NgPIvCw&sm=play-music-video&click_id=8c17egmfvu3hqfeecb&hash=vOmj42LBq2tQilhQn41t6w&exp=1682311985`
The second link is now suspended, I can grab a new one if needed. These two rules have been time-tested, no FP and blocking lots of those sites. There is another regex rule useful to block them but for this PR I'll focus on non-regex rules.

### Terms

- [x] By submitting this issue, I agree that pull request does not contain private info and all conditions are met

2023-05-05 16:30 UTC, Alex-302 requested changes

2023-05-05 17:11 UTC, Yuki2718 commented on BaseFilter/sections/general_url.txt
> +/?pl=*&sm=$document
Okay

2023-05-09 15:30 UTC, Yuki2718 commented
A new clck example: `https://theadvdomclub.com/EHG4A7xwuuIVaEJJogkI7g8GYeU2NrNyQY9G0LO7Yqg/?clck=7145dwf8wc8scd7d&sid=14`

2023-05-10 13:33 UTC, Alex-302 commented on BaseFilter/sections/general_url.txt
> +/?pl=*&sm=$document
@Yuki2718 What about TLD - always XYZ? Is `robot` always present on that place?

2023-05-11 16:28 UTC, Alex-302 approved these changes

2023-05-11 16:28 UTC, merged