Fix azumarikishi.co.jp social
AdguardTeam/AdguardFilters pull request #150675
Opened 2023-05-11 13:54 UTC by SKEIDs

## Prerequisites

### To avoid invalid pull requests, please check and confirm following terms

- [x] This is not an ad/bug report;
- [x] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
- [x] I have performed a self-review of my own changes;
- [x] My changes do not break web sites, apps and files structure.

## What problem does the pull request fix?

### If the problem does not fall under any category that is listed here, please write a comment below in corresponding section

- [ ] Missed ads or ad leftovers;
- [ ] Website or app doesn't work properly;
- [ ] AdGuard gets detected on a website;
- [ ] Missed analytics or tracker;
- [x] Social media buttons — share, like, tweet, etc;
- [ ] Annoyances — pop-ups, cookie warnings, etc;
- [ ] Filters maintenance.

## What issue is being fixed?

### Enter the issue address

 https://azumarikishi.co.jp/media/hangover-prevention

### Add your comment and screenshots

#### If possible, a screenshot of a page or application should not be cropped too much. Otherwise, it is not always clear where the element is located
 

<details><summary>screenshot</summary>

![](https://i.slow.pics/HYfqUrvb.png)
![](https://i.slow.pics/KPP4bcsQ.png)

</details><br/>

### Terms

- [x] By submitting this issue, I agree that pull request does not contain private info and all conditions are met

2023-05-12 11:01 UTC, Alex-302 requested changes

2023-05-12 11:01 UTC, Alex-302 commented on SocialFilter/sections/specific.txt
> +azumarikishi.co.jp,mynewgear.info,kaonavi.jp,manetatsu.com,garugram.com,pirori2ch.com,seaseagaming.tokyo,jpstreamer.com,sophiadigital.com,collieme.com,webhack.jp,mats2.net,lady1919.com,intelligence-c
It blocks back-to-top button.
Please change
```adblock
azumarikishi.co.jp##.article-header > div.fab-btn
```

2023-05-14 21:32 UTC, krystian3w requested changes
<!-- -->

2023-05-16 16:34 UTC, closed without merging

2023-05-20 01:49 UTC, SKEIDs commented
This website has no visitor. Ao, I can not add new rule.
I am sorry.