Fix cocreco.kodansha.co.jp Ad
AdguardTeam/AdguardFilters pull request #152660
Opened 2023-06-02 22:50 UTC by SKEIDs

## Prerequisites

### To avoid invalid pull requests, please check and confirm following terms

- [x] This is not an ad/bug report;
- [x] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
- [x] I have performed a self-review of my own changes;
- [x] My changes do not break web sites, apps and files structure.

## What problem does the pull request fix?

### If the problem does not fall under any category that is listed here, please write a comment below in corresponding section

- [x] Missed ads or ad leftovers;
- [ ] Website or app doesn't work properly;
- [ ] AdGuard gets detected on a website;
- [x] Missed analytics or tracker;
- [ ] Social media buttons — share, like, tweet, etc;
- [ ] Annoyances — pop-ups, cookie warnings, etc;
- [ ] Filters maintenance.

## What issue is being fixed?

### Enter the issue address

 https://cocreco.kodansha.co.jp/cocreco/general/education/D1T9X

### Add your comment and screenshots

<details><summary>screenshot</summary>

![](https://i.ibb.co/MsrydxR/image.png)
![](https://i.ibb.co/sWqmyyk/image.png)

</details><br/>

### Terms

- [x] By submitting this issue, I agree that pull request does not contain private info and all conditions are met

2023-06-03 17:39 UTC, Yuki2718 requested changes

2023-06-03 17:39 UTC, Yuki2718 commented on JapaneseFilter/sections/specific.txt
> +cocreco.kodansha.co.jp##div[class*="banner-area--adsense-"]
Better `cocreco.kodansha.co.jp##.banner-area`

2023-06-03 17:39 UTC, Yuki2718 commented on SpywareFilter/sections/specific.txt
> +||d34gglw95p9zsk.cloudfront.net/clipkit_assets/beacon-*.js
Please add `||amazonaws.com/beacon^` too.

2023-06-07 12:24 UTC, SKEIDs commented on JapaneseFilter/sections/specific.txt
> +cocreco.kodansha.co.jp##div[class*="banner-area--adsense-"]
I will fix.

2023-06-07 13:33 UTC, Yuki2718 approved these changes

2023-06-07 13:55 UTC, merged