Fix t.livepocket.jp Ad
AdguardTeam/AdguardFilters pull request #152664
Opened 2023-06-02 23:28 UTC by SKEIDs

## Prerequisites

### To avoid invalid pull requests, please check and confirm following terms

- [x] This is not an ad/bug report;
- [x] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
- [x] I have performed a self-review of my own changes;
- [x] My changes do not break web sites, apps and files structure.

## What problem does the pull request fix?

### If the problem does not fall under any category that is listed here, please write a comment below in corresponding section

- [x] Missed ads or ad leftovers;
- [ ] Website or app doesn't work properly;
- [ ] AdGuard gets detected on a website;
- [ ] Missed analytics or tracker;
- [ ] Social media buttons — share, like, tweet, etc;
- [ ] Annoyances — pop-ups, cookie warnings, etc;
- [ ] Filters maintenance.

## What issue is being fixed?

### Enter the issue address

 https://t.livepocket.jp/tag/IdolTalent

### Add your comment and screenshots

<details><summary>screenshot - PC</summary>

![](https://i.slow.pics/sjpKpWIx.png)
</details><br/>

<details><summary>screenshot - mobile</summary>

![](https://i.slow.pics/nbLRhHWt.png)
</details><br/>

### Terms

- [x] By submitting this issue, I agree that pull request does not contain private info and all conditions are met

2023-06-08 16:08 UTC, Yuki2718 requested changes

2023-06-08 16:08 UTC, Yuki2718 commented on JapaneseFilter/sections/specific.txt
> +t.livepocket.jp##div[style*="height:90px;"][style$="text-align:center"]
Better `##div[style$="height:90px; text-align:center"]`

2023-06-08 22:17 UTC, SKEIDs commented on JapaneseFilter/sections/specific.txt
> +t.livepocket.jp##div[style*="height:90px;"][style$="text-align:center"]
I see.

2023-06-09 13:02 UTC, Yuki2718 approved these changes

2023-06-12 11:03 UTC, merged