Fix mora.jp - Ad
AdguardTeam/AdguardFilters pull request #153071
Opened 2023-06-07 12:40 UTC by SKEIDs

## Prerequisites

### To avoid invalid pull requests, please check and confirm following terms

- [x] This is not an ad/bug report;
- [x] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
- [x] I have performed a self-review of my own changes;
- [x] My changes do not break web sites, apps and files structure.

## What problem does the pull request fix?

### If the problem does not fall under any category that is listed here, please write a comment below in corresponding section

- [x] Missed ads or ad leftovers;
- [ ] Website or app doesn't work properly;
- [ ] AdGuard gets detected on a website;
- [ ] Missed analytics or tracker;
- [ ] Social media buttons — share, like, tweet, etc;
- [ ] Annoyances — pop-ups, cookie warnings, etc;
- [ ] Filters maintenance.

## What issue is being fixed?

### Enter the issue address

 https://mora.jp/topics/news/anisong_weekly_20230604/

### Add your comment and screenshots

#### If possible, a screenshot of a page or application should not be cropped too much. Otherwise, it is not always clear where the element is located

<details><summary>screenshot</summary>

![](https://i.postimg.cc/tgdVBpTm/image.png)
</details><br/>

### Terms

- [x] By submitting this issue, I agree that pull request does not contain private info and all conditions are met

2023-06-08 16:03 UTC, Yuki2718 requested changes

2023-06-08 16:03 UTC, Yuki2718 commented on JapaneseFilter/sections/specific.txt
> +mora.jp##.page_adArea_bottom
Better `mora.jp##.page_adArea`

2023-06-08 22:15 UTC, SKEIDs commented on JapaneseFilter/sections/specific.txt
> +mora.jp##.page_adArea_bottom
ok

2023-06-09 13:03 UTC, Yuki2718 approved these changes

2023-06-12 11:01 UTC, merged