Add some rules for domains starting with an "A"
AdguardTeam/AdguardFilters pull request #169858
Opened 2024-01-03 13:43 UTC by JohnyP36

# Creating the pull request

> Please include a summary of the change and which issue is fixed\
> If the related issue does not exist in our repository, please create it before making pull request\
> It is highly recommended to use our [Web Reporting Tool](https://kb.adguard.com/technical-support/reporting-tool) instead of creating an issue on GitHub directly\
> Please note, that we verify every pull request manually, so it may take time to apply it

## Prerequisites

### To avoid invalid pull requests, please check and confirm following terms

- [x] This is not an ad/bug report;
- [x] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
- [x] I have performed a self-review of my own changes;
- [x] My changes do not break web sites, apps and files structure.

## What problem does the pull request fix?
### If the problem does not fall under any category that is listed here, please write a comment below in corresponding section

- [x] Missed ads or ad leftovers;
- [ ] Website or app doesn't work properly;
- [ ] AdGuard gets detected on a website;
- [ ] Missed analytics or tracker;
- [ ] Social media buttons — share, like, tweet, etc;
- [ ] Annoyances — pop-ups, cookie warnings, etc;
- [ ] Filters maintenance.

## What issue is being fixed?
### Enter the issue address

Example: #169856 
### Add your comment and screenshots

#### If possible, a screenshot of a page or application should not be cropped too much. Otherwise, it is not always clear where the element is located

0. **DO NOT** upload screenshots with sexually explicit material on GitHub directly.\
 Instead, upload it to a third-party image hosting and post the link to it without preview (!) here.\
 Also, mention if the link leads to NSFW content;

1. Add screenshots of the problem. You can drag and drop images or paste them from clipboard

    Use `<details> </details>` tag to hide screenshots under the spoiler;

2. Describe the issue in detail until it is absolutely clear from the screenshot what the problem is

    You can also indicate any other information that you think the developers should know.

**Warning:** Please remove personal information before uploading screenshots!

1. Your comment

The normal EasyList Dutch filter list is outdated a lot and in the past they wouldn't approve my new rules as it didn't meet their syntax. But that really hindered me, as some rules need the advanced Adguard/uBlock syntax. 

Below is a list of domains, so you can verify my rules. I have tested them recently (today and max 1 week old):

<details><summary>List with domains where you can find ads or left-overs</summary>

```
https://www.112achterhoek-nieuws.nl/
https://www.402online.com/

7sur7.be, ad.nl, bd.nl, bndestem.nl, destentor.nl, ed.nl, gelderlander.nl, hln.be, pzc.nl, tubantia.nl --> all on homepage

https://adultwebmaster.nl/forums/

https://www.afkortingen.nu/bios & other 2 on https://www.afkortingen.nu/

https://www.ajax1.nl/

https://www.alkmaarguardians.nl/

https://www.alle-tests.nl/ & https://www.bloovi.be/

https://www.alblasserdamsnieuws.nl/

https://allecijfers.nl/verkiezingsuitslagen/

1st: https://almere-nieuws.nl/p2000/
2nd: https://www.almere-nieuws.nl/nieuws/25595/mogelijk-verkeersconflict-voorafgaand-aan-schietpartij-in-tussen-de-vaarten/
3-5: https://www.almere-nieuws.nl/ (& [NSFW] https://www.sexjobs.nl/)

https://ans-online.nl/

https://www.apparata.nl/

https://autosport.nl/

1st: https://www.autowereld.nl/goedkope-occasions
2nd: https://www.autowereld.nl/

https://www.arenalokaal.nl/
https://www.dehavenloods.nl/
https://www.dekrantnieuws.nl/
https://www.destreekkrant.nu/
https://www.gooieneembode.nl/
https://www.hetkrantje-online.nl/
https://www.laardercourant.nl/
https://www.leiderdorpsweekblad.nl/
https://www.nnp.nl/
https://www.weespernieuws.nl/
https://www.zuidenvelder.info/

`.bannergroup`: all on homepage & https://www.dolcevia.com/nl/italie-magazine/lifestyle/4779-kerstavond-in-italie-het-feest-van-de-zeven-vissen

https://www.autowereld.nl/goedkope-occasions
https://www.autowereld.nl/
```
</details>

If I missed an URL then the element is on the homepage.

2. Screenshots

*To many to add*

### Terms

- [x] By submitting this issue, I agree that pull request does not contain private info and all conditions are met

2024-01-03 13:45 UTC, JohnyP36 commented
I know I didn't follow the guidelines on the point that it's easier to address every issue separate, but this were to many.

2024-01-09 18:32 UTC, Alex-302 requested changes

2024-01-09 18:32 UTC, Alex-302 commented on DutchFilter/sections/specific.txt
> +alkmaarguardians.nl###footer
Not even clickable. Maybe better to Annoyances-Self Promo.
```suggestion
```

2024-01-09 18:32 UTC, Alex-302 commented on DutchFilter/sections/specific.txt
> +almere-nieuws.nl#?#.promocentered:upward(section)
Too few visitors, leftovers are small
```suggestion
```

2024-01-09 18:32 UTC, Alex-302 commented on DutchFilter/sections/specific.txt
> +almere-nieuws.nl,sexjobs.nl##div[id^="banner-"]
0 px height
```suggestion
```

2024-01-09 18:32 UTC, Alex-302 commented on DutchFilter/sections/specific.txt
> +androidworld.nl,cinenews.be,handbal.nl,openrotterdam.nl,webmastersunited.com,wegdamnieuws.nl##.ads
made another rule for androidworld.nl
```suggestion
androidworld.nl##.r89-desktop-billboard-atf
cinenews.be,handbal.nl,webmastersunited.com,wegdamnieuws.nl##.ads
```

2024-01-09 18:32 UTC, Alex-302 commented on DutchFilter/sections/specific.txt
> +ans-online.nl#?#.theiaStickySidebar > .widget:has-text(/Advertentie\b/)
Blocks too much
```suggestion
ans-online.nl#?#.theiaStickySidebar > aside.penci_latest_news_widget > h4.widget-title:contains(Advertentie)
```

2024-01-09 18:32 UTC, Alex-302 commented on DutchFilter/sections/specific.txt
> +arenalokaal.nl,dehavenloods.nl,dekrantnieuws.nl,destreekkrant.nu,gooieneembode.nl,hetkrantje-online.nl,laardercourant.nl,leiderdorpsweekblad.nl,nnp.nl,weespernieuws.nl,zuidenvelder.info#?#.component_
It seems ok without `:has`
```suggestion
arenalokaal.nl,dehavenloods.nl,dekrantnieuws.nl,destreekkrant.nu,gooieneembode.nl,hetkrantje-online.nl,laardercourant.nl,leiderdorpsweekblad.nl,nnp.nl,weespernieuws.nl,zuidenvelder.info##.component__pubble-banner
```

2024-01-09 18:32 UTC, Alex-302 commented on DutchFilter/sections/specific.txt
> +arenalokaal.nl#?#.content-start > * > div[style]:has-text(/Externe links|Externe websites/i)
AdGuard syntax
```suggestion
arenalokaal.nl#?#.content-start > * > div[style]:contains(/Externe links|Externe websites/i)
```

2024-01-09 18:32 UTC, Alex-302 commented on DutchFilter/sections/specific.txt
> +arenalokaal.nl,dehavenloods.nl,hetkrantje-online.nl,laardercourant.nl,leiderdorpsweekblad.nl#?#.component__pubble-banner:has([advobject]):upward(.bg-gray-100):has-text(/Uit de krant/i)
Looks redundant
```suggestion
```

2024-01-09 18:32 UTC, Alex-302 commented on DutchFilter/sections/specific.txt
> +autosport.nl#?#.active.first:style(margin-top: 0px !important;)
It is their design of tabs
```suggestion
```

2024-01-09 18:38 UTC, merged

2024-01-09 18:39 UTC, Alex-302 commented
Commited some changes directly to your PR with comments.

2024-01-10 06:10 UTC, JohnyP36 commented
> Commited some changes directly to your PR with comments.

Thanks for the feedback, that keeps me improving how I make rules with Adguard syntax.

2024-01-10 07:11 UTC, JohnyP36 reviewed
Thanks for correcting me.