update suaurl.com
AdguardTeam/AdguardFilters pull request #173375
Opened 2024-02-22 17:45 UTC by D4niloMR

# Creating the pull request

> Please include a summary of the change and which issue is fixed\
> If the related issue does not exist in our repository, please create it before making pull request\
> It is highly recommended to use our [Web Reporting Tool](https://kb.adguard.com/technical-support/reporting-tool) instead of creating an issue on GitHub directly\
> Please note, that we verify every pull request manually, so it may take time to apply it

## Prerequisites

### To avoid invalid pull requests, please check and confirm following terms

- [X] This is not an ad/bug report;
- [X] My code follows the [guidelines](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md) and [syntax](https://kb.adguard.com/general/how-to-create-your-own-ad-filters) of this project;
- [X] I have performed a self-review of my own changes;
- [X] My changes do not break web sites, apps and files structure.

## What problem does the pull request fix?

### If the problem does not fall under any category that is listed here, please write a comment below in corresponding section

- [ ] Missed ads or ad leftovers;
- [X] Website or app doesn't work properly;
- [ ] AdGuard gets detected on a website;
- [ ] Missed analytics or tracker;
- [ ] Social media buttons — share, like, tweet, etc;
- [ ] Annoyances — pop-ups, cookie warnings, etc;
- [ ] Filters maintenance.

## What issue is being fixed?

`https://suaurl.com/getlink/880fb9`

### Add your comment and screenshots

1. Your comment

Both filters prevent the link from opening.

2. Screenshots

<details>

<summary>Screenshot 1:</summary>

</details>

<details>

<summary>Screenshot N:</summary>

</details>

### Terms

- [X] By submitting this issue, I agree that pull request does not contain private info and all conditions are met

2024-02-22 18:03 UTC, D4niloMR commented
Might be worth adding to AdGuard:

```adb
reidoplacar.com###divactioncheck > .mb-3
reidoplacar.com##.result_content_ff:style(display: block !important;)
```

2024-02-25 13:30 UTC, Yuki2718 requested changes
Needs
```
reidoplacar.com#%#//scriptlet('prevent-fetch', 'https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js')
!#if (adguard_app_ios || adguard_ext_android_cb || adguard_ext_safari)
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$xmlhttprequest,domain=reidoplacar.com
!#endif
```

in anti-adblock.txt

2024-02-25 17:24 UTC, Yuki2718 commented
Sorry, I forgot to enable Spanish list.

2024-02-25 17:24 UTC, Yuki2718 approved these changes

2024-03-07 14:54 UTC, Alex-302 approved these changes

2024-03-07 14:54 UTC, merged