Remove cname tracker lists
AdguardTeam/AdguardFilters pull request #179645
Opened 2024-05-20 15:45 UTC by jellizaveta

Related: 
https://github.com/AdguardTeam/FiltersCompiler/issues/217
https://github.com/AdguardTeam/FiltersRegistry/issues/946
Don't merge until this pr: https://github.com/AdguardTeam/FiltersRegistry/pull/953

2024-05-21 06:30 UTC, zloyden approved these changes

2024-05-21 11:13 UTC, Alex-302 approved these changes

2024-05-21 19:38 UTC, KatanaDi1408 requested changes
<!-- Error while uploading Screenshot_20240521-223316.jpg -->****~~~~~~~~****

2024-05-22 10:57 UTC, Alex-302 requested changes

2024-05-22 10:57 UTC, Alex-302 commented on BaseFilter/sections/adservers.txt
> +! add some additional rules when we can block whole CNAME domain, not only CNAME subdomains.
> ...to optimize the filter size

or something like

> which will be used during the optimization by `/optimizeDomainBlockingRules` option.

Same below.

2024-05-22 10:57 UTC, Alex-302 commented on BaseFilter/sections/adservers.txt
> +!
I'd wrap it by Comment Anchors tags

* Beginning
```
! NOTE: CNAME disguised advertising networks
! SECTION: CNAME disguised advertising networks
```

* End
```
! NOTE: CNAME disguised advertising networks end ⬆️
! !SECTION: CNAME disguised advertising networks
```

And same for tracking.

2024-05-22 10:57 UTC, Alex-302 commented on BaseFilter/sections/adservers.txt
> +! This section contains the list of the rules are against CNAME advertising networks.
Better `against CNAME` => `against CNAME disguised`... (and below)

2024-05-22 14:20 UTC, Alex-302 requested changes

2024-05-22 14:20 UTC, Alex-302 commented on BaseFilter/sections/adservers.txt
> +! !SECTION: CNAME disguised advertisin networks
a typo 
```suggestion
! !SECTION: CNAME disguised advertising networks
```

2024-05-22 14:23 UTC, zloyden approved these changes

2024-05-22 17:02 UTC, merged