Fix #181773 life.ru
AdguardTeam/AdguardFilters pull request #181876
Opened 2024-06-20 17:43 UTC by rakleed

Fix #181773 life.ru

2024-06-24 17:34 UTC, Alex-302 requested changes

2024-06-24 17:34 UTC, Alex-302 commented on AnnoyancesFilter/Cookies/sections/cookies_specific.txt
> +life.ru#%#//scriptlet('trusted-set-cookie', 'personDataConsent', 'true')
`trusted` здесь не нужен.
Лучше `:has()` примени.

2024-06-25 14:26 UTC, zloyden approved these changes

2024-06-25 14:27 UTC, zloyden commented on AnnoyancesFilter/Cookies/sections/cookies_specific.txt
> +life.ru#%#//scriptlet('trusted-set-cookie', 'personDataConsent', 'true')
Он используется когда необходим и особо других вариантов нет.

2024-06-26 06:42 UTC, merged