Fix #182052 money.usnews.com
AdguardTeam/AdguardFilters pull request #182294
Opened 2024-06-26 19:14 UTC by rakleed

Fix #182052 money.usnews.com

2024-06-28 15:21 UTC, jellizaveta commented
Сверху `Read more` осталось, блокируется TPF, правило для этого блока стоит поместить в `Spyware --> specific.txt`

2024-06-28 16:02 UTC, jellizaveta requested changes

2024-06-28 16:02 UTC, jellizaveta commented on AnnoyancesFilter/Other/sections/annoyances.txt
> +usnews.com###null-recommendations-widget
Spyware --> specific.txt

2024-06-28 16:15 UTC, jellizaveta approved these changes

2024-06-28 16:16 UTC, jellizaveta commented
@rakleed разрешите, пожалуйста конфликты. GitHub не позволяет мне это сделать в веб редакторе

2024-06-28 17:37 UTC, Alex-302 commented
Сегодня и не выйдет - гитхаб деградирует.

2024-07-01 11:25 UTC, jellizaveta commented
@rakleed Здравствуйте, не увидела вчера вашего сообщения, прошу прощения. Можно попросить разрешить новые и вмержим.

2024-07-01 12:50 UTC, merged