Fix #182384 eikaiwa.dmm.com
AdguardTeam/AdguardFilters pull request #182511
Opened 2024-06-28 22:01 UTC by rakleed

Fix #182384 eikaiwa.dmm.com

2024-06-30 13:21 UTC, Yuki2718 requested changes

2024-06-30 13:21 UTC, Yuki2718 commented on AnnoyancesFilter/Other/sections/self-promo.txt
> +eikaiwa.dmm.com###content div[class^="banner-"]
`eikaiwa.dmm.com` consists of multple sites. I prefer two rules of
```
eikaiwa.dmm.com##.banner-default
eikaiwa.dmm.com##.banner-single-top
```

for safety.

2024-07-01 09:53 UTC, Yuki2718 approved these changes

2024-07-02 11:48 UTC, Yuki2718 commented
I'm not allowed to merge PR.

2024-07-03 18:27 UTC, Sergey-Lyapin approved these changes

2024-07-03 18:28 UTC, merged