Fix/annoyances issues 05092018
AdguardTeam/AdguardFilters pull request #22033
Opened 2018-09-05 08:11 UTC by TheHasagi

#21882;#21952;#21954;#21997;#21779

2018-09-05 17:17 UTC, Alex-302 approved these changes

2018-09-05 17:34 UTC, ameshkov commented on AnnoyancesFilter/sections/annoyances.txt
> +geva.co.il#$#.mfp-bg { display:none!important; }
А почему стилем а не обычным правилом скрытия?

2018-09-06 08:10 UTC, TheHasagi commented on AnnoyancesFilter/sections/annoyances.txt
> +geva.co.il#$#.mfp-bg { display:none!important; }
Там остается оверлей и не работает прокрутка.

2018-09-06 08:11 UTC, TheHasagi commented on AnnoyancesFilter/sections/annoyances.txt
> +geva.co.il#$#.mfp-bg { display:none!important; }
Так не стоит скрывать?

2018-09-06 16:28 UTC, ameshkov commented on AnnoyancesFilter/sections/annoyances.txt
> +geva.co.il#$#.mfp-bg { display:none!important; }
`geva.co.il#$#html[-ext-has="head"] { overflow: auto; }`

2018-09-14 11:24 UTC, ameshkov requested changes
Не смог смержить нормально

2018-09-17 13:22 UTC, closed without merging