taiphanmempc.net #23055
AdguardTeam/AdguardFilters pull request #26112
Opened 2018-11-27 15:39 UTC by slavaleleka

.

2018-11-27 18:41 UTC, BlazDT commented
Popup not showing, only in code. Scrolling still works after hiding it?

2018-11-28 07:48 UTC, slavaleleka commented
Yea, scrolling works just fine

2018-11-29 10:40 UTC, Alex-302 requested changes

2018-12-03 19:45 UTC, BlazDT requested changes
No need for "third-party" option if you already use $domain.
Also please use ^$domain=   instead of only $domain

2018-12-04 14:46 UTC, Alex-302 approved these changes

2018-12-04 14:46 UTC, merged