attuale.ru #23522
AdguardTeam/AdguardFilters pull request #26162
Opened 2018-11-28 17:10 UTC by slavaleleka

.

2018-11-29 10:45 UTC, Alex-302 requested changes

2018-11-29 10:45 UTC, Alex-302 commented on RussianFilter/sections/adservers.txt
> +||kak-bit-new.ru^$third-party
Там есть `<script>window.RESOURCE_O1B2L3 = 'kak-bit-new.ru';</script>`
В фильтрах ищи `window.RESOURCE`, в начало списка добавь домен. Если кириллица - то в конец.
При блокировке домена правила ниже нужны?

2018-11-29 12:12 UTC, slavaleleka commented on RussianFilter/sections/adservers.txt
> +||kak-bit-new.ru^$third-party
добавил домен в список. правила ниже нужны (подчищают остатки)

2018-11-30 11:29 UTC, Alex-302 approved these changes

2018-11-30 11:29 UTC, merged