dha.com.tr #24115
AdguardTeam/AdguardFilters pull request #26221
Opened 2018-11-29 18:29 UTC by slavaleleka

2018-11-29 19:04 UTC, BlazDT requested changes
dha.com.tr##.news-body > div[style="width:315px;float:left;height:250px;padding:3px;"]

Element below whatsapp not reproduced. Other one is site's design.

2018-12-03 16:35 UTC, Alex-302 commented
@BlazDT

2018-12-03 19:41 UTC, BlazDT approved these changes

2018-12-04 10:20 UTC, Alex-302 approved these changes

2018-12-04 10:20 UTC, merged