ondemandkorea.com #24315
AdguardTeam/AdguardFilters pull request #26272
Opened 2018-11-30 15:54 UTC by slavaleleka

.

2018-12-03 16:35 UTC, AdamWr approved these changes

2018-12-03 19:24 UTC, BlazDT approved these changes

2018-12-03 19:24 UTC, BlazDT approved these changes

2018-12-06 09:34 UTC, Alex-302 requested changes

2018-12-06 09:34 UTC, Alex-302 commented on EnglishFilter/sections/specific.txt
> +ondemandkorea.com###playerMasthed > #player > .player_ads
можно без `#playerMasthed > #player > `  Класс элемента и так говорящий.

2018-12-06 20:46 UTC, Alex-302 approved these changes

2018-12-06 20:46 UTC, merged