smithsonianmag.com #24278
AdguardTeam/AdguardFilters pull request #26270
Opened 2018-11-30 15:35 UTC by slavaleleka

.

2018-12-03 19:28 UTC, BlazDT requested changes
Use ext-CSS rule to hide the ad text in sidebar. Class name is unsafe.

Also please add the proposed rule by user.

2018-12-04 11:18 UTC, slavaleleka commented
.sticky-block disappeared, I guess with such class name it's safe now. or it is not?

2018-12-04 12:31 UTC, BlazDT commented
Yes, it is safe now. But the "||logs ..." rule must be moved to SpywareFilter/tracking_servers_firstparty.txt

2018-12-06 09:32 UTC, Alex-302 requested changes

2018-12-06 09:32 UTC, Alex-302 commented on SpywareFilter/sections/tracking_servers_firstparty.txt
> +||logs*.smithsonian.museum^$domain=smithsonianmag.com
specific.txt

2018-12-06 09:32 UTC, Alex-302 commented on EnglishFilter/sections/specific.txt
> +smithsonianmag.com##.main-wrapper > .sidebar > .special-offers-from-advertisers-ad-showcase
можно без `.main-wrapper > .sidebar >`

2018-12-06 20:48 UTC, Alex-302 approved these changes

2018-12-06 20:48 UTC, merged