pornov.online #24390
AdguardTeam/AdguardFilters pull request #26448
Opened 2018-12-03 10:42 UTC by slavaleleka

.

2018-12-03 16:51 UTC, AdamWr commented
Could you please check the main page too?
If I'm not wrong there is an ad and ad leftover here:
<details><summary>Screenshot</summary>

![po](https://user-images.githubusercontent.com/29142494/49387954-506c7000-f723-11e8-95a4-383df64eaff3.jpg)

</details>
<br>

2018-12-03 18:46 UTC, BlazDT requested changes
||pornov.online/img/asd^
pornov.online##.thumbnails > li:has(.thumbnail > a[href^="/asd/"])

ext-CSS rule hides left-over at main page and on linked page.

2018-12-04 11:13 UTC, Alex-302 requested changes

2018-12-04 11:13 UTC, Alex-302 commented on RussianFilter/sections/specific.txt
> +pornov.online###right > .hsad
you can use just `.hsad`

2018-12-04 14:27 UTC, Alex-302 approved these changes

2018-12-04 14:27 UTC, merged