itemci.com #24520
AdguardTeam/AdguardFilters pull request #26455
Opened 2018-12-03 13:22 UTC by slavaleleka

.

2018-12-03 18:36 UTC, BlazDT requested changes
Move the rules to Turkish filter.

2018-12-04 10:39 UTC, Alex-302 commented
@BlazDT

2018-12-04 11:04 UTC, Alex-302 requested changes

2018-12-04 11:04 UTC, Alex-302 commented on TurkishFilter/sections/specific.txt
> +||itemci.com/jsrc/jquery.fancybox.min.js$domain=itemci.com
also this rule breaks the slider at the top

2018-12-04 11:04 UTC, Alex-302 commented on TurkishFilter/sections/specific.txt
> +||itemci.com/jsrc/jquery.fancybox.min.js$domain=itemci.com
better use extended CSS
```
itemci.com#$#html.fancybox-lock:has(> body) { overflow: visible!important; }
itemci.com#$#html.fancybox-lock:has(> body) > body { overflow: visible!important; }
itemci.com#$#body > div.fancybox-overlay:has(> div) { display: none!important; }
```

2018-12-04 14:25 UTC, Alex-302 requested changes

2018-12-04 15:41 UTC, Alex-302 approved these changes

2018-12-04 15:41 UTC, merged