iza.ne.jp #24067
AdguardTeam/AdguardFilters pull request #26574
Opened 2018-12-06 11:20 UTC by slavaleleka

https://github.com/AdguardTeam/AdguardFilters/issues/24067

only for web version, for android won't fix

2018-12-06 11:58 UTC, BlazDT requested changes

2018-12-06 11:58 UTC, BlazDT commented on JapaneseFilter/sections/css_extended.txt
> +iza.ne.jp#$#.sideFixedWrapper { position: relative!important; }
Not css_extended. It is general_extensions.
I also don't see a difference with this rule.

2018-12-06 11:58 UTC, BlazDT commented on JapaneseFilter/sections/specific.txt
> +||prt.iza.ne.jp/common/css/v2/images/bg_header_003.png^$domain=iza.ne.jp
Request not reproduced - also $domain is unnecessary.
Same for other url block rule.

2018-12-06 11:58 UTC, BlazDT commented on JapaneseFilter/sections/specific.txt
> +iza.ne.jp##section.module-pickup-topics
Breaks good content.

2018-12-06 11:58 UTC, BlazDT commented on JapaneseFilter/sections/specific.txt
> +iza.ne.jp##aside.ad-tokudane
All those aside.ad rules can be done with this rule:
iza.ne.jp##aside[class^="ad-"]

2018-12-06 11:58 UTC, BlazDT commented on SpywareFilter/sections/specific.txt
> +||smp.sankei.co.jp/js/analytics/skd.Analysis.js^$domain=iza.ne.jp
Change to:
`||smp.sankei.co.jp/js/analytics^`

2018-12-06 12:35 UTC, slavaleleka commented
@BlazDT 
without `iza.ne.jp#$#.sideFixedWrapper { position: relative!important; }`
`div#SecondaryContents` sticks to the bottom after scrolling in desktop browser

2018-12-17 12:32 UTC, Alex-302 commented on JapaneseFilter/sections/general_extensions.txt
> +iza.ne.jp#$#.sideFixedWrapper { position: relative!important; }
add a comment with URL of an issue, as above

2018-12-17 12:33 UTC, Alex-302 commented on JapaneseFilter/sections/general_extensions.txt
> +iza.ne.jp#$#.sideFixedWrapper { position: relative!important; }
or description of the rule

2018-12-19 10:53 UTC, Alex-302 approved these changes

2018-12-19 10:53 UTC, merged