ebalovo.info #25230
AdguardTeam/AdguardFilters pull request #28370
Opened 2019-01-16 08:14 UTC by slavaleleka

https://github.com/AdguardTeam/AdguardFilters/issues/25230

2019-01-18 16:51 UTC, Alex-302 requested changes

2019-01-18 16:51 UTC, Alex-302 commented on AnnoyancesFilter/sections/popups.txt
> +ebalovo.net#$#body > .modal { display: none!important; }
we don't block 18+ notification popups

2019-01-21 20:11 UTC, Alex-302 approved these changes

2019-01-22 17:26 UTC, AdamWr approved these changes

2019-01-24 22:58 UTC, Alex-302 approved these changes

2019-01-24 22:59 UTC, merged