fix #26301 flyingmag.com
AdguardTeam/AdguardFilters pull request #29059
Opened 2019-02-01 09:38 UTC by slavaleleka

https://github.com/AdguardTeam/AdguardFilters/issues/26301

2019-02-01 17:50 UTC, BlazDT requested changes
Paywall which we do not fix.

2019-02-04 09:07 UTC, slavaleleka commented
it's about InstartLogic script (ads and cookie); see no paywall on my end

2019-02-04 12:46 UTC, BlazDT approved these changes

2019-02-04 12:47 UTC, BlazDT commented
Screenshot showed paywall, therefore the comment.

2019-02-05 14:50 UTC, Alex-302 approved these changes

2019-02-05 14:50 UTC, merged