fix #27086 amazon.com.tr
AdguardTeam/AdguardFilters pull request #29372
Opened 2019-02-08 07:33 UTC by slavaleleka

https://github.com/AdguardTeam/AdguardFilters/issues/27086

2019-02-08 10:20 UTC, PentagramTr commented
@slavaleleka

Rule doesn't work on the mobile site.
`amazon.com.tr###desktop-banner-stripe`

2019-02-08 12:13 UTC, PentagramTr commented
Now it is not working in the desktop version.

<details><summary>Screenshot:</summary>

![www amazon com tr](https://user-images.githubusercontent.com/34379403/52474862-b6092c80-2baa-11e9-86fe-7c4b2651bb37.png)


</details>
<br />

@slavaleleka

2019-02-11 19:52 UTC, Alex-302 commented on SpywareFilter/sections/specific.txt
> +||amazon.com.tr/*/uedata?
Better `/uedata?`. And remove old rules.

2019-02-11 19:54 UTC, Alex-302 requested changes
Better `/uedata?`(like in EasyPrivacy). And remove old rules.

2019-02-16 14:36 UTC, Alex-302 approved these changes

2019-02-16 14:36 UTC, merged