fix #27802 anilibria.tv
AdguardTeam/AdguardFilters pull request #30164
Opened 2019-02-26 10:30 UTC by slavaleleka

https://github.com/AdguardTeam/AdguardFilters/issues/27802

2019-03-10 17:21 UTC, Alex-302 commented on RussianFilter/sections/css_extended.txt
> +anilibria.tv##div:has(> #headercontent)
от BODY сделай, а то очень широкое правило

2019-03-10 17:22 UTC, Alex-302 requested changes

2019-03-10 17:22 UTC, Alex-302 commented on RussianFilter/sections/specific.txt
> +anilibria.tv##a[href*="advg.agency"]
уже не актуально, похоже

2019-03-15 21:43 UTC, Alex-302 commented on RussianFilter/sections/specific.txt
> +anilibria.tv##a[href*="advg.agency"]
Опять переделали) Попробуй расширенным CSS его

2019-03-19 09:38 UTC, poiuty commented
Пожалуйста, разблокируйте websocket для домена anilibria.tv
https://img.poiuty.com/img/70/610536c6e63f9633cb8ea8a169f4fa70.png
```
ws*://$domain=0day.kiev.ua|...|anilibria.tv
```

Websocket нужен для счетчика.
https://github.com/anilibria/anilibria/blob/master/other/stat.go
https://img.poiuty.com/img/75/5918cfb143c5a8d69b0367e949352675.png
https://img.poiuty.com/img/31/347e870a2e10f36d51c9b4b5a8504c31.png

<hr>

Пожалуйста, не блокируйте шапку сайта.

> Header стилизован под дизайн сайта.
>
> Ссылка не занимает много места.
> https://img.poiuty.com/img/10/3c8c86a3207b7d2de229387fbcb6b810.png
>
> На сайте мало рекламы (шапка и плеер).
> Можно отключить в настройках.
> https://img.poiuty.com/img/88/1f1abf88566efb07cc5e87b8c255a388.png
> https://img.poiuty.com/img/8d/c0541f726e400f5bfddf4a7a99ae3b8d.png

<hr>

Белый список - плохая идея.
https://forums.lanik.us/viewtopic.php?f=102&t=34618
https://www.youtube.com/watch?v=d4KunAODlTM&t=590s
```
anilibria.tv##body > div:not(:has(> div > div.contentmenu)):not(:has(> div[class^="footer_"])):not(div.clear)
```
```html
<!-- change class name --> 
<div class="contentmenu1">
```
<img src="https://img.poiuty.com/img/b0/75de44de12fdda742b03557001958bb0.png">

Пусть пользователь сам решает - блокировать header или нет.
```
через свой фильтр (adblock, adguard ...)
через настройки сайта
```

Не будете навязывать всем пользователям блокировку header.
Уберем random class name.

2019-03-19 13:51 UTC, closed without merging

2019-03-19 13:56 UTC, Alex-302 commented
> Пожалуйста, разблокируйте websocket для домена anilibria.tv

не вижу такого запроса. Как его повторить?

2019-03-20 06:21 UTC, poiuty commented
Спасибо https://github.com/AdguardTeam/AdguardFilters/commit/a880472f6af44cdd5e788622a80817ffff603565. WebSocket работает.
Убрал background image base64, random class name & image size.

2019-04-03 09:41 UTC, slavaleleka commented
@poiuty зарегистрировавшись у вас на сайте, рекламу можно отключить, но об этом нигде не указано. и нам продолжают репортить о рекламе в шапке. вы не могли бы сообщать пользователям, чтобы это было очевидно — либо зарегистрироваться, либо видеть рекламу?

2019-04-10 02:09 UTC, poiuty commented
@slavaleleka, думаю размещать уведомлние избыточно. Такая информация не интересна зрителю.
Пользователь может самостоятельно заблокировать ссылку/ шапку.
Возможно, компромис добавить  `title="Вы можете отключить рекламу в личном кабинете"`