fix #27793 adultwalls.com
AdguardTeam/AdguardFilters pull request #30254
Opened 2019-02-28 08:55 UTC by slavaleleka

https://github.com/AdguardTeam/AdguardFilters/issues/27793

2019-02-28 09:52 UTC, BlazDT requested changes
Following rules are sufficient for me. That way the animated stripper is also blocked for products which do not support javascript rules:

```
adultwalls.com##.sidebar .panel:has(h3.panel-title:contains(Sponsors))
||adultwalls.com/istripper^
||adultwalls.com/td480c6bc2c7.js
```

2019-03-10 14:54 UTC, Alex-302 commented
> ||adultwalls.com/td480c6bc2c7.js

can be blocked by adding new domain to `/\/t[a-f0-9]{10,13}\.js$/$domain=motaen.com|camclips.cc|camwhores.biz|freeporn-site.com|imageteam.org|cambabe.video|cambabe.me|caminspector.net|free-strip-games.com|hdgirlstock.com|camwhores.tv`

2019-03-15 21:49 UTC, Alex-302 commented
@BlazDT

2019-03-16 08:23 UTC, BlazDT approved these changes

2019-03-29 15:44 UTC, merged