fix hi-fi.ru #33327
AdguardTeam/AdguardFilters pull request #35189
Opened 2019-06-13 16:24 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/33327

2019-06-13 16:44 UTC, Alex-302 requested changes

2019-06-13 16:44 UTC, Alex-302 commented on AnnoyancesFilter/sections/annoyances.txt
> +hi-fi.ru##a[href^="https://zen.yandex.ru"]
plz move to `!* Subscriptions/newsletters (not popups)` section in this file, you can add new domain to existing rule

2019-06-14 08:29 UTC, AdamWr approved these changes

2019-06-14 10:12 UTC, Alex-302 approved these changes

2019-06-14 10:37 UTC, merged