fix tutsgalaxy.com #31402
AdguardTeam/AdguardFilters pull request #35188
Opened 2019-06-13 15:57 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/31402

2019-06-13 16:53 UTC, BlazDT requested changes

2019-06-13 16:53 UTC, BlazDT commented on AnnoyancesFilter/sections/annoyances.txt
> +tutsgalaxy.com###secondary > .widget_blog_subscription
Please move the rule internally as this way it suggests it is related to id 28876

2019-06-14 08:26 UTC, AdamWr approved these changes

2019-06-14 11:36 UTC, Alex-302 approved these changes

2019-06-14 11:37 UTC, merged