fix #35232 theblockcrypto.com
AdguardTeam/AdguardFilters pull request #35234
Opened 2019-06-14 15:41 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/35232

2019-06-14 15:52 UTC, BlazDT requested changes

2019-06-14 15:52 UTC, BlazDT commented on AnnoyancesFilter/sections/annoyances.txt
> +theblockcrypto.com##.fixed-bottom
I would suggest: theblockcrypto.com##body > .fixed-bottom
Also please move the rule to /popups.txt

2019-06-17 07:19 UTC, BlazDT approved these changes

2019-06-17 08:50 UTC, AdamWr approved these changes

2019-06-17 10:14 UTC, Alex-302 approved these changes

2019-06-17 10:14 UTC, merged