fix #28348 daily.afisha.ru
AdguardTeam/AdguardFilters pull request #35487
Opened 2019-06-19 10:11 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/28348

2019-06-19 10:18 UTC, BlazDT approved these changes

2019-06-19 12:52 UTC, AdamWr approved these changes

2019-06-19 18:46 UTC, Alex-302 commented
Please check also another pages:
![image](https://user-images.githubusercontent.com/8361299/59791809-8fd36600-92db-11e9-9e08-564d0c364e83.png)
and ad leftovers on the main page(use extended CSS, and check for obsolete rules)

2019-06-20 14:58 UTC, BlazDT requested changes

2019-06-20 14:58 UTC, BlazDT commented on AnnoyancesFilter/sections/popups.txt
> +! afisha.ru - floating element
Comment is not required

2019-06-20 15:21 UTC, BlazDT approved these changes

2019-06-20 18:36 UTC, Alex-302 approved these changes

2019-06-20 18:37 UTC, merged