fix #31827 aksam.com.tr
AdguardTeam/AdguardFilters pull request #35585
Opened 2019-06-21 07:51 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/31827

2019-06-21 08:10 UTC, BlazDT requested changes

2019-06-21 08:10 UTC, BlazDT commented on TurkishFilter/sections/css_extended.txt
> +aksam.com.tr#?#.column > .center:has(> .wrapper)
.wrapper is too generic. Better > div > div[id^="div-gpt-ad-"].

Mobile app:
#bottomrightside > a[href*="/app"]

2019-06-21 09:48 UTC, BlazDT approved these changes

2019-06-24 21:35 UTC, Alex-302 commented on TurkishFilter/sections/css_extended.txt
> +aksam.com.tr#?#.column > .center:has(> div > div[id^="div-gpt-ad-"])
`#?#` - `?` is redundant in this case.

2019-06-25 19:59 UTC, Alex-302 approved these changes

2019-06-25 19:59 UTC, merged