fix #31672 newsru.co.il
AdguardTeam/AdguardFilters pull request #35598
Opened 2019-06-21 11:20 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/31672

2019-06-21 22:30 UTC, BlazDT requested changes
Not directly an ad which hides it, just articles from third-party site, I would put it into Annoyances.
@Alex-302 what do you think?

Please block also:
<img width="671" alt="newsru" src="https://user-images.githubusercontent.com/34266271/59954352-80435100-9484-11e9-9090-6b0cfa21cfa9.png">

2019-06-24 18:56 UTC, Alex-302 commented on RussianFilter/sections/specific.txt
> +newsru.co.il##.aux-container > div > .ad
`##.ad` is safe on this site

2019-06-24 18:57 UTC, Alex-302 commented
> Not directly an ad which hides it, just articles from third-party site, I would put it into Annoyances.
> @Alex-302 what do you think?

this is ad. Please check without ad blocker.

2019-06-25 19:56 UTC, Alex-302 requested changes

2019-06-25 19:56 UTC, Alex-302 commented on RussianFilter/sections/css_extended.txt
> +newsru.co.il#?#.left-column > div:has(> div > div > a[href][target="_blank"])
`#?#` - remove `?`

2019-06-26 22:10 UTC, BlazDT approved these changes

2019-06-27 09:39 UTC, slavaleleka requested changes
I guess this part of header should be unblocked.
`~newsru.co.il##.social-buttons` to SocialFilter > general_elemhide.txt

![Screenshot 2019-06-27 at 12 24 01](https://user-images.githubusercontent.com/45171506/60254703-0fae9100-98d7-11e9-93df-19bc77c727f3.png)
_____________________________

and block that left-over please (for content blockers only)

![Screenshot 2019-06-27 at 12 31 33](https://user-images.githubusercontent.com/45171506/60255298-2dc8c100-98d8-11e9-8f24-56a92faeb108.png)

2019-06-28 11:12 UTC, Alex-302 requested changes

2019-06-28 11:12 UTC, Alex-302 commented on RussianFilter/sections/css_extended.txt
> +newsru.co.il##.left-column > div:has(> div > div > a[href][target="_blank"])
too wide selector. Make it more specific

2019-06-28 12:06 UTC, Alex-302 approved these changes

2019-06-28 12:06 UTC, merged