fix #28916 wotspeak.org
AdguardTeam/AdguardFilters pull request #35605
Opened 2019-06-21 13:29 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/28916

2019-06-21 22:37 UTC, BlazDT requested changes
Main page left-over:
wotspeak.org#?#.col-left > div[class]:not([id]):not(.hblock-catop):has(> div > .adsbygoogle)

2019-06-24 18:48 UTC, Alex-302 commented on AnnoyancesFilter/sections/popups.txt
> +jquery.slick-modals.min.js^$domain=wotspeak.org
better use full file name with slash - `/jquery.slick-modals.min.js`

2019-06-24 18:53 UTC, Alex-302 commented on RussianFilter/sections/specific.txt
> +/engine/modules/banners/wot*$image,domain=wotspeak.org
`/engine/modules/banners/` is not popular. I prefer to use `||wotspeak.org/engine/modules/banners/` It seems it contains only ads.

2019-06-25 19:55 UTC, Alex-302 approved these changes

2019-06-25 19:56 UTC, merged