fix #30910 mforos.com
AdguardTeam/AdguardFilters pull request #35740
Opened 2019-06-24 13:22 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/30910

2019-06-26 22:31 UTC, BlazDT approved these changes

2019-06-28 10:12 UTC, Alex-302 requested changes
comment + share button at the header

2019-06-28 10:12 UTC, Alex-302 commented on AnnoyancesFilter/sections/css_extended.txt
> +mforos.com#?#body > div:has(> div > div > p > a[href="https://servicios.miarroba.com/cookies/"])
better use less wide selector
`body > div[id][class] > div[class]:has(> div > p > a[href="https://servicios.miarroba.com/cookies/"])`

2019-06-28 12:09 UTC, Alex-302 approved these changes

2019-06-28 12:09 UTC, merged