fix #31800 forum.antichat.ru
AdguardTeam/AdguardFilters pull request #35798
Opened 2019-06-25 14:44 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/31800

2019-06-26 23:06 UTC, BlazDT approved these changes

2019-06-28 11:36 UTC, Alex-302 requested changes

2019-06-28 11:36 UTC, Alex-302 commented on RussianFilter/sections/specific.txt
> +forum.antichat.ru##.funboxWrapper  a > img
`ul[class^="sam1Bannner"]`
or
`ul[class^="sam"][class*="Bannner"]`
and check existing rules, some are obsolete

2019-07-01 19:29 UTC, Alex-302 approved these changes

2019-07-01 19:29 UTC, merged