fix #31698 zozhnik.ru
AdguardTeam/AdguardFilters pull request #35793
Opened 2019-06-25 12:37 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/31698

2019-06-26 22:52 UTC, BlazDT requested changes

2019-06-26 22:52 UTC, BlazDT commented on RussianFilter/sections/general_extensions.txt
> +zozhnik.ru#$#body { background: #000000!important; margin-top: -300px!important; }
Black background is not good. When you disable red background you will have this element:
    background: url(/i/bg.png) #addadf;

2019-06-26 22:52 UTC, BlazDT commented on RussianFilter/sections/specific.txt
> +||zozhnik.ru/wp-content/uploads/2019/05/Zozhnik.png
For left-over:
zozhnik.ru##.footer__con__leftblock__reclama

2019-06-28 11:51 UTC, Alex-302 requested changes

2019-06-28 11:51 UTC, Alex-302 commented on RussianFilter/sections/general_extensions.txt
> +zozhnik.ru#$#body { margin-top: -300px!important; }
не тот элемент изменяешь. Нужно тот, для которого задан отступ - `body > div#page`

2019-07-02 09:05 UTC, BlazDT approved these changes

2019-07-02 20:44 UTC, Alex-302 approved these changes

2019-07-02 20:44 UTC, merged