fix #31829 raywenderlich.com
AdguardTeam/AdguardFilters pull request #35804
Opened 2019-06-25 16:01 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/31829

2019-06-26 22:04 UTC, BlazDT requested changes

2019-06-26 22:04 UTC, BlazDT commented on AnnoyancesFilter/sections/annoyances.txt
> +raywenderlich.com##.c-global-footer__wrapper > div:has(p[class*="newsletter"])
Please move to css_extended

2019-06-27 08:32 UTC, BlazDT approved these changes

2019-06-28 12:11 UTC, Alex-302 requested changes

2019-06-28 12:11 UTC, Alex-302 commented on AnnoyancesFilter/sections/popups.txt
> +raywenderlich.com##div[class*="banner-advert-sticky"]
зачем `*`? Можно же просто `raywenderlich.com##.c-banner-advert-sticky`
Для остальных так же

2019-06-28 15:52 UTC, BlazDT approved these changes

2019-07-01 19:23 UTC, Alex-302 approved these changes

2019-07-01 19:23 UTC, merged