fix #31877 rumormillnews.com
AdguardTeam/AdguardFilters pull request #35841
Opened 2019-06-26 15:58 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/31877

2019-06-28 13:16 UTC, Alex-302 requested changes
better block that ads by url

2019-06-28 13:16 UTC, Alex-302 commented on AnnoyancesFilter/sections/antiadblock.txt
> +rumormillnews.com$$script[tag-content="if(!document"][max-length="120"]
why not `@@||rumormillnews.com/ads.js`?

2019-06-28 13:16 UTC, Alex-302 commented on EnglishFilter/sections/specific.txt
> +rumormillnews.com##a[target="_blank"] > img
too wide rule

2019-06-28 13:16 UTC, Alex-302 commented on EnglishFilter/sections/specific.txt
> +rumormillnews.com##.fr-widget
not an ad

2019-06-28 13:16 UTC, Alex-302 commented on EnglishFilter/sections/css_extended.txt
> +rumormillnews.com##div:has(a[href*="calculatorcat.com"])
wide

2019-06-28 15:52 UTC, BlazDT approved these changes

2019-07-01 19:22 UTC, Alex-302 commented on EnglishFilter/sections/specific.txt
> +||rumormillnews.com/Images/nanacast-RMNsidebar.jpg
better combine first-party images in one regex rule

2019-07-04 20:52 UTC, Alex-302 approved these changes

2019-07-04 20:53 UTC, merged