Changes for Ext CSS rules - `##`/`#$#` => `#?#`/`#?#`
AdguardTeam/AdguardFilters pull request #35954
Opened 2019-06-29 15:01 UTC by Alex-302

*** Don't merge it ***

https://regex101.com/r/uGzQhl/6/

2019-07-04 17:14 UTC, BlazDT requested changes
EnglishFilter/sections/specific.txt
Russian/sections/general_extensions.txt
RussianFilter/sections/specific.txt 
TurkishFilter/sections/general_extensions.txt
pcwelt.de#?##sidebar > div[class="box"][-ext-has='span[class$="banner-text"]']
amateurbusters.com#?#.sb_area > .sb_area_headline:contains(Urlaub)

All be moved to ext-css.


These rules do not make sense to me:
html:has(> body)
Every valid html has body, so ext-css not useful here.

2019-07-04 17:14 UTC, BlazDT commented on UsefulAdsFilter/sections/usefulads.txt
> +google.com,google.ad,google.ae,google.com.af,google.com.ag,google.com.ai,google.al,google.am,google.co.ao,google.com.ar,google.as,google.at,google.com.au,google.az,google.ba,google.com.bd,google.be,g
Not an ext-CSS rule. So `?` must be removed again.

2019-07-04 20:56 UTC, Alex-302 commented
@BlazDT look at `##`/`#$#` => `#?#`/`#?#` only, don't check the rules and conflicts)
You can try that regexp in custom branch in VSC.

```
EnglishFilter/sections/specific.txt
Russian/sections/general_extensions.txt
RussianFilter/sections/specific.txt
TurkishFilter/sections/general_extensions.txt
```
what do you mean?

2019-07-04 21:53 UTC, BlazDT commented
The mentioned files include ext-CSS rules

2019-07-04 23:05 UTC, Alex-302 commented
What abour regexp? Please check cosmetic rule markers only - `#**#`.

2019-07-04 23:22 UTC, BlazDT commented
I did not notice any errors after you fixed it in 2nd commit.

2019-07-05 09:57 UTC, Alex-302 commented
ok

2019-09-13 22:32 UTC, closed without merging