fix #35997 24h.pchome.com.tw
AdguardTeam/AdguardFilters pull request #36057
Opened 2019-07-01 10:27 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/35997

2019-07-01 16:01 UTC, BlazDT requested changes

2019-07-01 16:01 UTC, BlazDT commented on EnglishFilter/sections/foreign.txt
> +||ecimg.tw/img/xdsys/v3/layout/h24/sign/channel*/h24/3c/ad_*.jpg
Better to use wildcard for v3 and h24.

2019-07-02 09:00 UTC, BlazDT commented on EnglishFilter/sections/foreign.txt
> +||ecimg.tw/img/xdsys/*/layout/*/sign/channel*/h24/3c/ad_*.jpg
There is an additional h24. Also 3c please.

||ecimg.tw/img/xdsys/*/layout/*/sign/channel*/ad_*.jpg

2019-07-02 20:17 UTC, Alex-302 approved these changes

2019-07-02 20:17 UTC, merged