Fix #36054 id.logi.com
AdguardTeam/AdguardFilters pull request #36066
Opened 2019-07-01 13:45 UTC by tvinzz

https://github.com/AdguardTeam/AdguardFilters/issues/36054

2019-07-01 16:13 UTC, BlazDT requested changes

2019-07-01 16:13 UTC, BlazDT commented on SocialFilter/sections/whitelist.txt
> +@@||apis.google.com/js/platform.js$domain=id.logi.com,third-party
"third-party" is not required.

2019-07-02 09:03 UTC, BlazDT approved these changes

2019-07-02 11:52 UTC, Alex-302 approved these changes

2019-07-02 11:52 UTC, merged