Fix #36058 sims4pack.ru
AdguardTeam/AdguardFilters pull request #36065
Opened 2019-07-01 13:21 UTC by tvinzz

https://github.com/AdguardTeam/AdguardFilters/issues/36058

2019-07-01 16:19 UTC, BlazDT requested changes

2019-07-01 16:19 UTC, BlazDT commented on SocialFilter/sections/specific.txt
> +sims4pack.ru##.menu-block:has(#vk_groups)
Please move this and the following rule to css_extended. Also please modify both ext-css rules to include parent element:

.block-right > .menu-block

2019-07-01 16:19 UTC, BlazDT commented on SpywareFilter/sections/specific.txt
> +||mc.yandex.ru^$domain=sims4pack.ru,third-party
This and the following domains are already blocked by Spyware filter.

2019-07-01 16:19 UTC, BlazDT commented on SpywareFilter/sections/specific.txt
> +||yastatic.net^$domain=sims4pack.ru,third-party
Not spyware. Social filter already blocks share.js and script file blocked contains this:
https://github.com/es-shims/es5-shim

2019-07-01 18:00 UTC, Alex-302 requested changes

2019-07-02 20:10 UTC, Alex-302 commented on SocialFilter/sections/css_extended.txt
> +sims4pack.ru##.block-right > .menu-block:has(#vk_groups)
better add `.block-right > .menu-block:has(> #vk_groups)`

2019-07-03 15:46 UTC, Alex-302 approved these changes

2019-07-03 15:46 UTC, merged