Fix #36194 poelab.com
AdguardTeam/AdguardFilters pull request #36206
Opened 2019-07-04 09:14 UTC by tvinzz

https://github.com/AdguardTeam/AdguardFilters/issues/36194

2019-07-04 21:16 UTC, Alex-302 requested changes

2019-07-04 21:16 UTC, Alex-302 commented on EnglishFilter/sections/adservers.txt
> +||playwire.com^$third-party
this is not ad server

2019-07-04 21:16 UTC, Alex-302 commented on AnnoyancesFilter/sections/popups.txt
> +||playwire.com^$domain=poelab.com,third-party
`third-party` is unnecessary here

2019-07-04 21:16 UTC, Alex-302 commented on AnnoyancesFilter/sections/popups.txt
> +||playwire.com^$domain=poelab.com,third-party
better add te existing rule `||playwire.com^$domain=` in Base filter

2019-07-10 14:54 UTC, slavaleleka approved these changes

2019-07-10 14:59 UTC, merged