fix #34539 ru.autogidas.lt
AdguardTeam/AdguardFilters pull request #36254
Opened 2019-07-05 14:39 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/34539

2019-07-05 15:00 UTC, BlazDT approved these changes

2019-07-05 16:18 UTC, slavaleleka requested changes
social button missed

![Screenshot 2019-07-05 at 19 17 09](https://user-images.githubusercontent.com/45171506/60734748-97407380-9f59-11e9-8b91-be5853540e16.png)

2019-07-08 07:16 UTC, slavaleleka approved these changes

2019-07-08 15:10 UTC, BlazDT approved these changes

2019-07-08 19:00 UTC, Alex-302 approved these changes

2019-07-08 19:02 UTC, merged