Fix #36415 otpbank.hu
AdguardTeam/AdguardFilters pull request #36435
Opened 2019-07-08 10:56 UTC by tvinzz

https://github.com/AdguardTeam/AdguardFilters/issues/36415

2019-07-08 16:07 UTC, BlazDT requested changes

2019-07-08 16:07 UTC, BlazDT commented on AnnoyancesFilter/sections/css_extended.txt
> +otpbank.hu#$##modal-content:contains('cookie') { display: none !important }
Remove the mentioned rule and add this rule to cookies:
otpbank.hu#$##gdpr_modal { display:none!important; }

2019-07-09 19:42 UTC, Alex-302 requested changes

2019-07-09 19:42 UTC, Alex-302 commented on AnnoyancesFilter/sections/cookies_specific.txt
> +otpbank.hu#$#body { overflow: visible !important }
missed `;`

2019-07-10 15:46 UTC, slavaleleka approved these changes

2019-07-10 15:47 UTC, merged