Fix #36410 invitel.hu
AdguardTeam/AdguardFilters pull request #36433
Opened 2019-07-08 10:31 UTC by tvinzz

https://github.com/AdguardTeam/AdguardFilters/issues/36410

2019-07-08 16:04 UTC, BlazDT requested changes
Please also add `invitel.hu#@#.afs_ads` for adblock detection in case they change script.

2019-07-08 20:20 UTC, Alex-302 commented
one rule is enough. You can just hide it. Don't wast a lot of time for annoyances.

2019-07-09 19:45 UTC, Alex-302 requested changes

2019-07-09 19:45 UTC, Alex-302 commented on AnnoyancesFilter/sections/antiadblock.txt
> +||*adblockerdetect.min.js^$domain=invitel.hu
URL is `https://www.invitel.hu/lakossagi/assets/js/adblockerdetect.min.js`
Better use full path or `/adblockerdetect.min.js$domain=invitel.hu`
`||*` and `^` are redundant here

2019-07-09 19:47 UTC, Alex-302 approved these changes

2019-07-09 19:47 UTC, merged