Fix #36397 itcafe.hu
AdguardTeam/AdguardFilters pull request #36445
Opened 2019-07-08 13:47 UTC by tvinzz

https://github.com/AdguardTeam/AdguardFilters/issues/36397

2019-07-08 16:25 UTC, BlazDT requested changes

2019-07-08 16:25 UTC, BlazDT commented on EnglishFilter/sections/css_extended.txt
> +itcafe.hu#?#div[class$="responsive-300px-600px"]:has( > h4:contains(/H*s/))
itcafe.hu##div[class$="responsive-300px-600px"]

Those two values are normal ad values, so it should be safe to use no ext-CSS.
FYI if a non-English site requires usage of ext-CSS rules, please put them into foreign.txt too.

2019-07-09 19:29 UTC, Alex-302 approved these changes

2019-07-10 19:16 UTC, BlazDT approved these changes

2019-07-10 19:16 UTC, merged