fix #35338 klusidee.nl
AdguardTeam/AdguardFilters pull request #36520
Opened 2019-07-09 10:47 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/35338

2019-07-09 20:40 UTC, Alex-302 requested changes

2019-07-09 20:40 UTC, Alex-302 commented on MobileFilter/sections/specific_web.txt
> +klusidee.nl##.top-ad-special.hide-mobile-top
`.hide-mobile-top` is unnecessary

2019-07-10 19:18 UTC, BlazDT approved these changes

2019-07-10 20:48 UTC, Alex-302 approved these changes

2019-07-10 20:49 UTC, merged