fix #36288 tokar.ua
AdguardTeam/AdguardFilters pull request #36543
Opened 2019-07-09 13:18 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/36288

2019-07-10 19:29 UTC, BlazDT requested changes

2019-07-10 19:29 UTC, BlazDT commented on AnnoyancesFilter/sections/popups.txt
> +tokar.ua##.under-header
Not hiding something for me.

2019-07-10 19:29 UTC, BlazDT commented on AnnoyancesFilter/sections/push-notifications.txt
> +tokar.ua##.bouncing-icon
To popups since it is always shown on the page (even though it is a link to their twitter).

2019-07-10 19:29 UTC, BlazDT commented on AnnoyancesFilter/sections/self-promo.txt
> +tokar.ua##.single-shr-wrapper
Rule to social (contains like buttons and other social like element).

2019-07-10 19:29 UTC, BlazDT commented on AnnoyancesFilter/sections/self-promo.txt
> +tokar.ua##.scl-sbsc
This section contains links to their social sites, so do not block.

2019-07-11 07:32 UTC, zloyden commented on AnnoyancesFilter/sections/popups.txt
> +tokar.ua##.under-header
<details><summary>Screenshot:</summary>

![Снимок экрана 2019-07-11 в 10 31 07](https://user-images.githubusercontent.com/33488229/61030919-1d7c1000-a3c7-11e9-8e57-24eee609e7a6.png)

</details><br/>

2019-07-11 08:10 UTC, slavaleleka approved these changes

2019-07-11 08:10 UTC, merged