fix #36285 obozrevatel.com
AdguardTeam/AdguardFilters pull request #36551
Opened 2019-07-09 14:19 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/36285

2019-07-09 14:49 UTC, slavaleleka requested changes
I'd rather consider `.widget-instagram` as non-popup subscription annoyance, and `.widget-facebook` as remains of social widgets

2019-07-09 14:59 UTC, slavaleleka commented
and one more thing

![Screenshot 2019-07-09 at 17 53 16](https://user-images.githubusercontent.com/45171506/60899448-2b208100-a273-11e9-9ee1-3ee4e00d062a.png)

@Alex-302 what do you think?

2019-07-09 21:18 UTC, Alex-302 commented
Yes, better fix it.

2019-07-10 20:41 UTC, Alex-302 approved these changes

2019-07-10 20:41 UTC, merged