fix #35737 sunexpress.com
AdguardTeam/AdguardFilters pull request #36878
Opened 2019-07-15 14:18 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/35737

2019-07-15 16:22 UTC, AdamWr approved these changes

2019-07-15 16:47 UTC, BlazDT approved these changes

2019-07-15 16:55 UTC, slavaleleka requested changes
unblock icons here please
![Screenshot 2019-07-15 at 19 54 45](https://user-images.githubusercontent.com/45171506/61233934-6f5fc580-a73a-11e9-9e75-6f0b60e7eeaa.png)

2019-07-15 17:00 UTC, BlazDT commented
@slavaleleka good catch :)

@zloyden For the filter search for e. g. icon-facebook in social/generic and add the domain there like the others already there.

2019-07-15 20:59 UTC, Alex-302 approved these changes

2019-07-15 20:59 UTC, Alex-302 commented
waiting for social buttons fix

2019-07-16 07:57 UTC, slavaleleka approved these changes

2019-07-16 08:11 UTC, merged