Fix #36851 aif.ua
AdguardTeam/AdguardFilters pull request #36873
Opened 2019-07-15 11:12 UTC by tvinzz

https://github.com/AdguardTeam/AdguardFilters/issues/36851

2019-07-15 21:07 UTC, Alex-302 requested changes

2019-07-15 21:07 UTC, Alex-302 commented on SocialFilter/sections/css_extended.txt
> +aif.ua#$?#.bordered_top:has(> .articl_tag ) { border-top: none!important; }
redundant rule

2019-07-16 07:46 UTC, tvinzz commented on SocialFilter/sections/css_extended.txt
> +aif.ua#$?#.bordered_top:has(> .articl_tag ) { border-top: none!important; }
I deleted redundant rule

2019-07-16 13:36 UTC, Alex-302 approved these changes

2019-07-16 13:36 UTC, merged