Fix #36848 24xxx.me
AdguardTeam/AdguardFilters pull request #36887
Opened 2019-07-15 15:52 UTC by tvinzz

https://github.com/AdguardTeam/AdguardFilters/issues/36848

2019-07-15 17:13 UTC, slavaleleka requested changes
I guess in this case we can add 
`||cdn-*.cdnbmb.com^$domain=24xxx.me`

2019-07-15 20:40 UTC, Alex-302 commented
and block VAST source - `u2bmco.com`

2019-07-15 20:41 UTC, Alex-302 requested changes
and block VAST source - `u2bmco.com`

2019-07-16 08:05 UTC, tvinzz commented
changed the first rule and blocked VAST

2019-07-16 13:35 UTC, Alex-302 requested changes

2019-07-16 13:35 UTC, Alex-302 commented on RussianFilter/sections/specific.txt
> +||u2bmco.com^$domain=24xxx.me
this is ad server

2019-07-18 07:38 UTC, tvinzz commented on RussianFilter/sections/specific.txt
> +||u2bmco.com^$domain=24xxx.me
moved u2bmco.com to adservers

2019-07-18 09:14 UTC, AdamWr approved these changes

2019-07-18 09:18 UTC, slavaleleka approved these changes

2019-07-18 09:18 UTC, merged