fix #35573 divamagazin.com
AdguardTeam/AdguardFilters pull request #36942
Opened 2019-07-16 12:22 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/35573

2019-07-16 13:25 UTC, Alex-302 requested changes

2019-07-16 13:25 UTC, Alex-302 commented on SocialFilter/sections/specific.txt
> +divamagazin.com###vitrin_ile_astro
looks like an ad

2019-07-16 13:25 UTC, Alex-302 commented on SocialFilter/sections/specific.txt
> +divamagazin.com###insta-celeb
block with script(domain specific)

2019-07-16 13:53 UTC, PentagramTr commented
`###insta-celeb`

This is the site's Instagram page.I think it should not be blocked.

https://kb.adguard.com/en/general/adguard-filter-policy#limitations-and-exceptions-2

```
Links to website’s communities in social networks are not blocked.
```

2019-07-16 14:43 UTC, PentagramTr commented
@zloyden 

I think you forgot this ad.Please check it.

<details><summary>Screenshot:</summary>

![divamagazin com](https://user-images.githubusercontent.com/34379403/61303879-ea83b300-a7f0-11e9-9d51-48b03e401a0b.png)

</details>

2019-07-16 15:05 UTC, zloyden commented
> @zloyden
> 
> I think you forgot this ad.Please check it.
> 
> Screenshot:

It wasn't showing on my side before. Thanks!

2019-07-18 15:59 UTC, Alex-302 approved these changes

2019-07-18 15:59 UTC, merged