fix #35449 haftasonu.com.tr
AdguardTeam/AdguardFilters pull request #36956
Opened 2019-07-16 15:00 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/35449

2019-07-16 15:41 UTC, BlazDT requested changes
Please also add this rule, else products with no #$# support cannot use the site:

haftasonu.com.tr#@##cadre_alert_cookies

2019-07-16 23:30 UTC, PentagramTr commented
@BlazDT 
@zloyden 

Rules only works desktop.Not working on iOS Safari.
<details><summary>Screenshot:</summary>

![IMG_5880](https://user-images.githubusercontent.com/34379403/61336641-bcc35c00-a83a-11e9-9c3b-dc4609e5786d.jpg)


</details>

2019-07-17 05:45 UTC, BlazDT commented
iOS does not have #$# support.

2019-07-17 05:45 UTC, BlazDT approved these changes

2019-07-18 09:09 UTC, AdamWr approved these changes

2019-07-18 13:14 UTC, slavaleleka approved these changes

2019-07-18 13:15 UTC, merged