Fix #37065 wylecz.to
AdguardTeam/AdguardFilters pull request #37075
Opened 2019-07-18 10:57 UTC by tvinzz

https://github.com/AdguardTeam/AdguardFilters/issues/37065

2019-07-18 12:22 UTC, AdamWr requested changes

2019-07-18 12:22 UTC, AdamWr commented on EnglishFilter/sections/foreign.txt
> +wylecz.to#?#.row > div > div > div > div:contains("REKLAMA")
It seems that some ads are not blocked by this rule - https://wylecz.to/badania-laboratoryjne/lipidogram/
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/61456251-df9e5f00-a965-11e9-9b32-ad25f887a013.png)

</details>

This rule should be okay:
`wylecz.to#?#.row div[class][style*="border-bottom:"][style*="max-height:"]:has(> div[style]:contains(REKLAMA))`

2019-07-19 09:13 UTC, tvinzz commented
rules changed according to @Alex-302 advise and moved to cookies-specific

2019-07-19 09:24 UTC, AdamWr approved these changes

2019-07-19 11:36 UTC, slavaleleka approved these changes

2019-07-19 11:36 UTC, merged