Fix #37074 vevobahis25.tv
AdguardTeam/AdguardFilters pull request #37102
Opened 2019-07-18 13:57 UTC by tvinzz

https://github.com/AdguardTeam/AdguardFilters/issues/37074

2019-07-18 16:58 UTC, Alex-302 requested changes

2019-07-18 16:58 UTC, Alex-302 commented on TurkishFilter/sections/specific.txt
> +vevobahis25.tv#$#.fancybox-enabled { overflow: visible!important; }
wrong section

2019-07-18 18:48 UTC, tvinzz commented on TurkishFilter/sections/specific.txt
> +vevobahis25.tv#$#.fancybox-enabled { overflow: visible!important; }
moved rule to general_extensions

2019-07-18 21:12 UTC, Alex-302 approved these changes

2019-07-19 08:03 UTC, slavaleleka approved these changes

2019-07-19 08:14 UTC, merged