fix #37175 pcpro100.info
AdguardTeam/AdguardFilters pull request #37267
Opened 2019-07-22 10:31 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/37175

2019-07-22 22:23 UTC, BlazDT requested changes
For left-over on desktop at top:

pcpro100.info#$#.top-line + .single.post { padding-top: 0px !important; }
pcpro100.info#$#.top-line { margin-bottom: 0px !important; }

2019-07-23 08:46 UTC, BlazDT approved these changes

2019-07-23 11:08 UTC, Alex-302 requested changes

2019-07-23 11:08 UTC, Alex-302 commented on RussianFilter/sections/general_extensions.txt
> +pcpro100.info#$#.top-line + .single.post { padding-top: 0px !important; }
please remove #$# rules. Paddings are not ad leftovers.

2019-07-23 11:15 UTC, Alex-302 approved these changes

2019-07-23 11:16 UTC, merged