fix #37179 windowsobraz.com
AdguardTeam/AdguardFilters pull request #37263
Opened 2019-07-22 09:56 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/37179

2019-07-22 22:14 UTC, BlazDT requested changes

2019-07-22 22:14 UTC, BlazDT commented on RussianFilter/sections/specific.txt
> +windowsobraz.com###dle-content > div[style="margin:30px;"] > a[onclick^="window.open"] > img
> img is not required in this case.

2019-07-23 08:46 UTC, BlazDT approved these changes

2019-07-23 11:14 UTC, Alex-302 approved these changes

2019-07-23 11:14 UTC, merged