fix #37170 ru.aorus.com
AdguardTeam/AdguardFilters pull request #37270
Opened 2019-07-22 11:14 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/37170

2019-07-22 22:28 UTC, BlazDT requested changes
Mobile cookie:
#policy-div-m

.social should be enough.

2019-07-23 07:48 UTC, zloyden commented
> Mobile cookie:
> #policy-div-m

Added, thanks!



> .social should be enough.

Not exactly, this rule also hide social-links from footer. This is enough for share `aorus.com##ul.social`.

2019-07-23 08:45 UTC, BlazDT approved these changes

2019-07-23 09:57 UTC, AdamWr approved these changes

2019-07-23 11:05 UTC, Alex-302 approved these changes

2019-07-23 11:05 UTC, merged