fix #37163 helpsetup.ru
AdguardTeam/AdguardFilters pull request #37276
Opened 2019-07-22 13:45 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/37163

2019-07-22 22:34 UTC, BlazDT requested changes
Also social buttons:
.uptl_container-share

2019-07-22 22:34 UTC, BlazDT commented on AnnoyancesFilter/sections/popups.txt
> +helpsetup.ru###popup__toggle
Please put rule also into Socialfilter/popups.txt

2019-07-23 08:45 UTC, BlazDT requested changes

2019-07-23 08:45 UTC, BlazDT commented on AnnoyancesFilter/sections/popups.txt
> -helpsetup.ru###popup__toggle
I meant to have the rule both in social and annoyances filter.

2019-07-23 09:15 UTC, BlazDT approved these changes

2019-07-23 11:54 UTC, Alex-302 approved these changes

2019-07-23 11:54 UTC, merged