fix #37283 vgtimes.ru
AdguardTeam/AdguardFilters pull request #37320
Opened 2019-07-23 12:22 UTC by tvinzz

https://github.com/AdguardTeam/AdguardFilters/issues/37283

2019-07-23 12:56 UTC, AdamWr requested changes

2019-07-23 12:56 UTC, AdamWr commented on RussianFilter/sections/specific.txt
> +||vgtimes.ru/engine/classes/min/index.php
It seems that this rule breaks website, for example "search" button doesn't work.

By the way, if I'm not wrong, they use some kind of anti-adblock script and display different ads for adblock users, these rules fix it on my end:
`vgtimes.ru#$#.adsbox#adfox_ { display: block!important; }`
`vgtimes.ru#%#AG_setConstant('adBlockEnabled', 'false');`

2019-07-23 15:42 UTC, AdamWr approved these changes

2019-07-24 14:34 UTC, Alex-302 approved these changes

2019-07-24 14:34 UTC, merged