fix #37366 turizmgunlugu.com
AdguardTeam/AdguardFilters pull request #37386
Opened 2019-07-24 10:29 UTC by tvinzz

https://github.com/AdguardTeam/AdguardFilters/issues/37366

2019-07-24 14:07 UTC, Alex-302 requested changes

2019-07-24 14:07 UTC, Alex-302 commented on TurkishFilter/sections/css_extended.txt
> +turizmgunlugu.com#?#.owl-carousel:has(a[target="_blank"])
dangerous rule. Make CSS selector(`.owl-carousel`) more specific.

2019-07-24 15:12 UTC, tvinzz commented
blocked owl-carousel script

2019-07-25 08:16 UTC, Alex-302 approved these changes

2019-07-25 08:16 UTC, Alex-302 commented on TurkishFilter/sections/css_extended.txt
> +turizmgunlugu.com#?#.owl-carousel:has(a[target="_blank"])
not a good solution, but it seems it is used for ads only)

2019-07-25 08:16 UTC, merged