fix #37419 rbc.ua
AdguardTeam/AdguardFilters pull request #37444
Opened 2019-07-25 11:28 UTC by tvinzz

https://github.com/AdguardTeam/AdguardFilters/issues/37419

2019-07-25 11:49 UTC, Alex-302 requested changes

2019-07-25 11:49 UTC, Alex-302 commented on AnnoyancesFilter/sections/annoyances.txt
> +rbc.ua##a.telegram-link[target="_blank"]
`[target="_blank"]` is redundant here

2019-07-26 08:35 UTC, tvinzz commented on AnnoyancesFilter/sections/annoyances.txt
> +rbc.ua##a.telegram-link[target="_blank"]
deleted redundant part

2019-07-30 21:38 UTC, Alex-302 commented on AnnoyancesFilter/sections/annoyances.txt
> +rbc.ua##a.telegram-link
tag is not necessary here

2019-07-31 07:41 UTC, tvinzz commented on AnnoyancesFilter/sections/annoyances.txt
> +rbc.ua##a.telegram-link
@Alex-302,
removed tag.

2019-07-31 09:48 UTC, Alex-302 approved these changes

2019-07-31 09:48 UTC, merged