fix #33009 nk.org.ua
AdguardTeam/AdguardFilters pull request #37688
Opened 2019-07-30 15:31 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/33009

2019-07-30 18:49 UTC, BlazDT requested changes
#ok_widget

2019-07-30 21:32 UTC, Alex-302 approved these changes

2019-07-30 21:33 UTC, Alex-302 commented
> #ok_widget

![image](https://user-images.githubusercontent.com/8361299/62166965-c1077300-b32a-11e9-8675-6eff6abece15.png)

2019-07-30 21:33 UTC, merged

2019-07-31 15:58 UTC, BlazDT commented
> > #ok_widget


For me it was bigger height and below it had other content yesterday, today the other content is gone, so no need to hide anymore.