fix #33017 cargurus.com
AdguardTeam/AdguardFilters pull request #37684
Opened 2019-07-30 14:25 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/33017

2019-07-30 18:46 UTC, BlazDT approved these changes

2019-07-30 21:48 UTC, Alex-302 requested changes

2019-07-30 21:48 UTC, Alex-302 commented on SpywareFilter/sections/specific.txt
> +||d3j1weegxvu8ns.cloudfront.net/*/t.js
in this case this domain can be blocked

2019-07-31 09:57 UTC, Alex-302 approved these changes

2019-07-31 09:58 UTC, merged