fix #33080 scdkey.com
AdguardTeam/AdguardFilters pull request #37738
Opened 2019-07-31 12:06 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/33080

2019-07-31 16:05 UTC, BlazDT approved these changes

2019-07-31 16:06 UTC, BlazDT commented on SpywareFilter/sections/specific.txt
> +||widget.trustpilot.com/*/v*/tp.widget.bootstrap.min.js
Unsure about this one though.

2019-08-01 09:17 UTC, Alex-302 requested changes

2019-08-01 09:17 UTC, Alex-302 commented on SpywareFilter/sections/specific.txt
> +||widget.trustpilot.com/*/v*/tp.widget.bootstrap.min.js
not a tracker

2019-08-05 18:09 UTC, Alex-302 approved these changes

2019-08-05 18:10 UTC, merged