fix #33587 hihbt.com
AdguardTeam/AdguardFilters pull request #37880
Opened 2019-08-02 12:33 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/33587

2019-08-02 15:29 UTC, BlazDT requested changes
Those CSS rules which has no comment were not reproduced.

2019-08-02 15:29 UTC, BlazDT commented on EnglishFilter/sections/css_extended.txt
> +hihbt.com#?#.theiaStickySidebar > .widget_custom_html:has(> div.textwidget > p[style] > a[href*="baa.im/"])
Move both to foreign too.

2019-08-02 15:29 UTC, BlazDT commented on EnglishFilter/sections/foreign.txt
> +hihbt.com##a[href*="66dage.com/"]
.single-content > p > a[target="_blank"]

2019-08-02 15:29 UTC, BlazDT commented on EnglishFilter/sections/foreign.txt
> +hihbt.com##a[href*="18sapp.com"]
.single-content > p > a[target="_blank"]

2019-08-02 15:29 UTC, BlazDT commented on EnglishFilter/sections/foreign.txt
> +hihbt.com##a[href*="baa.im/"]
.textwidget  > p a[target="_blank"][rel="noopener"]:not([href^="/"]). Please also exchange search parameter for ext-CSS rules.

2019-08-02 15:29 UTC, BlazDT commented on EnglishFilter/sections/foreign.txt
> +hihbt.com##a[href*="goen.win/"]
.textwidget  > p a[target="_blank"][rel="noopener"]:not([href^="/"]). Please also exchange search parameter for ext-CSS rules.

2019-08-06 12:30 UTC, Alex-302 approved these changes

2019-08-06 12:31 UTC, merged