fix #34068 hochu.tv
AdguardTeam/AdguardFilters pull request #38183
Opened 2019-08-07 11:33 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/34068
Branding 1xbet not reproduced but here I removed redirect from player when you click on play/pause. Also blocked push-notifications.

2019-08-07 13:35 UTC, BlazDT requested changes
||youtvonlinefree.com/foradu^

Stealth referrer on http://hochu.tv/fap-tv-compilation.html:
@@||cdntvnet.com/fap-tv-compilation.php$stealth

2019-08-07 13:35 UTC, BlazDT commented on AnnoyancesFilter/sections/push-notifications.txt
> +||selectroduced.com^$third-party
It is a fake push notification. Should be moved to adservers.

2019-08-07 13:35 UTC, BlazDT commented on RussianFilter/sections/general_extensions.txt
> +cdntvnet.com#%#window.open = function() { };
Was not working for me.

Should work though:
||cdntvnet.com/jquerymin18.js

2019-08-07 14:15 UTC, zloyden commented
Added `||youtvonlinefree.com/foradu/`.
For stealth-mode referrer I changed a bit rule because old version worked only on one category.
> Was not working for me.

That's strange. I checked these rules on extension and app - works fine on my side, but I change to your variant. `||cdntvnet.com/jquerymin18.js` is enough for block redirect.

2019-08-07 16:38 UTC, BlazDT approved these changes

2019-08-12 12:17 UTC, merged

2019-08-12 12:17 UTC, Alex-302 approved these changes