fix #38206 turbina.ru
AdguardTeam/AdguardFilters pull request #38222
Opened 2019-08-08 07:27 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/38206

2019-08-08 16:57 UTC, BlazDT approved these changes

2019-08-12 12:11 UTC, Alex-302 requested changes

2019-08-12 12:11 UTC, Alex-302 commented on RussianFilter/sections/general_extensions.txt
> +turbina.ru#%#AG_onLoad(function(){ AG_removeElementBySelector('#goodeLinks'); });
use CSS instead of JS

2019-08-12 12:51 UTC, zloyden commented on RussianFilter/sections/general_extensions.txt
> +turbina.ru#%#AG_onLoad(function(){ AG_removeElementBySelector('#goodeLinks'); });
Changed to CSS rule.

2019-08-12 13:25 UTC, Alex-302 approved these changes

2019-08-12 13:26 UTC, merged