fix #38418 imaginetricks.com
AdguardTeam/AdguardFilters pull request #38439
Opened 2019-08-12 10:07 UTC by tvinzz

https://github.com/AdguardTeam/AdguardFilters/issues/38418

2019-08-12 10:41 UTC, AdamWr requested changes

2019-08-12 10:41 UTC, AdamWr commented on EnglishFilter/sections/antiadblock.txt
> -her-sey.net,dostats.info,k2nblog.com,kolompc.us,tollypics.com,manatelugumovies.cc,mycumx.com,learningcrux.com,vqporn.com,readcomicsonline.ru,gmetrix.review,thichviet.site,megaurl.in,correotemporal.or
Unfortunately it doesn't work on my end.
There is no `eval`.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/62859249-e3bb6380-bcfc-11e9-8614-25c5cb16cba1.png)

</details>

So, I think that in this case we should add new rule, for example:
`imaginetricks.com$$script[tag-content="getElementById('babasbmsgx')"][min-length="5000"][max-length="20000"]`
or just
`imaginetricks.com$$script[tag-content="babasbmsgx"][min-length="5000"][max-length="20000"]`

It seems that `#%#//scriptlet("prevent-bab")` also doesn't work in this case.
This rule should fix it:
`imaginetricks.com#%#AG_abortInlineScript(/getElementById\('babasbmsgx'\)/, 'document.addEventListener');`

2019-08-12 13:00 UTC, Alex-302 commented on EnglishFilter/sections/antiadblock.txt
> -her-sey.net,dostats.info,k2nblog.com,kolompc.us,tollypics.com,manatelugumovies.cc,mycumx.com,learningcrux.com,vqporn.com,readcomicsonline.ru,gmetrix.review,thichviet.site,megaurl.in,correotemporal.or
please add new rules with a comment, because this script is different

2019-08-14 09:52 UTC, tvinzz commented on EnglishFilter/sections/antiadblock.txt
> -her-sey.net,dostats.info,k2nblog.com,kolompc.us,tollypics.com,manatelugumovies.cc,mycumx.com,learningcrux.com,vqporn.com,readcomicsonline.ru,gmetrix.review,thichviet.site,megaurl.in,correotemporal.or
@AdamWr, your rules work perfect, thank you.

2019-08-14 09:54 UTC, AdamWr approved these changes

2019-08-14 10:06 UTC, Alex-302 requested changes

2019-08-14 10:06 UTC, Alex-302 commented on EnglishFilter/sections/antiadblock.txt
> +imaginetricks.com#%#AG_abortInlineScript(/getElementById\('babasbmsgx'\)/, 'document.addEventListener');
better use scriptlet. JS rule will not be loaded in Opera and FF

2019-08-21 10:40 UTC, Alex-302 approved these changes

2019-08-21 11:31 UTC, Alex-302 approved these changes

2019-08-21 11:32 UTC, merged