fix agroreview.com https://forum.adguard.com/index.php?threads/https-…
AdguardTeam/AdguardFilters pull request #38519
Opened 2019-08-13 10:06 UTC by tvinzz

https://forum.adguard.com/index.php?threads/https-agroreview-com.34365/

2019-08-13 16:02 UTC, Alex-302 requested changes

2019-08-13 16:02 UTC, Alex-302 commented on RussianFilter/sections/css_extended.txt
> +agroreview.com#?#h2.block-title:contains(#Події)
not an ad

2019-08-13 16:02 UTC, Alex-302 commented on RussianFilter/sections/specific.txt
> +agroreview.com##.views-field-field-image > .field-content > a[rel="nofollow"][target="_blank"]
I see ad leftover with this rule

2019-08-14 08:32 UTC, slavaleleka approved these changes

2019-08-14 08:34 UTC, merged