fix od-news.com https://forum.adguard.com/index.php?threads/https-od-…
AdguardTeam/AdguardFilters pull request #38513
Opened 2019-08-13 09:21 UTC by tvinzz

https://forum.adguard.com/index.php?threads/https-od-news-com.34353/

2019-08-13 14:26 UTC, Alex-302 requested changes

2019-08-13 14:26 UTC, Alex-302 commented on RussianFilter/sections/antiadblock.txt
> +od-news.com#@##adsense
I don't see antiadblock.

2019-08-13 14:26 UTC, Alex-302 commented on RussianFilter/sections/antiadblock.txt
> +od-news.com#@##adsense
leftover:
![image](https://user-images.githubusercontent.com/8361299/62949682-4ee56280-bdef-11e9-89af-0901be1b0f8a.png)

2019-08-13 18:25 UTC, tvinzz commented on RussianFilter/sections/antiadblock.txt
> +od-news.com#@##adsense
> I don't see antiadblock.

![image](https://user-images.githubusercontent.com/15062885/62967037-e313f180-be10-11e9-91b1-8a9ae38a7be8.png)

2019-08-14 08:17 UTC, slavaleleka approved these changes

2019-08-14 08:18 UTC, merged