fix #37874 openssource.biz
AdguardTeam/AdguardFilters pull request #38587
Opened 2019-08-14 13:25 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/37874

2019-08-15 03:49 UTC, BlazDT approved these changes

2019-08-16 19:36 UTC, Alex-302 requested changes

2019-08-16 19:36 UTC, Alex-302 commented on RussianFilter/sections/css_extended.txt
> +openssource.biz#?##sidebar > div.widget:has(> div.textwidget a[target="_blank"]:not([href*="openssource.biz/"]):not([href="https://openssource.net"]):not([href="https://openssource.pro"]))
`:not([href^="https://openssource."])`
also this rule will block all links, which does not contain site address

2019-08-20 16:46 UTC, Alex-302 commented on RussianFilter/sections/css_extended.txt
> +openssource.biz#?##sidebar > div.widget:has(> div.textwidget a[target="_blank"]:not([href*="openssource.biz/"]):not([href="https://openssource.net"]):not([href="https://openssource.pro"]))
look:
![image](https://user-images.githubusercontent.com/8361299/63366803-2e834e00-c383-11e9-9c2a-86134e13d2a7.png)

2019-08-20 22:09 UTC, BlazDT approved these changes

2019-08-21 19:31 UTC, Alex-302 approved these changes

2019-08-21 20:02 UTC, merged