fix #38645 animefrenzy.net
AdguardTeam/AdguardFilters pull request #38665
Opened 2019-08-15 20:16 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/38645

2019-08-15 21:05 UTC, BlazDT approved these changes

2019-08-16 19:37 UTC, Alex-302 requested changes

2019-08-16 19:37 UTC, Alex-302 commented on AnnoyancesFilter/sections/widgets.txt
> +animefrenzy.net,sedsports.com,filmbioskop21.me,indoxxi.show,strikeout.nu,aniwatcher.com,mylivecricket.info##iframe[src*="chatango.com"]
make the same domains order in groups of the rules

2019-08-16 22:13 UTC, Alex-302 approved these changes

2019-08-16 22:26 UTC, closed without merging

2019-08-16 22:27 UTC, Alex-302 commented
many conflicts. Commited changes directly