fix #38249 thesaurus.com
AdguardTeam/AdguardFilters pull request #38874
Opened 2019-08-19 16:28 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/38249

2019-08-19 21:33 UTC, BlazDT requested changes

2019-08-19 21:33 UTC, BlazDT commented on AnnoyancesFilter/sections/antiadblock.txt
> +!+ PLATFORM(ext_ff, ext_opera, ios, ext_android_cb, ext_safari)
This rule is required in English/content_blocker too for ext_safari and iOS due to different adblocker modules. Also $domain=thesaurus.com is not required.

2019-08-20 07:29 UTC, BlazDT approved these changes

2019-08-20 16:24 UTC, Alex-302 commented on AnnoyancesFilter/sections/antiadblock.txt
> +@@||thesaurus.com/assets/ads.js
this rule can be added without hint

2019-08-20 16:24 UTC, Alex-302 approved these changes

2019-08-20 16:24 UTC, merged