fix #38789 tvfeed.in
AdguardTeam/AdguardFilters pull request #38896
Opened 2019-08-20 08:18 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/38789

2019-08-20 08:35 UTC, BlazDT approved these changes

2019-08-20 16:28 UTC, Alex-302 commented on AnnoyancesFilter/sections/antiadblock.txt
> +!+ PLATFORM(ext_ff, ext_opera, ext_android_cb)
Opera and FF support scriptlets. Is this rule required?

2019-08-21 19:59 UTC, Alex-302 requested changes

2019-08-21 19:59 UTC, Alex-302 commented on EnglishFilter/sections/content_blocker.txt
> +!+ PLATFORM(ext_safari, ios)
read the comment is filters chat

2019-08-22 18:52 UTC, merged