fix #38479 nastroisam.ru
AdguardTeam/AdguardFilters pull request #38902
Opened 2019-08-20 09:23 UTC by tvinzz

https://github.com/AdguardTeam/AdguardFilters/issues/38479

2019-08-20 16:51 UTC, Alex-302 requested changes

2019-08-20 16:51 UTC, Alex-302 commented on SocialFilter/sections/specific.txt
> +nastroisam.ru##.textwidget > a[target="_blank"][rel="nofollow"]
just block image

2019-08-21 09:39 UTC, tvinzz commented on SocialFilter/sections/specific.txt
> +nastroisam.ru##.textwidget > a[target="_blank"][rel="nofollow"]
@Alex-302,
blocked image by url

2019-08-21 19:52 UTC, Alex-302 approved these changes

2019-08-21 19:52 UTC, merged