fix #38262 myanianime.ru
AdguardTeam/AdguardFilters pull request #38900
Opened 2019-08-20 09:05 UTC by tvinzz

https://github.com/AdguardTeam/AdguardFilters/issues/38626

2019-08-20 09:26 UTC, BlazDT requested changes

2019-08-20 09:26 UTC, BlazDT commented on RussianFilter/sections/specific.txt
> +myanianime.ru##div[id^="adp_"]
Please also block iframe via url.

2019-08-20 10:13 UTC, tvinzz commented on RussianFilter/sections/specific.txt
> +myanianime.ru##div[id^="adp_"]
added to `adservers.txt`

2019-08-20 16:52 UTC, Alex-302 requested changes

2019-08-20 16:52 UTC, Alex-302 commented on SocialFilter/sections/specific.txt
> +||myanianime.ru/templates/newmyanianime/images/telegram.png
just link. Move to annoyances filter

2019-08-21 19:53 UTC, Alex-302 approved these changes

2019-08-21 19:53 UTC, merged