fix #38654 nissan.webstarterz.com
AdguardTeam/AdguardFilters pull request #38970
Opened 2019-08-21 13:32 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/38654

2019-08-21 13:47 UTC, BlazDT approved these changes

2019-08-21 19:37 UTC, Alex-302 requested changes

2019-08-21 19:37 UTC, Alex-302 commented on EnglishFilter/sections/content_blocker.txt
> +!+ PLATFORM(ext_safari, ios)
hints are not required. look on the directive

2019-08-22 18:45 UTC, Alex-302 approved these changes

2019-08-22 18:46 UTC, merged