fix #39097 ntsk.ru
AdguardTeam/AdguardFilters pull request #39376
Opened 2019-08-27 10:33 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/39097

2019-08-27 10:41 UTC, BlazDT approved these changes

2019-08-27 19:26 UTC, Alex-302 requested changes

2019-08-27 19:26 UTC, Alex-302 commented on RussianFilter/sections/specific.txt
> +ntsk.ru##.right > div.right-cell:not(.services)
better use `div[class="right-cell"]:not(.services)` instead of `div.right-cell:not(.services)` in this case

2019-08-28 19:34 UTC, Alex-302 approved these changes

2019-08-28 19:34 UTC, merged