fix #39165 iyinet.com
AdguardTeam/AdguardFilters pull request #39440
Opened 2019-08-28 10:47 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/39165

2019-08-28 17:14 UTC, BlazDT approved these changes

2019-08-28 19:32 UTC, Alex-302 requested changes

2019-08-28 19:32 UTC, Alex-302 commented on TurkishFilter/sections/specific.txt
> +$third-party,image,domain=iyinet.com
bad rule. This is forum, users can upload images from any source.
Better use something like that:
```
iyinet.com##.p-body-inner > center > a[title]:not([href^="https://iyinet.com/"]) > img[alt]
iyinet.com##.p-header-content > a[title]:not([href^="https://iyinet.com/"]) > img[alt]
```

2019-08-30 19:31 UTC, Alex-302 approved these changes

2019-08-31 09:38 UTC, merged