fix #39278 asyadizileri.net
AdguardTeam/AdguardFilters pull request #39589
Opened 2019-08-29 15:07 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/39278

2019-08-30 05:12 UTC, BlazDT requested changes

2019-08-30 05:12 UTC, BlazDT commented on EnglishFilter/sections/content_blocker.txt
> +asyadizileri.net#@#.reklam
Should be hidden in Turkish filter too normally.

Missed social:
##.paylas

2019-08-30 19:23 UTC, Alex-302 approved these changes

2019-08-31 09:41 UTC, merged

2021-01-15 22:04 UTC, muhasturk commented
should be investigate again
See.
https://github.com/AdguardTeam/AdguardFilters/issues/39278#issuecomment-761222530

2021-01-18 08:51 UTC, zloyden commented
Please, don't reply in old tasks. You should make a new report for the future. I also answered [here](https://github.com/AdguardTeam/AdguardFilters/issues/39278#issuecomment-762090326)