fix #39417 tanisgazetesi.com.tr
AdguardTeam/AdguardFilters pull request #39810
Opened 2019-09-02 14:04 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/39417

2019-09-02 14:27 UTC, BlazDT requested changes

2019-09-02 14:27 UTC, BlazDT commented on AnnoyancesFilter/sections/cookies_specific.txt
> +tanisgazetesi.com.tr##.sub-info
Better to merge domain to existing rule:
##.f-data-policy

2019-09-02 15:21 UTC, BlazDT approved these changes

2019-09-03 20:18 UTC, Alex-302 approved these changes

2019-09-03 20:20 UTC, merged