fix #39468 pembefilm.com
AdguardTeam/AdguardFilters pull request #39845
Opened 2019-09-03 07:43 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/39468

2019-09-03 11:11 UTC, BlazDT approved these changes

2019-09-03 20:17 UTC, Alex-302 requested changes

2019-09-03 20:17 UTC, Alex-302 commented on TurkishFilter/sections/specific.txt
> +||i.hizliresim.com/p56zga.jpg
better add to `://i.hizliresim.com^$domain=`

2019-09-04 19:12 UTC, Alex-302 approved these changes

2019-09-04 19:13 UTC, merged