fix #39536 torntube.com
AdguardTeam/AdguardFilters pull request #39907
Opened 2019-09-04 10:24 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/39536

2019-09-04 13:03 UTC, BlazDT requested changes

2019-09-04 13:03 UTC, BlazDT commented on TurkishFilter/sections/css_extended.txt
> +torntube.com#?#.wrap > h1[style]:has(> span:contains(TELEFONDA))
Rule with red text is enough, similar sites do not have any red text except the ads.

2019-09-04 13:28 UTC, BlazDT approved these changes

2019-09-04 19:07 UTC, Alex-302 commented on TurkishFilter/sections/adservers.txt
> +||hood.ninja^
this is not ad server. And why without `$third-party`

2019-09-07 18:42 UTC, BlazDT approved these changes

2019-09-09 11:50 UTC, Alex-302 approved these changes

2019-09-09 11:51 UTC, merged