fix #39603 fcinternews.it
AdguardTeam/AdguardFilters pull request #39967
Opened 2019-09-05 10:25 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/39603

2019-09-07 18:42 UTC, BlazDT requested changes

2019-09-07 18:42 UTC, BlazDT commented on EnglishFilter/sections/foreign.txt
> +fcinternews.it#?#.mx-auto:has(ins.adsbygoogle)
.mx-auto:has( > div >ins.adsbygoogle)

2019-09-07 19:12 UTC, zloyden commented
Changed a bit one ext-css rule and added new element which not shows on my side before.

2019-09-07 19:19 UTC, BlazDT approved these changes

2019-09-09 11:27 UTC, Alex-302 approved these changes

2019-09-09 11:27 UTC, merged