fix #39632 pornq.com
AdguardTeam/AdguardFilters pull request #39976
Opened 2019-09-05 12:56 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/39632

2019-09-07 17:42 UTC, BlazDT requested changes
Please modify the rule to

/poppy^$script,domain=pornq.com|upornia.com|hclips.com

For hclips we already have a specific rule which must be changed/removed.

https://upornia.com/videos/218962/judit-in-pornxn-video-fisting-beauties/?source=784232601&ad_tags=european

Also ad overlay.

upornia.com##.moralez

2019-09-07 18:14 UTC, zloyden commented
I made changes for pornq.com and hclips.com, also added `upornia.com##.moralez`.

2019-09-07 18:16 UTC, BlazDT approved these changes

2019-09-09 11:07 UTC, Alex-302 approved these changes

2019-09-09 11:07 UTC, merged