fix #39783 tomiks33.ru
AdguardTeam/AdguardFilters pull request #39993
Opened 2019-09-05 15:48 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/39783

2019-09-07 18:36 UTC, BlazDT requested changes
Social left-over:

##.index-follow

2019-09-07 18:56 UTC, zloyden commented
I was thinking of adding that element when I created pr. Thanks!

2019-09-07 19:18 UTC, BlazDT approved these changes

2019-09-09 11:02 UTC, Alex-302 approved these changes

2019-09-09 11:03 UTC, merged