fix #39672 pornl.com
AdguardTeam/AdguardFilters pull request #40056
Opened 2019-09-06 13:45 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/39672

2019-09-07 17:51 UTC, BlazDT requested changes

2019-09-07 17:51 UTC, BlazDT commented on AnnoyancesFilter/sections/push-notifications.txt
> +||sw.wpu.sh/script/main.js^$domain=pornl.com
Is not fixing notifications for me:

||pornl.com/ps/index.js

2019-09-07 18:09 UTC, BlazDT requested changes
And popunder on hclips.com

2019-09-07 19:17 UTC, BlazDT approved these changes

2019-09-07 19:18 UTC, BlazDT commented
And for hclips?

2019-09-07 19:20 UTC, zloyden commented
I just found a script which caused redirect. I will make a commit.

2019-09-07 19:26 UTC, BlazDT commented
Missed notification for hclips:
||sw.wpu.sh/script/main.js$domain=hclips.com

2019-09-07 19:30 UTC, zloyden commented
I also checked notification for hclips before made a commit - not reproduced, but I added it.

2019-09-07 19:47 UTC, BlazDT approved these changes

2019-09-09 10:58 UTC, Alex-302 approved these changes

2019-09-09 10:58 UTC, merged