fix #40323 lk21tv.com
AdguardTeam/AdguardFilters pull request #40378
Opened 2019-09-12 15:37 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/40323

2019-09-12 15:57 UTC, AdamWr requested changes
With AdGuard for Windows I see large empty spaces, like on a screenshot below.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/64799981-08b62700-d586-11e9-9649-eccc6276e5a9.png)

</details>

So please add also this rule:
```
lk21tv.com#$#a[href][rel="nofollow"] > img[src*="/ezgif-"] { position: absolute!important; keft: -3000px!important; }
```
and maybe `lk21tv.com#@#.img-responsive` to fix incorrect blocking by `ABPindo`.
<details><summary>Screenshot without rule</summary>

![image](https://user-images.githubusercontent.com/29142494/64800101-40bd6a00-d586-11e9-9fc2-804f61931b6e.png)

</details>

<details><summary>Screenshot with rule</summary>

![image](https://user-images.githubusercontent.com/29142494/64800139-4f0b8600-d586-11e9-8a9b-6bccc8ee8aa9.png)

</details>

2019-09-12 18:15 UTC, AdamWr requested changes

2019-09-13 07:14 UTC, AdamWr approved these changes

2019-09-13 20:45 UTC, Alex-302 approved these changes

2019-09-13 20:45 UTC, merged