fix #40565 ru.solverbook.com
AdguardTeam/AdguardFilters pull request #40590
Opened 2019-09-16 12:34 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/40565

2019-09-17 08:54 UTC, BlazDT requested changes

2019-09-17 08:54 UTC, BlazDT commented on RussianFilter/sections/css_extended.txt
> +ru.solverbook.com#?#.social > table:has(> tbody > tr > td:contains(Понравился сайт))
Social filter.

2019-09-17 09:06 UTC, BlazDT approved these changes

2019-09-18 18:42 UTC, Alex-302 requested changes

2019-09-18 18:42 UTC, Alex-302 commented on RussianFilter/sections/specific.txt
> +ru.solverbook.com##a[class*="-banner-"]
remove `ru.`

2019-09-23 08:31 UTC, Alex-302 approved these changes

2019-09-23 08:32 UTC, merged