fix #40434 ero.motaen.com
AdguardTeam/AdguardFilters pull request #40656
Opened 2019-09-17 11:12 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/40434

2019-09-17 23:18 UTC, BlazDT approved these changes

2019-09-18 18:50 UTC, Alex-302 requested changes

2019-09-18 18:50 UTC, Alex-302 commented on EnglishFilter/sections/specific.txt
> +||cdsbnrs.com^$domain=motaen.com
this is ad server
https://www.istripper.com/mailing/custom/adblocks_affiliates082019

2019-09-21 16:21 UTC, Alex-302 approved these changes

2019-09-21 16:21 UTC, merged