fix #40396 m.xigua110.com
AdguardTeam/AdguardFilters pull request #40729
Opened 2019-09-18 15:50 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/40396

2019-09-18 18:54 UTC, Alex-302 requested changes

2019-09-18 18:54 UTC, Alex-302 commented on EnglishFilter/sections/foreign.txt
> +m.xigua110.com##.ui-detail-info > div[style]
use more specific style - at least `line-height:35px; text-align:center;`

2019-09-19 10:58 UTC, BlazDT approved these changes

2019-09-20 10:39 UTC, Alex-302 approved these changes

2019-09-20 10:39 UTC, merged