added exception for money.yandex.ru/kz/by/ua
AdguardTeam/AdguardFilters pull request #40768
Opened 2019-09-19 09:12 UTC by tvinzz

https://github.com/AdguardTeam/AdguardFilters/issues/32997

The scriptlets for pogoda.yandex.ru/kz/by/ua were braking the money.yandex.ru/kz/by/ua, so I had to add the exception rules.

2019-09-19 10:41 UTC, BlazDT approved these changes

2019-09-19 10:42 UTC, zloyden approved these changes

2019-09-19 10:46 UTC, slavaleleka approved these changes

2019-09-19 18:34 UTC, Alex-302 requested changes

2019-09-19 18:34 UTC, Alex-302 commented on AnnoyancesFilter/sections/annoyances.txt
> +! https://github.com/AdguardTeam/AdguardFilters/issues/32997
better add `~domain` to original rules. In this case.

2019-09-20 18:27 UTC, Alex-302 approved these changes

2019-09-20 18:27 UTC, merged