fix #41057 coachmag.co.uk
AdguardTeam/AdguardFilters pull request #41066
Opened 2019-09-24 09:17 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/41057

2019-09-24 14:11 UTC, BlazDT requested changes
Adblock not reproduced, but cookie reproduced (likely AdBlock is also caused by Sourcepoint which is blocked by the following rules):

||coachmag.co.uk/misc/advagg_js/msg
||coachmag.co.uk/sites/coachmag/files/advagg_js/js

2019-09-24 16:55 UTC, BlazDT commented
Why not block sourcepoint?

2019-09-24 16:56 UTC, Alex-302 commented
and social share
![image](https://user-images.githubusercontent.com/8361299/65532934-668f2b00-df05-11e9-8ea4-5436d9a97f64.png)

2019-09-25 21:12 UTC, Alex-302 approved these changes

2019-09-25 21:15 UTC, merged