fix #41496 coinhub.pw
AdguardTeam/AdguardFilters pull request #41530
Opened 2019-10-01 11:45 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/41496

2019-10-01 17:05 UTC, BlazDT requested changes

2019-10-01 17:05 UTC, BlazDT commented on AnnoyancesFilter/sections/antiadblock.txt
> +coinhub.pw#?#body > center:contains(Turn off your adblocker)
ext-CSS

2019-10-01 18:34 UTC, Alex-302 commented on AnnoyancesFilter/sections/antiadblock.txt
> +coinhub.pw#?#body > center:contains(Turn off your adblocker)
what is wrong?

2019-10-08 20:33 UTC, Alex-302 approved these changes

2019-10-08 20:51 UTC, Alex-302 requested changes

2019-10-08 20:51 UTC, Alex-302 commented on EnglishFilter/sections/antiadblock.txt
> +coinhub.pw,phys-kids.com,simple-devices.ru,javjack.com,btcleets.xyz,xko.red,5urokov.ru,cpopchanelofficial.com,satoshimonster.com,capage.in,okcaller.com,satoshihero.com,yhocdata.com,1000ps.at,mexa.sh,
this rule causes adblock detection with disabled filters.
This rule also required `#%#//scriptlet('abort-current-inline-script', 'adBlockNotDetected', '/FuckAdBlock/')`

2019-10-09 09:25 UTC, zloyden commented
I will make a new pr because there is a lot of changes.

2019-10-09 09:25 UTC, closed without merging