fix #42090 dailyhive.com
AdguardTeam/AdguardFilters pull request #42123
Opened 2019-10-10 14:31 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/42090

2019-10-11 07:12 UTC, BlazDT requested changes

2019-10-11 07:12 UTC, BlazDT commented on EnglishFilter/sections/specific.txt
> +dailyhive.com##.top
.sidebar.top

2019-10-13 14:44 UTC, Alex-302 commented on EnglishFilter/sections/specific.txt
> +dailyhive.com##.sidebar.top
not sure about it. Check images size at left side.

2019-10-14 19:49 UTC, Alex-302 approved these changes

2019-10-14 19:50 UTC, merged