fix #42170 chrysanthemumgarden.com
AdguardTeam/AdguardFilters pull request #42171
Opened 2019-10-11 13:59 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/42170

2019-10-11 16:08 UTC, BlazDT requested changes

2019-10-11 16:08 UTC, BlazDT commented on EnglishFilter/sections/specific.txt
> +||qlkms.ga^$domain=chrysanthemumgarden.com
Looks more like adserver to me.

2019-10-13 12:47 UTC, BlazDT approved these changes

2019-10-13 14:22 UTC, Alex-302 approved these changes

2019-10-13 14:22 UTC, merged