fix #42093 qaru.site
AdguardTeam/AdguardFilters pull request #42492
Opened 2019-10-17 08:36 UTC by zloyden

https://github.com/AdguardTeam/AdguardFilters/issues/42093#issuecomment-543055547

2019-10-17 09:32 UTC, BlazDT approved these changes

2019-10-18 12:47 UTC, Alex-302 requested changes

2019-10-18 12:47 UTC, Alex-302 commented on RussianFilter/sections/specific.txt
> +||cloudfront.net^$domain=allfon.org|allfon.pro|allfon.xyz|batpic.com|kinovideo.tv|mintmanga.com|mobzon.ru|qaru.site
too wide rule.  cloudfront.net is not ad server. Better block `||d1uw69x4c2zrim.cloudfront.net^`

2019-10-18 16:20 UTC, Alex-302 approved these changes

2019-10-18 16:20 UTC, merged