extra #34 gazeta.ru
AdguardTeam/AdguardFilters pull request #43241
Opened 2019-10-30 22:31 UTC by tvinzz

https://github.com/AdguardTeam/AdGuardExtra/issues/34

2019-10-31 08:12 UTC, zloyden approved these changes

2019-11-04 16:16 UTC, Alex-302 requested changes
а остальные домены?

2019-11-05 08:04 UTC, merged

2019-11-05 15:43 UTC, Alex-302 commented
@tvinzz

2019-11-05 22:04 UTC, Alex-302 commented
@tvinzz