extra #45 my.mail.ru
AdguardTeam/AdguardFilters pull request #44789
Opened 2019-11-25 21:55 UTC by tvinzz

https://github.com/AdguardTeam/AdGuardExtra/issues/45

2019-11-25 21:59 UTC, Alex-302 approved these changes

2019-11-25 21:59 UTC, Alex-302 requested changes

2019-11-25 21:59 UTC, Alex-302 commented on RussianFilter/sections/antiadblock.txt
> +my.mail.ru#%#//scriptlet("abort-on-property-read", "Object.prototype.isFixedRightEnable")
to Annoyances

2019-11-27 07:29 UTC, zloyden approved these changes

2019-11-27 07:29 UTC, merged