fix #44845 stfly.io
AdguardTeam/AdguardFilters pull request #44848
Opened 2019-11-26 15:01 UTC by Sergey-Lyapin

#44845

2019-11-27 16:30 UTC, AdamWr requested changes
Please also add rules to block ad and popups.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/69741347-2f264000-113b-11ea-80d2-97f28202dae5.png)

</details>

For example:
`stfly.io##.banner-inner` (to `specific.txt`, there is already similar rule)
and for popups, something like (to `general_extensions.txt`):
```
!+ NOT_PLATFORM(windows, mac, android)
stfly.io#%#//scriptlet("abort-on-property-read", "tabUnder")
!+ PLATFORM(windows, mac, android)
stfly.io#%#AG_abortOnPropertyRead('tabUnder');
```

2019-11-28 10:26 UTC, AdamWr approved these changes

2019-11-28 10:26 UTC, zloyden approved these changes

2019-11-28 10:27 UTC, Sergey-Lyapin commented
done
@AdamWr check it please

2019-11-28 10:30 UTC, merged