fix #44836 official-amtemu.com
AdguardTeam/AdguardFilters pull request #44842
Opened 2019-11-26 13:12 UTC by Sergey-Lyapin

#44836

2019-11-26 13:21 UTC, zloyden requested changes

2019-11-26 13:21 UTC, zloyden commented on EnglishFilter/sections/css_extended.txt
> +official-amtemu.com##aside.sidebar > div.theiaStickySidebar > div#text-html-widget-2:has(div > ins.adsbygoogle)
It's better re-write rule to this `official-amtemu.com##.theiaStickySidebar > div.widget:has(> div > ins.adsbygoogle)`

2019-11-26 14:41 UTC, zloyden approved these changes

2019-11-27 16:19 UTC, AdamWr approved these changes

2019-11-27 16:19 UTC, merged