fix #44840 neemias.info
AdguardTeam/AdguardFilters pull request #44854
Opened 2019-11-26 17:24 UTC by Sergey-Lyapin

#44840

2019-11-27 18:58 UTC, Alex-302 requested changes

2019-11-27 18:58 UTC, Alex-302 commented on SpanishFilter/sections/specific.txt
> +||*.wp.com/afiliados.hostgator.com.br^$domain=neemias.info
убери `.*` или палки. `||wp.` достаточно

2019-11-27 18:58 UTC, Alex-302 commented on SpanishFilter/sections/specific.txt
> +neemias.info###text-7
пустой элемент вроде.

2019-11-27 18:58 UTC, Alex-302 commented on SpanishFilter/sections/specific.txt
> +neemias.info###text-7
`||magazinevoce.com.br/js/banner.js`
и рекламный скрипт пропустил

2019-11-28 10:49 UTC, Sergey-Lyapin commented on SpanishFilter/sections/specific.txt
> +neemias.info###text-7
> пустой элемент вроде.

Это огрызок от рекламы, убрал его, чтобы смотрелось лучше

2019-11-29 17:28 UTC, Alex-302 approved these changes

2019-11-29 17:28 UTC, merged