fix #44910 rick-and-morty.online
AdguardTeam/AdguardFilters pull request #44918
Opened 2019-11-27 10:12 UTC by Sergey-Lyapin

#44910

2019-11-27 18:35 UTC, Alex-302 requested changes

2019-11-27 18:35 UTC, Alex-302 commented on EnglishFilter/sections/content_blocker.txt
> +@@||rick-and-morty.online/wp-content/plugins/*/assets/js/showads.js$domain=rick-and-morty.online
тут полный адрес нужен, будет видно для какого антиадблочного скрипта он

2019-11-27 18:35 UTC, Alex-302 commented on RussianFilter/sections/antiadblock.txt
> +rick-and-morty.online#%#window.DHAntiAdBlocker = true
вместо JS нужно использовать скриптлет. 
Ну и эти правила не в том фильтре - это раздражитель, т.к. можно закрыть

2019-11-27 18:35 UTC, Alex-302 commented on RussianFilter/sections/specific.txt
> +rick-and-morty.online##.td-all-devices
это не вижу в коде. Что скрывает?

2019-11-27 18:50 UTC, Alex-302 commented on RussianFilter/sections/specific.txt
> +rick-and-morty.online##.td-all-devices
ещё рекламный домен пропустил - `2tdsprofit.in`(добавил в фильтр)

2019-11-28 11:33 UTC, Sergey-Lyapin commented on RussianFilter/sections/antiadblock.txt
> +rick-and-morty.online#%#window.DHAntiAdBlocker = true
Закрыть можно, тогда перестают отображаться картинки в некоторых местах, например в новостях

2019-11-29 17:31 UTC, Alex-302 requested changes

2019-11-29 17:31 UTC, Alex-302 commented on AnnoyancesFilter/sections/antiadblock.txt
> +@@||rick-and-morty.online/wp-content/plugins/*/assets/js/showads.js$domain=rick-and-morty.online
это правило уже не нужно. Добавили общее исключение.

2019-12-02 14:21 UTC, Sergey-Lyapin commented on RussianFilter/sections/specific.txt
> +rick-and-morty.online##.td-all-devices
Это реклама, ведет на сторонний интернет-магазин
![Screenshot 2019-12-02 at 17 15 27](https://user-images.githubusercontent.com/18536328/69966737-0d0c3380-1528-11ea-902a-8dd137ca545c.png)

2019-12-02 14:25 UTC, Alex-302 approved these changes

2019-12-02 14:26 UTC, merged