fix #46246 automobilemagazine.com.tr
AdguardTeam/AdguardFilters pull request #46253
Opened 2019-12-19 12:13 UTC by Sergey-Lyapin

#46246

2019-12-22 17:12 UTC, Alex-302 requested changes
make more specific rules

2019-12-22 17:12 UTC, Alex-302 commented on TurkishFilter/sections/specific.txt
> +automobilemagazine.com.tr##.td-single-image-
bad rules

2019-12-25 17:09 UTC, krystian3w approved these changes

2019-12-26 14:12 UTC, Alex-302 approved these changes

2019-12-26 14:12 UTC, merged