beat.rambler.ru: fixed leftover
AdguardTeam/AdguardFilters pull request #47838
Opened 2020-01-15 11:07 UTC by Sergey-Lyapin

2020-01-15 18:44 UTC, Alex-302 requested changes

2020-01-15 18:44 UTC, Alex-302 commented on RussianFilter/sections/css_extended.txt
> +beat.rambler.ru#?##app > div[class] > div[class] > div[class] > div:has(> div:contains(реклама))
selector is obsolete

2020-01-15 19:31 UTC, Sergey-Lyapin commented on RussianFilter/sections/css_extended.txt
> +beat.rambler.ru#?##app > div[class] > div[class] > div[class] > div:has(> div:contains(реклама))
Why? The rule still works on my device

2020-01-16 09:51 UTC, Alex-302 approved these changes

2020-01-16 09:51 UTC, merged