fix #49080 fashionwaltz.com
AdguardTeam/AdguardFilters pull request #49186
Opened 2020-02-04 10:22 UTC by Sergey-Lyapin

2020-02-10 17:47 UTC, Alex-302 requested changes

2020-02-10 17:47 UTC, Alex-302 commented on SocialFilter/sections/css_extended.txt
> +fashionwaltz.com#?##sidebar-2 > div.widget:has(> div.textwidget > div#newsletter_form)
to annoyances

2020-02-11 09:08 UTC, zloyden requested changes

2020-02-11 09:08 UTC, zloyden commented on EnglishFilter/sections/foreign.txt
> +fashionwaltz.com##div[style*="margin-top:20px;"][style*="text-align:center;"]
Change a bit second rule to this `fashionwaltz.com##.entry-content > div.copyright ~ div[style*="text-align:center;"]`

2020-02-11 09:08 UTC, zloyden commented on AnnoyancesFilter/sections/annoyances.txt
> +fashionwaltz.com#?##sidebar-2 > div.widget:has(> div.textwidget > div#newsletter_form)
I guess you can exchange this part`#sidebar-2` to `.pull-left`. Also for social ext-css rule.

2020-02-11 09:12 UTC, zloyden approved these changes

2020-02-11 09:12 UTC, merged