fix #49892 theandroidpro.com
AdguardTeam/AdguardFilters pull request #50222
Opened 2020-02-21 09:48 UTC by Sergey-Lyapin

#49892

2020-02-21 10:01 UTC, zloyden reviewed
А контент блокеры?

2020-02-25 18:17 UTC, Alex-302 commented on EnglishFilter/sections/antiadblock.txt
> +theandroidpro.com,kodvizit.com,guzelresimler.info,download.mokeedev.com,mangahosted.com,123link.biz,inmanga.com,1004lucifer.blogspot.com,mshare.io,wikiall.org,eskago.pl,streamcloud.eu#@%#//scriptlet(
а это зачем? Ты же добавляешь этот домен в скриптлетное правило ниже.

2020-02-25 18:20 UTC, Alex-302 requested changes

2020-02-25 18:20 UTC, Alex-302 commented on EnglishFilter/sections/content_blocker.txt
> +@@||cdn.intergi.com/*/js/libs/cmg-prebid-*.new.js$domain=coolmathgames.
Зачем домен верхнего уровня удалил?

2020-02-26 07:40 UTC, Sergey-Lyapin commented on EnglishFilter/sections/content_blocker.txt
> +@@||cdn.intergi.com/*/js/libs/cmg-prebid-*.new.js$domain=coolmathgames.
упс, случайно

2020-02-26 07:47 UTC, Sergey-Lyapin commented on EnglishFilter/sections/antiadblock.txt
> +theandroidpro.com,kodvizit.com,guzelresimler.info,download.mokeedev.com,mangahosted.com,123link.biz,inmanga.com,1004lucifer.blogspot.com,mshare.io,wikiall.org,eskago.pl,streamcloud.eu#@%#//scriptlet(
Скриптлетное правило вызывает обнаружение адблока, добавил туда потому что там во всех правилах должен быть одинаковый список доменов, предыдущие домены в этом правиле так же добавлены

2020-02-26 21:54 UTC, Alex-302 commented on EnglishFilter/sections/antiadblock.txt
> +theandroidpro.com,kodvizit.com,guzelresimler.info,download.mokeedev.com,mangahosted.com,123link.biz,inmanga.com,1004lucifer.blogspot.com,mshare.io,wikiall.org,eskago.pl,streamcloud.eu#@%#//scriptlet(
для таких случаев есть секция для KillAdBlock, правила CSS и исключения одинаковые

2020-02-27 08:22 UTC, Sergey-Lyapin commented on EnglishFilter/sections/antiadblock.txt
> +theandroidpro.com,kodvizit.com,guzelresimler.info,download.mokeedev.com,mangahosted.com,123link.biz,inmanga.com,1004lucifer.blogspot.com,mshare.io,wikiall.org,eskago.pl,streamcloud.eu#@%#//scriptlet(
Перенес домен

2020-02-27 08:24 UTC, zloyden requested changes

2020-02-27 08:24 UTC, zloyden commented on EnglishFilter/sections/antiadblock.txt
> +@@||cdn.jsdelivr.net/npm/fuckadblock@3.2.1/fuckadblock.min.js$domain=theandroidpro.com
`fuckadblock@3.2.1` лучше заменить на `*`

2020-02-27 09:49 UTC, zloyden approved these changes

2020-02-27 09:54 UTC, merged