fix #50245 nurdanhaber.com
AdguardTeam/AdguardFilters pull request #50529
Opened 2020-02-26 16:35 UTC by Sergey-Lyapin

#50245

2020-02-26 22:23 UTC, zloyden requested changes

2020-02-26 22:23 UTC, zloyden commented on TurkishFilter/sections/specific.txt
> +nurdanhaber.com###haberAlani > div.detayBaslik + div[style*="width: 100%"][style*="float: left"]
Лучше уточнить до скрываемого изображения.

2020-02-27 18:51 UTC, Alex-302 commented on TurkishFilter/sections/specific.txt
> +nurdanhaber.com###haberAlani > div.detayBaslik + div[style*="width: 100%"][style*="float: left"]
до `div[style*="width: 728px"]` можно. 728 - популярный размер баннеров

2020-02-27 18:52 UTC, Alex-302 approved these changes

2020-02-27 18:52 UTC, merged