fix #50914 tafdi.org
AdguardTeam/AdguardFilters pull request #50971
Opened 2020-03-05 10:46 UTC by Sergey-Lyapin

#50914

2020-03-05 11:21 UTC, zloyden requested changes

2020-03-05 11:21 UTC, zloyden commented on AnnoyancesFilter/sections/popups.txt
> +tafdi.org#%#//scriptlet("set-constant", "yenigeliyor", "noopFunc")
Не в ту секцию занес скриптлет, да и попап можно прибить без него.

2020-03-05 19:49 UTC, zloyden requested changes

2020-03-05 19:49 UTC, zloyden commented on TurkishFilter/sections/specific.txt
> +||asdqweq.com/tafdi.js
Есть еще похожие правила с этим доменом. Посмотри, как можно его улучшить.

2020-03-06 09:19 UTC, zloyden commented on TurkishFilter/sections/specific.txt
> +||asdqweq.com^$script,domain=dizimex.net|morfilmizle.com|tafdi.org
Это безопасный вариант, но его лучше перенести в `adservers` с `$third-party`.

2020-03-06 15:24 UTC, Alex-302 approved these changes

2020-03-06 15:26 UTC, merged