fix #50920 dizison.pw
AdguardTeam/AdguardFilters pull request #50979
Opened 2020-03-05 13:52 UTC by Sergey-Lyapin

#50920

2020-03-06 15:31 UTC, Alex-302 requested changes

2020-03-06 15:31 UTC, Alex-302 commented on TurkishFilter/sections/specific.txt
> +dizison.pw##img[alt="BETPAS ÜYELİK"]
чего не `dizison.pw##.st_ad`?

2020-03-06 15:31 UTC, Alex-302 commented on TurkishFilter/sections/specific.txt
> +dizison.pw##img[alt="BETPAS ÜYELİK"]
i.imgyukle.com можно добавить к `||i.imgyukle.com^$domain=selcuksportshd22.live`

2020-03-06 15:31 UTC, Alex-302 commented on TurkishFilter/sections/specific.txt
> +dizison.pw##body > div[style*="position:relative"][style*="width:100%"]
не пойму для чего. Вроде высота 0

2020-03-06 15:31 UTC, Alex-302 commented on TurkishFilter/sections/specific.txt
> +||dizison.pw/*losev.gif
зачем `*`?

2020-03-10 08:46 UTC, Sergey-Lyapin commented on TurkishFilter/sections/specific.txt
> +dizison.pw##body > div[style*="position:relative"][style*="width:100%"]
Там внутри ссылка рекламная лежит, она на весь фон

2020-03-12 13:23 UTC, Alex-302 approved these changes

2020-03-12 13:24 UTC, merged