fix #51401 q32.ru
AdguardTeam/AdguardFilters pull request #51435
Opened 2020-03-13 12:54 UTC by Sergey-Lyapin

#51401

2020-03-13 13:15 UTC, zloyden requested changes

2020-03-13 13:15 UTC, zloyden commented on RussianFilter/sections/antiadblock.txt
> +@@||q32.ru/themes/default/reklama/advertising.js
Здесь можно применить скриптлет, а для не поддерживающих его платформ это правило перенести в соответствующую секцию.

2020-03-16 22:21 UTC, Alex-302 commented on RussianFilter/sections/antiadblock.txt
> +@@||q32.ru/themes/default/reklama/advertising.js
Да и так нормально. Усложнять во многих ситуациях тоже не стоит.

2020-03-16 22:21 UTC, Alex-302 approved these changes

2020-03-16 22:21 UTC, merged