fix #52224 anime.anidub.life
AdguardTeam/AdguardFilters pull request #52323
Opened 2020-03-27 09:28 UTC by Sergey-Lyapin

#52224

2020-03-29 19:18 UTC, Alex-302 commented
проверь, нужны ли правила для anidub.com

2020-03-30 07:54 UTC, Sergey-Lyapin commented
> проверь, нужны ли правила для anidub.com

Эти правила из русского фильтра можно исключить, два рекламных домена внизу скорее всего мертвые (не пингуются). 
```
||online.anidub.com/player/vast.php$redirect=noopvast-3.0
anidub.com##.branding
anidub.com##.left-banner
anidub.com##.top_one ~ div:empty + div[id]:not([class])
anidub.com##.top_one ~ script ~ div[id] > style + a[onclick]
anidub.com##body > a
||anidub.com/uploads/fotos/*brand.html
||online.anidub.com/templates/Anidub_online/L2anidub*.jpg
||mxttrf.com/vast.xml
||n278adserv.com/vast.xml
```

2020-03-30 17:47 UTC, Alex-302 commented
> Эти правила можно исключить,

все не актуальные? 



> два рекламных домена внизу скорее всего мертвые

пока пусть будут. Я именно про правила для этого сайта интересовался.

2020-03-31 08:05 UTC, Sergey-Lyapin commented
> все не актуальные?

Я их всех исключил и проверил везде, прошелся по всем страницам - исключения ни разу не сработали (и визуально ничего не изменилось).
Судя по скринам из старых заявок они полностью поменяли дизайн сайта.

2020-04-06 12:42 UTC, Alex-302 requested changes

2020-04-06 12:42 UTC, Alex-302 commented on SocialFilter/sections/css_extended.txt
> +anidub.com##.sidebar > div.block:has(> div#vk_groups > iframe[src^="https://vk.com/widget_community.php"])
`#?#`

2020-04-08 12:32 UTC, Alex-302 approved these changes

2020-04-08 12:32 UTC, merged