fix #52261 halklailiskiler.com.tr
AdguardTeam/AdguardFilters pull request #52339
Opened 2020-03-27 12:58 UTC by Sergey-Lyapin

#52261

2020-03-27 13:03 UTC, Alex-302 requested changes

2020-03-27 13:03 UTC, Alex-302 commented on TurkishFilter/sections/specific.txt
> +||halklailiskiler.com.tr/images/uploads/ad*.gif
too wide. Better regeex `ad+number`

2020-03-27 14:29 UTC, zloyden commented on TurkishFilter/sections/specific.txt
> +/\/images\/uploads\/ad[0-9][0-9][0-9][0-9].(gif)/$domain=halklailiskiler.com.tr,image
It's better to impove it to this `/halklailiskiler\.com\.tr\/images\/uploads\/ad[0-9]+\.gif/`

2020-03-30 17:22 UTC, Alex-302 approved these changes

2020-03-30 17:22 UTC, merged