fix #53007 riamo.ru
AdguardTeam/AdguardFilters pull request #53118
Opened 2020-04-07 15:17 UTC by Sergey-Lyapin

#53007

Эти исключения чинят подгрузку новых статей при прокрутке.

2020-04-07 15:36 UTC, zloyden requested changes

2020-04-07 15:36 UTC, zloyden commented on SpywareFilter/sections/whitelist.txt
> +@@||googletagmanager.com/gtag/js?id=$domain=riamo.ru
Не нужно `?id=`

2020-04-08 13:27 UTC, Alex-302 commented on SpywareFilter/sections/whitelist.txt
> +@@||googletagmanager.com/gtag/js?id=$domain=riamo.ru
Да и так можно. Других вариантов там нет. Для однообразия разве что.
@Sergey-Lyapin сделай как у аналогичных исключений.

2020-04-08 14:34 UTC, Sergey-Lyapin commented on SpywareFilter/sections/whitelist.txt
> +@@||googletagmanager.com/gtag/js?id=$domain=riamo.ru
@Alex-302  Мне просто твое правило на глаза попалось, хотел сделать исключение как можно уже
`@@||googletagmanager.com/gtag/js?id=$domain=chainreactioncycles.com`

2020-04-08 14:39 UTC, zloyden approved these changes

2020-04-08 14:39 UTC, merged