fix #54138 newsrated-kino.info
AdguardTeam/AdguardFilters pull request #54277
Opened 2020-04-23 17:38 UTC by Sergey-Lyapin

#54138

2020-04-24 14:03 UTC, zloyden requested changes

2020-04-24 14:03 UTC, zloyden commented on RussianFilter/sections/specific.txt
> +newsrated-kino.info##.dnmoduly-load-vk
У меня еще осталась реклама, как вариант можно убрать этим правилом вместо выше двух `newsrated-kino.info##a[href^="https://newsrated-kino.info/engine/go.php?url="]`

2020-04-24 17:35 UTC, Sergey-Lyapin commented on RussianFilter/sections/specific.txt
> +newsrated-kino.info##.dnmoduly-load-vk
Я не нашел там кнопку, по которой можно скачать торрент-файл, поэтому оставил ссылки на скачивание менеджера закачек (Download Studio), в этой проге можно скачивать фильмы. Если их тоже удалить, то тогда с этого сайта вообще ничего нельзя будет скачать)

2020-04-27 08:24 UTC, zloyden commented on RussianFilter/sections/specific.txt
> +newsrated-kino.info##.dnmoduly-load-vk
Ок, сегодня у сайта никаких изменений не вижу и нет варианта скачать файл кроме как через DS

2020-04-27 08:24 UTC, zloyden approved these changes

2020-04-27 08:24 UTC, merged