fix #54940 stratege.ru
AdguardTeam/AdguardFilters pull request #55010
Opened 2020-05-06 14:28 UTC by Sergey-Lyapin

#54940

Чтобы воспроизвести проблему необходимо авторизоваться.

2020-05-06 15:14 UTC, zloyden commented
Удаление правила исправляет детект, но [здесь ](https://www.stratege.ru/forums/register.php) еще реклама
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/81194246-17de5f00-8fc5-11ea-9dcf-f7a73ca12a0f.png)
</details><br/>

2020-05-07 07:34 UTC, zloyden requested changes

2020-05-07 07:34 UTC, zloyden commented on RussianFilter/sections/specific.txt
> +||stratege.ru/misc/*_TOP.jpg
Правило широкое, но можно немного конкретизировать `||stratege.ru/misc/*_APR20_TOP.jpg`

2020-05-07 07:34 UTC, zloyden commented on RussianFilter/sections/specific.txt
> +stratege.ru##div[id$="promo_layer"] > div[id] > a[href$="?r=stratege"]
Перехода по ссылке больше нет, но осталось изменение курсора при наведении на эту область и отступ сверху. В данном случае он рекламный, поэтому мы это правим тоже.
Добавь эти правила.
```
stratege.ru#$#body > div[id$="promo_layer"] { background: #000000 !important; }
stratege.ru#$##globalcontent { padding-top: 0 !important; }
stratege.ru##body > div[id$="promo_layer"] > style[type] + div[id]
```

2020-05-07 11:37 UTC, Sergey-Lyapin commented on RussianFilter/sections/specific.txt
> +||stratege.ru/misc/*_TOP.jpg
В июне спонсор им пришлет новые картинки и будет `_JUN20_TOP.jpg` и они не заблочатся

2020-05-07 11:57 UTC, zloyden commented on RussianFilter/sections/specific.txt
> +||stratege.ru/misc/*_TOP.jpg
Тогда нет особого смысла в этом блокирующем запросе, я ранее выкладывал правила `#$#`, которые убирают рекламный фон и отступ.

2020-05-07 12:37 UTC, Sergey-Lyapin commented on RussianFilter/sections/specific.txt
> +||stratege.ru/misc/*_TOP.jpg
Они не сработают на iOS и в контент блокере

2020-05-08 07:01 UTC, zloyden commented on RussianFilter/sections/specific.txt
> +||stratege.ru/misc/*_TOP.jpg
Хм, все же добавь это `||stratege.ru/misc/*_APR20_TOP.jpg` вместе с правилами из второго коммента и если поменяют в июне (равно изменению в верстке), мы тоже внесем поправки.

2020-05-08 10:15 UTC, zloyden approved these changes

2020-05-08 10:15 UTC, merged