fix #55770 ozon.ru
AdguardTeam/AdguardFilters pull request #55919
Opened 2020-05-22 17:05 UTC by Sergey-Lyapin

#55770

2020-05-22 17:51 UTC, Alex-302 commented on AnnoyancesFilter/sections/mobile-app.txt
> +ozon.ru#$#.modal-mask { display: none!important; }
dangerous rule. Can break useful popup

2020-05-26 14:37 UTC, Alex-302 commented on AnnoyancesFilter/sections/mobile-app.txt
> +ozon.ru#$?##__ozon > div.mobile > div.mobile > div.modal-mask:has(> div.modal-wrapper > div.modal-container > div.modal-content > div > h2:contains(OZON ещё лучше в приложении)) { display: none!impor
оно на всех платформах нужно?

2020-05-27 12:45 UTC, Sergey-Lyapin commented on AnnoyancesFilter/sections/mobile-app.txt
> +ozon.ru#$?##__ozon > div.mobile > div.mobile > div.modal-mask:has(> div.modal-wrapper > div.modal-container > div.modal-content > div > h2:contains(OZON ещё лучше в приложении)) { display: none!impor
Ну сработает все равно только на андроиде, но могу хинт добавить

2020-05-27 13:24 UTC, Alex-302 commented on AnnoyancesFilter/sections/mobile-app.txt
> +ozon.ru#$?##__ozon > div.mobile > div.mobile > div.modal-mask:has(> div.modal-wrapper > div.modal-container > div.modal-content > div > h2:contains(OZON ещё лучше в приложении)) { display: none!impor
А те которые ниже? Группируй такие хотя бы.

2020-05-27 14:17 UTC, zloyden requested changes

2020-05-27 14:17 UTC, zloyden commented on AnnoyancesFilter/sections/mobile-app.txt
> +ozon.ru#$#html { overflow:  visible!important; }
Лишний пробел в последнем правиле после `overflow:`.
Если ограничиваешь платформой несколько правил, а тут их 3, лучше использовать директиву `!#if`

2020-05-28 11:06 UTC, zloyden approved these changes

2020-06-01 09:39 UTC, Alex-302 commented on AnnoyancesFilter/sections/mobile-app.txt
> +!#if (android)
What is `!#if (` **android** `)`?
https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#what-constants-do-we-declare

2020-06-01 09:59 UTC, zloyden commented on AnnoyancesFilter/sections/mobile-app.txt
> +ozon.ru#$?##__ozon > div.mobile > div.mobile > div.modal-mask:has(> div.modal-wrapper > div.modal-container > div.modal-content > div > h2:contains(OZON ещё лучше в приложении)) { display: none!impor
Правило можно немного улучшить. В первой части необязательно `#__ozon > div.mobile`, во второй можно обойтись без `div`. Примерно так 
`ozon.ru#$?#.mobile > div.modal-mask:has(> div.modal-wrapper > div.modal-container > div.modal-content h2:contains(OZON ещё лучше в приложении)) { display: none!important; }`

2020-06-02 07:48 UTC, zloyden approved these changes

2020-06-02 07:48 UTC, merged