fix: blocks annoyance popup only
AdguardTeam/AdguardFilters pull request #56648
Opened 2020-06-02 13:49 UTC by HenryQW

***Description***:
* **Current behaviour**: 

All popups are blocked, including news.

* **Expected behaviour**: 

Only blocks annoyance popup, but allows other normal content popups.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/5896343/83527730-14fd5e00-a4e0-11ea-8fe7-628b57f6c907.png)

</details><br/>

2020-06-02 18:52 UTC, Alex-302 requested changes

2020-06-02 18:52 UTC, Alex-302 commented on SocialFilter/sections/general_extensions.txt
> +simplywall.st#$#div[data-cy-id="modal-ModalPortal-0-"] { display: none!important; }
please remove space at the end of the line

2020-06-02 18:53 UTC, Alex-302 commented
Hi. Which popups are useful? I see only this.

2020-06-03 15:36 UTC, HenryQW commented
> Hi. Which popups are useful? I see only this.

Pretty much every "View Data" button on the page will trigger a modal popup, which will be blocked by the current rule. These buttons are located in Section 3, 5, 7 etc.

![image](https://user-images.githubusercontent.com/5896343/83656964-2023bd00-a5b8-11ea-81e2-122cf33b2915.png)

![image](https://user-images.githubusercontent.com/5896343/83657152-65e08580-a5b8-11ea-931d-08f4effec0ae.png)

2020-06-04 13:31 UTC, Alex-302 commented
Got it.

2020-06-04 13:32 UTC, Alex-302 approved these changes

2020-06-04 13:32 UTC, merged