fix #57038 vegetarian.ru
AdguardTeam/AdguardFilters pull request #57074
Opened 2020-06-09 14:24 UTC by Sergey-Lyapin

#57038

2020-06-09 15:07 UTC, zloyden requested changes

2020-06-09 15:07 UTC, zloyden commented on RussianFilter/sections/css_extended.txt
> +vegetarian.ru#?#.sidebar div.widget:has(> noindex > a[href*="24veg.ru"])
Правило также не сработает не сработает на главной, 
Основную часть поменяй как в примере выше, а вторая здесь странная.
Лучше так `noindex > a[rel="nofollow"] > img`

2020-06-09 15:07 UTC, zloyden commented on AnnoyancesFilter/sections/annoyances.txt
> +vegetarian.ru#?#.sidebar div.widget:has(> div[id^="comp_"] > div.bx-subscribe)
Проверяй не только страницу из задачи. На главной это правило не сработает.
В первой части оставь `.widget`.
Во второй вместо `div[id^="comp_"]` просто `div[id]`.

2020-06-10 00:47 UTC, Sergey-Lyapin commented on AnnoyancesFilter/sections/annoyances.txt
> +vegetarian.ru#?#.sidebar div.widget:has(> div[id^="comp_"] > div.bx-subscribe)
у меня это правило работает на главной

2020-06-10 09:43 UTC, zloyden commented on AnnoyancesFilter/sections/annoyances.txt
> +vegetarian.ru#?#.sidebar div.widget:has(> div[id^="comp_"] > div.bx-subscribe)
Вчера у меня не сработали оба правила на главной. Вижу ты поменял, так будет лучше.

2020-06-10 09:47 UTC, zloyden requested changes
Добавь еще блокировку рекламных картинок `||vegetarian.ru/upload/rk/`.  Не в этом виде - в русском фильтре есть общее правило.

2020-06-10 11:59 UTC, zloyden approved these changes

2020-06-10 11:59 UTC, merged