fix #60453 dv-gazeta.info
AdguardTeam/AdguardFilters pull request #60551
Opened 2020-07-31 16:50 UTC by Sergey-Lyapin

#60453

2020-08-01 18:55 UTC, Alex-302 requested changes
также к этому сайту можно применить правило блокировки сторонних скриптов из русского фильтра

2020-08-01 18:55 UTC, Alex-302 commented on SocialFilter/sections/specific.txt
> +dv-gazeta.info##.postmetadata
ломает

2020-08-01 18:55 UTC, Alex-302 commented on SpywareFilter/sections/tracking_servers.txt
> +||informer.link^$third-party
больше на рекламныe похоже, со счётчиком

2020-08-01 20:19 UTC, zloyden commented on SpywareFilter/sections/tracking_servers.txt
> +||informer.link^$third-party
> больше на рекламныe похоже, со счётчиком

так и есть, правда последние два адреса у меня не появляются. судя из первого, это `n4p-rus.redtram.com` можно в трекеры

2020-08-01 20:25 UTC, Sergey-Lyapin commented on SpywareFilter/sections/tracking_servers.txt
> +||informer.link^$third-party
Видел это, но почему-то решил, что redtram это трекинг %)
![Screenshot 2020-08-01 at 23 21 24](https://user-images.githubusercontent.com/18536328/89109917-1e5a6680-d44e-11ea-874b-9de2e4d39013.png)

2020-08-01 20:27 UTC, Sergey-Lyapin commented on SocialFilter/sections/specific.txt
> +dv-gazeta.info##.postmetadata
хз как не заметил

2020-08-02 09:31 UTC, Alex-302 approved these changes

2020-08-02 09:31 UTC, merged