fix #60886 samehadaku.vip
AdguardTeam/AdguardFilters pull request #60899
Opened 2020-08-05 12:07 UTC by stanislav-atr

#60886

2020-08-05 14:13 UTC, zloyden requested changes

2020-08-05 14:13 UTC, zloyden commented on EnglishFilter/sections/specific.txt
> +samehadaku.vip##.adsplayer > div.close-button
It was fixed by `AdBlockID` (this site is Indonesian). You can fix here another elements like share `Bagikan`

2020-08-05 21:38 UTC, Alex-302 approved these changes

2020-08-06 08:02 UTC, zloyden approved these changes

2020-08-06 08:02 UTC, merged