fix #61010 pinkvilla.com
AdguardTeam/AdguardFilters pull request #61068
Opened 2020-08-07 11:21 UTC by Sergey-Lyapin

#61010

2020-08-07 17:35 UTC, Alex-302 requested changes

2020-08-07 17:35 UTC, Alex-302 commented on EnglishFilter/sections/css_extended.txt
> +pinkvilla.com#?#body li:has(> div[style] > span:contains(Advertisement))
`body`  is redundant here

2020-08-08 13:15 UTC, Sergey-Lyapin commented on SocialFilter/sections/specific.txt
> +pinkvilla.com##.top_media > ul
It is floating share button's leftover at the bottom (mobile version)

2020-08-09 11:35 UTC, Sergey-Lyapin commented on SocialFilter/sections/specific.txt
> +pinkvilla.com##.top_media > ul
![Screenshot 2020-08-09 at 14 34 21](https://user-images.githubusercontent.com/18536328/89731151-83fdb280-da4d-11ea-8c45-50bbb57d0d71.png)

2020-08-09 18:07 UTC, Alex-302 approved these changes

2020-08-09 18:09 UTC, merged