fix #61120 klix.ba
AdguardTeam/AdguardFilters pull request #61240
Opened 2020-08-10 10:50 UTC by Sergey-Lyapin

#61120

2020-08-10 10:59 UTC, Sergey-Lyapin commented on SpywareFilter/sections/whitelist.txt
> +@@||googletagmanager.com/gtag/js$domain=klix.ba
for fixing the slider, for example here
https://www.klix.ba/magazin/showbiz/katie-price-slomila-oba-stopala-krece-se-puzuci-na-koljenima/200810046

2020-08-11 12:42 UTC, Alex-302 requested changes

2020-08-11 12:42 UTC, Alex-302 commented on AnnoyancesFilter/sections/antiadblock.txt
> +klix.ba,news247.gr,sport24.gr,contra.gr,esquire.com.gr,slickdeals.net,narcity.com,observador.pt,ni.dk,jetphotos.com,marketscreener.com,zonebourse.com,ign.com,dziennikbaltycki.pl,marca.com,snopes.com,
redundant JS rule and unnecessary hints.
Better copy `! 'contributor.google.com'` from Base filter.

2020-08-13 19:10 UTC, Alex-302 approved these changes

2020-08-13 19:10 UTC, merged

2020-08-13 19:11 UTC, Alex-302 commented on AnnoyancesFilter/sections/antiadblock.txt
> +sport24.gr,contra.gr,esquire.com.gr,slickdeals.net,narcity.com,observador.pt,ni.dk,jetphotos.com,marketscreener.com,zonebourse.com,ign.com,dziennikbaltycki.pl,marca.com,snopes.com,cnnturk.com,polskat
эти тоже можешь перепроверить и заменить на CSS