fix #61280 elamigosedition.com
AdguardTeam/AdguardFilters pull request #61309
Opened 2020-08-11 10:03 UTC by stanislav-atr

#61280

2020-08-11 13:55 UTC, Alex-302 commented
Ad
![image](https://user-images.githubusercontent.com/8361299/89905931-6702e400-dbf3-11ea-858e-3ed09f75be61.png)
and clickunder when you trying to download.
Please fix in new PR.

2020-08-11 13:58 UTC, Alex-302 requested changes

2020-08-11 13:58 UTC, Alex-302 commented on EnglishFilter/sections/antiadblock.txt
> +elamigosedition.com,coolsoft.altervista.org,cooltamilhd.com,courseclub.net,crabcut.net,cracxsoftwares.com,csport.xyz,d-h.st,damasgate.com,dangotoons.com,dasolo.co,david-forum.de,dayzrp.com,dc-chronic
What about platforms without JS?

2020-08-12 11:53 UTC, stanislav-atr commented
> Ad
> ![image](https://user-images.githubusercontent.com/8361299/89905931-6702e400-dbf3-11ea-858e-3ed09f75be61.png)
> and clickunder when you trying to download.

Bait link removed, but i cant reproduce clickunder with AG turned on.

2020-08-13 19:16 UTC, Alex-302 approved these changes

2020-08-13 19:22 UTC, Alex-302 approved these changes

2020-08-13 19:22 UTC, merged