fix #61293 gorodarmavir.ru
AdguardTeam/AdguardFilters pull request #61302
Opened 2020-08-11 08:38 UTC by stanislav-atr

#61293

2020-08-11 08:58 UTC, Sergey-Lyapin requested changes

2020-08-11 08:58 UTC, Sergey-Lyapin commented on RussianFilter/sections/specific.txt
> +gorodarmavir.ru##.container-for-shadow-root
It's better to block adserver
`||yxswtummev.info^$third-party`

2020-08-11 09:03 UTC, Sergey-Lyapin commented
Please also block leftovers
<details>
<summary>Please also block leftovers like this</summary>
<img src="https://user-images.githubusercontent.com/18536328/89878612-6d309a80-dbca-11ea-81f9-4795c5895fae.png" />
</details>

2020-08-11 09:52 UTC, Sergey-Lyapin commented on RussianFilter/sections/specific.txt
> +gorodarmavir.ru##.container-for-shadow-root
`||metrics0.com^$third-party`
tracking server

2020-08-11 13:44 UTC, Alex-302 commented
there are a lot of similar sites. Look for `/section/banners/upload/*$domain=015.by******` rule

2020-08-12 15:18 UTC, Alex-302 approved these changes

2020-08-12 15:18 UTC, merged