fix #61418 myprivacy.dpgmedia.be
AdguardTeam/AdguardFilters pull request #61422
Opened 2020-08-13 10:41 UTC by stanislav-atr

#61418

2020-08-13 11:34 UTC, Sergey-Lyapin requested changes
This rule doesn't work

2020-08-14 11:37 UTC, Alex-302 commented on AnnoyancesFilter/sections/cookies_specific.txt
> -myprivacy.dpgmedia.net#%#AG_onLoad(function() { setTimeout(function() { var el = document.getElementsByClassName("form__button-group")[0]; if(el) { el.submit(); }; }, 300); });
они точно не нужны?
Проверь это с бельгийским и голландским VPN:
https://github.com/AdguardTeam/AdguardFilters/issues/32191

2020-08-14 11:42 UTC, stanislav-atr commented on AnnoyancesFilter/sections/cookies_specific.txt
> -myprivacy.dpgmedia.net#%#AG_onLoad(function() { setTimeout(function() { var el = document.getElementsByClassName("form__button-group")[0]; if(el) { el.submit(); }; }, 300); });
Они убрали форму, и теперь там просто две <button>, form.submit() неактуально.

2020-08-14 14:50 UTC, Alex-302 approved these changes

2020-08-14 14:50 UTC, merged