fix #61677 tr.bloggif.com
AdguardTeam/AdguardFilters pull request #61857
Opened 2020-08-19 16:11 UTC by Sergey-Lyapin

#61677

2020-08-19 16:12 UTC, Sergey-Lyapin commented on AnnoyancesFilter/sections/annoyances.txt
> +bloggif.com###right > div.sky + h2
or better use contains with "newsletter" on all app's languages?)

2020-08-20 20:00 UTC, Alex-302 requested changes

2020-08-20 20:00 UTC, Alex-302 commented on AnnoyancesFilter/sections/annoyances.txt
> +bloggif.com###right > div.sky + h2
make selector more specific

2020-08-23 18:40 UTC, Alex-302 commented on AnnoyancesFilter/sections/annoyances.txt
> +bloggif.com#?##right > h2:contains(/จดหมายข่าว|бюлетина|ewsletter|δελτίο|Boletín|hírlevél|ニュースレター|naujienas|Nieuwsbrief|рассылку|nyhetsbrevet|Bültenimizi|接收简讯/)
I mean something like that, without extended CSS
`#right > #rightTools + div.sky + h2`

2020-08-24 08:35 UTC, Alex-302 approved these changes

2020-08-24 08:36 UTC, merged