fix #61894 news.thewindowsclub.com
AdguardTeam/AdguardFilters pull request #61995
Opened 2020-08-21 10:00 UTC by stanislav-atr

#61894

2020-08-22 17:17 UTC, Sergey-Lyapin requested changes
`thewindowsclub.com###ss-floating-bar`
It's better to move this rule to popups.txt

2020-08-24 09:22 UTC, Alex-302 commented
> It's better to move this rule to popups.txt

not popup

2020-08-24 09:22 UTC, Alex-302 requested changes

2020-08-24 09:22 UTC, Alex-302 commented on AnnoyancesFilter/sections/annoyances.txt
> +thewindowsclub.com###ss-floating-bar
to social filter

2020-08-24 09:39 UTC, stanislav-atr commented
> 
> 
> leftover

Nothing there with or w/o adguard.

2020-08-24 09:46 UTC, Alex-302 approved these changes

2020-08-24 09:46 UTC, merged