fix #61973 digitalcitizen.life
AdguardTeam/AdguardFilters pull request #62014
Opened 2020-08-21 13:57 UTC by stanislav-atr

#61973

2020-08-22 18:20 UTC, Sergey-Lyapin requested changes
Please block also this newsletter (without social links of course)
![Screenshot 2020-08-22 at 21 17 53](https://user-images.githubusercontent.com/18536328/90963022-32c5d800-e4bd-11ea-9f1c-681fc3d2a9c1.png)

2020-08-24 09:12 UTC, Alex-302 commented on EnglishFilter/sections/specific.txt
> +digitalcitizen.life##aside[id*="-amp-ad-"]
why not `block--amp-ad`?

2020-08-24 10:03 UTC, stanislav-atr commented
> 
> 
> Please block also this newsletter (without social links of course)
> ![Screenshot 2020-08-22 at 21 17 53](https://user-images.githubusercontent.com/18536328/90963022-32c5d800-e4bd-11ea-9f1c-681fc3d2a9c1.png)

There is identical widget at the footer of the page, should we maybe delete this one completely?

2020-08-24 10:06 UTC, Alex-302 commented on AnnoyancesFilter/sections/annoyances.txt
> +digitalcitizen.life##.block-next-sidebar-subscription-options > :not(.subscription-options__social_buttons)
for subscriptions we have the section
https://github.com/AdguardTeam/AdguardFilters/blob/c4bbe243c52e19d72f7bdee07be6529658f225ea/AnnoyancesFilter/sections/annoyances.txt#L1476

2020-08-24 10:13 UTC, Alex-302 approved these changes

2020-08-24 10:27 UTC, Alex-302 approved these changes

2020-08-24 10:28 UTC, merged