fix #61903 xboxdynasty.de
AdguardTeam/AdguardFilters pull request #62010
Opened 2020-08-21 12:52 UTC by Sergey-Lyapin

#61903

2020-08-21 14:27 UTC, BlazDT requested changes

2020-08-24 09:14 UTC, Alex-302 commented on AnnoyancesFilter/sections/antiadblock.txt
> +||stalesummer.com^$third-party
you can add аdmiral also to Tracking Protection

2020-08-24 09:52 UTC, Sergey-Lyapin commented on AnnoyancesFilter/sections/antiadblock.txt
> +||stalesummer.com^$third-party
i've already done it)

2020-08-24 09:54 UTC, Alex-302 approved these changes

2020-08-24 09:54 UTC, merged