fix #61926 ceofix.com
AdguardTeam/AdguardFilters pull request #62019
Opened 2020-08-21 15:01 UTC by stanislav-atr

#61926

2020-08-22 19:06 UTC, Sergey-Lyapin requested changes

2020-08-24 10:02 UTC, Alex-302 commented on EnglishFilter/sections/specific.txt
> +ceofix.com##img.disabled[loading="lazy"]
This site it Turkish, has no English interface.

2020-08-24 10:09 UTC, stanislav-atr commented on EnglishFilter/sections/specific.txt
> +ceofix.com##img.disabled[loading="lazy"]
my bad

2020-08-24 10:40 UTC, Alex-302 approved these changes

2020-08-24 10:40 UTC, merged