fix #61999 good-football.org
AdguardTeam/AdguardFilters pull request #62024
Opened 2020-08-21 15:27 UTC by Sergey-Lyapin

#61999

2020-08-24 09:59 UTC, Alex-302 requested changes

2020-08-24 09:59 UTC, Alex-302 commented on RussianFilter/sections/general_extensions.txt
> +sporting7.pw,08sportbar.online,08sportbar.net,sport24hd.net,sport24hd.com#%#//scriptlet("prevent-window-open")
ломаешь открытие плеера

2020-08-24 09:59 UTC, Alex-302 commented on RussianFilter/sections/specific.txt
> +||apl14.me/js/pop.js
![image](https://user-images.githubusercontent.com/8361299/91031636-8d6c4a80-e609-11ea-8cdc-6357ccdbf70f.png)

2020-08-24 09:59 UTC, Alex-302 commented on RussianFilter/sections/specific.txt
> +sporting7.pw,goool7.ws##.ovdiv
а это откуда?

2020-08-24 10:12 UTC, Sergey-Lyapin commented on RussianFilter/sections/specific.txt
> +sporting7.pw,goool7.ws##.ovdiv
это такие же элементы как и `body > div[style*="position: absolute;"][style*="z-index: 9999;"]`, только у них еще и класс есть

2020-08-24 20:51 UTC, Alex-302 commented on RussianFilter/sections/specific.txt
> +sporting7.pw,goool7.ws##.ovdiv
всё равно не пойму) Элемент `body > div[style*="position: absolute;"][style*="z-index: 9999;"]` вижу, но его скрытие ничего не даёт.

2020-08-24 20:53 UTC, Alex-302 commented on RussianFilter/sections/general_extensions.txt
> +sporting7.pw,08sportbar.online,08sportbar.net,sport24hd.net,sport24hd.com#%#//scriptlet("prevent-window-open")
там ещё есть домены. В скрипте можно смотреть:
```
var videoid0 = '<iframe src="https://sporting360.org/channel/setantaplusru" width="640" height="560" frameborder="0" scrolling="no" allowfullscreen></iframe>';
var videoid1 = '<iframe src="https://sporting360.org/channel/setantaplusukr" width="640" height="560" frameborder="0" scrolling="no" allowfullscreen></iframe>';
var videoid2 = '<iframe src="https://08sportbar.net/seteurasiaplus.html" width="640" height="560" frameborder="0" scrolling="no" allowfullscreen></iframe>';
var videoid3 = '<iframe src="https://goool7.ws/891d76e2728978bbcba0ea2362a59c15-live.html" width="640" height="560" frameborder="0" scrolling="no" allowfullscreen></iframe>';
var videoid4 = '<iframe src="https://08sportbar.net/setantaukrplus.html" width="640" height="560" frameborder="0" scrolling="no" allowfullscreen></iframe>';
var videoid5 = '<iframe src="https://goool7.ws/05ae328bbd1091351f94efacc46e15f4-live.html" width="640" height="560" frameborder="0" scrolling="no" allowfullscreen></iframe>';
```

+ можно добавить это `||z.cdn.trafficdok.com^$document,popup`

2020-08-25 07:48 UTC, Sergey-Lyapin commented on RussianFilter/sections/general_extensions.txt
> +sporting7.pw,08sportbar.online,08sportbar.net,sport24hd.net,sport24hd.com#%#//scriptlet("prevent-window-open")
> В скрипте можно смотреть:

 Не вижу этого скрипта

2020-08-25 09:32 UTC, Sergey-Lyapin commented on RussianFilter/sections/specific.txt
> +sporting7.pw,goool7.ws##.ovdiv
Дает начало воспроизведения с первого клика, а не с 2-3-4

2020-08-25 09:36 UTC, Alex-302 approved these changes

2020-08-25 09:36 UTC, Alex-302 commented on RussianFilter/sections/specific.txt
> +sporting7.pw,goool7.ws##.ovdiv
ок

2020-08-25 09:37 UTC, merged