fix #62914 province.ru
AdguardTeam/AdguardFilters pull request #62988
Opened 2020-09-03 10:25 UTC by stanislav-atr

#62914

2020-09-03 10:43 UTC, zloyden requested changes

2020-09-03 10:43 UTC, zloyden commented on RussianFilter/sections/specific.txt
> +province.ru##div[style*="height:439px; width:730px;"]
Добавь еще альтернативное правило с ext-css для этого `province.ru##div[style*="height:439px; width:730px;"]`.

2020-09-03 10:46 UTC, zloyden requested changes
Эти остатки также нужно убрать
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/92105636-cb2c5880-edeb-11ea-9294-c42cd93489d9.png)

</details><br/>

2020-09-03 12:32 UTC, zloyden commented
В выделенной части в шапке реклама - посмотри без Адгарда.

2020-09-03 12:51 UTC, stanislav-atr commented
Removed white block and leftovers, not sure about #?# alternative though.
innerHTML script inside div breaks it somehow, not sure
![изображение](https://user-images.githubusercontent.com/68852737/92116980-40545980-edfd-11ea-8749-5eb942b229f1.png)

2020-09-03 15:10 UTC, zloyden commented
Этот элемент можно убрать расширенным, только учти еще, что код может быть не одинаковым.
Например, здесь отличается немного `https://www.province.ru/news/otets-otdal-dochke-shkolnitse-.html`

2020-09-03 15:12 UTC, zloyden requested changes

2020-09-03 15:12 UTC, zloyden commented on RussianFilter/sections/specific.txt
> +province.ru##tr[valign="top"] > td[width="215"]
Здесь лучше конкретней правило сделать. Для этого остатка есть общее правило в русском фильтре `##div[id^="unit_"]`
Второе правило не обязательно.

2020-09-03 15:16 UTC, zloyden commented
На главной `province.ru` уехал правый сайдбар из-за правила `province.ru##.flexbannergroup`. Нужно будет поправить отдельным.
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/92133816-7ef40f00-ee11-11ea-922c-a5862a903c6d.png)

</details><br/>

2020-09-04 11:14 UTC, zloyden approved these changes

2020-09-04 11:14 UTC, merged