fix #63666 meduza.io
AdguardTeam/AdguardFilters pull request #63859
Opened 2020-09-14 12:42 UTC by stanislav-atr

#63666

2020-09-15 10:19 UTC, Alex-302 commented on SocialFilter/sections/specific.txt
> +meduza.io##div[class*="style__List-sc-"]
не вижу этот элемент

2020-09-15 11:24 UTC, Alex-302 requested changes

2020-09-15 11:24 UTC, Alex-302 commented on SocialFilter/sections/specific.txt
> +meduza.io##a[href^="//odnoklassniki.ru/dk?st.cmd=addShare"]
а остатки? Только осторожно(по `ul > li` желательно сузить, чтоб не скрыть нужное, что может произойти на этом сайта).

2020-09-15 11:37 UTC, stanislav-atr commented on SocialFilter/sections/specific.txt
> +meduza.io##a[href^="//odnoklassniki.ru/dk?st.cmd=addShare"]
Под ul > li с такими же классами есть полезные элементы
![screen](https://user-images.githubusercontent.com/68852737/93205455-834cf000-f760-11ea-87d9-590cc6c46330.jpg)
Есть уникальный для страницы класс `.Toolbar`

2020-09-15 19:16 UTC, Alex-302 commented on SocialFilter/sections/specific.txt
> +meduza.io##a[href^="//odnoklassniki.ru/dk?st.cmd=addShare"]
ну не буквально `##ul > li` же. Найди подходящий родительский элемент и расширенным CSS скрой.

2020-09-21 11:17 UTC, Alex-302 approved these changes

2020-09-21 11:18 UTC, merged