Ran "Redundant Rule Checker" on AdGuard Base
AdguardTeam/AdguardFilters pull request #64857
Opened 2020-10-01 05:14 UTC by DandelionSprout

[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

I figured that since "Hacktober" has begun, and it'd probably seem underwhelming for me to just do a "Fix-PR for one or two issue reports" thing, I thought it'd seem more impressive to do redundancy removal PRs like these.

My plan was to go through the 178 most important lines I got in the report when I ran AdGuard Base as a whole through https://abp.surge.sh/redundantRuleChecker/. However, I began to lose track of AdGuard Base's 15 source files after a little more than an hour, and Fanboy seemed to me personally to cast doubt about how desired it was to remove redundant rules in major lists when [I did the same in EasyList](https://github.com/easylist/easylist/pull/6104), so I only went through ~140 of the 178 report lines.

```
/:\/\/rarbg.bypassed.org\/cdn\/static\/20\/js\/[a-z0-9]{20,}.js/$domain=rarbg.bypassed.org has been made redundant by /:\/\/rarbg.bypassed.org\/cdn\/static\/20\/js\/[a-z0-9]{20,}.js/$domain=rarbg.bypassed.org
@@/js/showad_.js$domain=flashx.tv has been made redundant by @@/js/showad*.js$domain=flashx.tv|flashx.to
@@|https:///ovh.webshark.pl/adserver/*/main_script.js?advertise_check=1 has been made redundant by @@||ovh.webshark.pl/adserver/*/main_script.js?advertise_check=1
@@||adm.fwmrm.net/p/msn_live/AdManager.swf$domain=msn.com has been made redundant by @@||adm.fwmrm.net/p/msn_live/AdManager.swf$domain=msn.com|akamaized.net
@@||ajax.googleapis.com/ajax/libs/jquery/$domain=2ddl.unblocked.vc|daporn.com|imagefap.com|linkdrop.net|gelbooru.com|fmovies.is|fmovies.se|imagespicy.site|mycloud.to has been made redundant by @@||ajax.googleapis.com/ajax/libs/jquery/
@@||androgalaxy.in^$generichide has been made redundant by @@||androgalaxy.in^$generichide
@@||aphim.co^$generichide has been made redundant by @@||aphim.co^$generichide
@@||apitvh.net/embed/ads_code_1.js$domain=apitvh.net has been made redundant by @@||apitvh.net/embed/*ads_code_*.js
@@||asianovel.com^$generichide has been made redundant by @@||asianovel.com^$generichide
@@||bitearns.com/*/libs/advertisement.js has been made redundant by @@||bitearns.com/*/advertisement.js
@@||cdn.staticdata.site/js/loadjs.min.js^$domain=strikeout.nu has been made redundant by @@||cdn.staticdata.site/js/loadjs*.min.js$domain=strikeout.nu
@@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js$domain=ac-mo.com|nfmovies.com has been made redundant by @@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js
@@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js$domain=asahihen.blogspot.com has been made redundant by @@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js
@@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js$domain=mp4mania.xyz has been made redundant by @@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js
@@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js$domain=she2013.com has been made redundant by @@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js
@@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js$domain=sport-tv-guide.live has been made redundant by @@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js
@@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js$domain=streamcloud.eu has been made redundant by @@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js
@@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js$domain=televisiongratishd.com has been made redundant by @@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js
@@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js$domain=todosobrepsp.com has been made redundant by @@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js
@@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js$domain=ventax.net has been made redundant by @@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js
@@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/3.2.1/fuckadblock.min.js$domain=1004lucifer.blogspot.com has been made redundant by @@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js
@@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/3.2.1/fuckadblock.min.js$domain=abazero.com has been made redundant by @@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js
@@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/3.2.1/fuckadblock.min.js$domain=androidaba.com has been made redundant by @@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js
@@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/3.2.1/fuckadblock.min.js$domain=aphim.co has been made redundant by @@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js
@@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/3.2.1/fuckadblock.min.js$domain=c11.kr has been made redundant by @@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js
@@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/3.2.1/fuckadblock.min.js$domain=comicspace.com.br has been made redundant by @@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js
@@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/3.2.1/fuckadblock.min.js$domain=daemon-hentai.com has been made redundant by @@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js
@@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/3.2.1/fuckadblock.min.js$domain=donia2link.net|sqrible.com has been made redundant by @@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js
@@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/3.2.1/fuckadblock.min.js$domain=evilkingmedia.com has been made redundant by @@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js
@@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/3.2.1/fuckadblock.min.js$domain=ezbit.co.in has been made redundant by @@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js
@@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/3.2.1/fuckadblock.min.js$domain=faucetcrypto.com has been made redundant by @@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js
@@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/3.2.1/fuckadblock.min.js$domain=filmninja.ws has been made redundant by @@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js
@@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/3.2.1/fuckadblock.min.js$domain=getpaidtoshare.money has been made redundant by @@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js
@@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/3.2.1/fuckadblock.min.js$domain=giga74.com has been made redundant by @@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js
@@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/3.2.1/fuckadblock.min.js$domain=gmyankee.tistory.com has been made redundant by @@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js
@@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/3.2.1/fuckadblock.min.js$domain=highresolutionmusic.com has been made redundant by @@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js
@@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/3.2.1/fuckadblock.min.js$domain=hotanime.me has been made redundant by @@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js
@@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/3.2.1/fuckadblock.min.js$domain=jyra.online has been made redundant by @@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js
@@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/3.2.1/fuckadblock.min.js$domain=link4gen.com has been made redundant by @@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js
@@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/3.2.1/fuckadblock.min.js$domain=loadvid.online|hdonline.is has been made redundant by @@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js
@@||cdnjs.cloudflare.com/ajax/libs/fuckadblo [...]

2020-10-01 14:48 UTC, Yuki2718 commented
Great! I think at some point in near future re-evaluation of old scriptlet rules will be needed too.

2020-10-05 09:54 UTC, Alex-302 requested changes

2020-10-05 09:54 UTC, Alex-302 commented on EnglishFilter/sections/adservers.txt
> -||analyticsq.com^
Not redundant. Please read directive above)

2020-10-05 09:54 UTC, Alex-302 commented on EnglishFilter/sections/antiadblock.txt
> +! https://github.com/AdguardTeam/AdguardFilters/issues/19880
wrong copy-pasta?

2020-10-05 09:54 UTC, Alex-302 commented on EnglishFilter/sections/antiadblock.txt
> -@@||imgadult.com/anex/alt2.js
Why these removed?
```
! https://github.com/AdguardTeam/AdguardFilters/issues/19880	
!+ PLATFORM(ext_ff, ext_opera, ios, ext_android_cb, ext_ublock)	
@@||singingdalong.blogspot.com^$generichide	
! https://github.com/AdguardTeam/AdguardFilters/issues/19837	
@@||imgadult.com/anex/alt2.js
```

2020-10-05 09:54 UTC, Alex-302 commented on EnglishFilter/sections/specific.txt
> -/:\/\/rarbg.bypassed.org\/cdn\/static\/20\/js\/[a-z0-9]{20,}.js/$domain=rarbg.bypassed.org
better remove another copy

2020-10-05 09:55 UTC, Alex-302 commented
Please note that the Safari's API is working not like Chrome, and some rules, which looks like redundant - are still required(URL rules).

2020-10-05 10:01 UTC, Alex-302 commented on EnglishFilter/sections/adservers.txt
> -||analyticsq.com^
Reverted.

2020-10-05 10:06 UTC, Alex-302 commented on EnglishFilter/sections/antiadblock.txt
> +! https://github.com/AdguardTeam/AdguardFilters/issues/19880
Removed.

2020-10-05 10:12 UTC, merged

2020-10-05 10:13 UTC, Alex-302 commented on EnglishFilter/sections/antiadblock.txt
> -@@||imgadult.com/anex/alt2.js
It seems ok)

2020-10-05 10:13 UTC, Alex-302 commented
Thanks!