fix #68564 brotorrent.net
AdguardTeam/AdguardFilters pull request #68771
Opened 2020-11-28 16:23 UTC by stanislav-atr

#68564

2020-11-29 16:48 UTC, Alex-302 requested changes

2020-11-29 16:48 UTC, Alex-302 commented on RussianFilter/sections/specific.txt
> +brotorrent.net##div.order-6 > a > img[style^="max-width: 100%; border-radius: 3px;"]
оно не работает в программах.

2020-11-30 12:18 UTC, stanislav-atr commented on RussianFilter/sections/specific.txt
> +brotorrent.net##div.order-6 > a > img[style^="max-width: 100%; border-radius: 3px;"]
По какой-то причине селектор не берет дальше div.order-6, убрать картинку
`||brotorrent.net/templates/brotorrent/images/rprprp.png`
или всю папку?
`||brotorrent.net/templates`

Нерекламные изображения картинки лежат в `/uploads`.

2020-11-30 14:09 UTC, zloyden commented on RussianFilter/sections/specific.txt
> +brotorrent.net##div.order-6 > a > img[style^="max-width: 100%; border-radius: 3px;"]
Вместо косметического правила лучше запросом убрать, как ты предложил выше - баннер один.
`||brotorrent.net/templates/brotorrent/images/rprprp.png`

2020-12-01 14:23 UTC, zloyden approved these changes

2020-12-01 14:42 UTC, merged