Fix #69545 myuploadedpremium.de
AdguardTeam/AdguardFilters pull request #69608
Opened 2020-12-09 10:47 UTC by AdamWr

Issue - https://github.com/AdguardTeam/AdguardFilters/issues/69545
Code - https://gist.github.com/AdamWr/d9d16be46fcad6df18306e19637ed6aa#file-myuploadedpremium-js

This website is checking iframe `height` attribute.
Something like:

```js
if( $("iframe")[1].height < 10 ) {
    adblock
}
```

2020-12-09 12:00 UTC, ameshkov requested changes

2020-12-09 12:03 UTC, AdamWr commented on EnglishFilter/sections/antiadblock.txt
> +myuploadedpremium.de#%#AG_onLoad(function(){var a=new MutationObserver(function(){document.querySelectorAll(".adsbygoogle iframe").forEach(function(b){b.setAttribute("height","11");a.disconnect()})})
I checked it and it doesn't work, because they are checking iframe attribute `height`, not style `height`.

2020-12-09 12:12 UTC, ameshkov commented on EnglishFilter/sections/antiadblock.txt
> +myuploadedpremium.de#%#AG_onLoad(function(){var a=new MutationObserver(function(){document.querySelectorAll(".adsbygoogle iframe").forEach(function(b){b.setAttribute("height","11");a.disconnect()})})
Hm, that's weird, because it did help me.

How to reproduce this issue?

2020-12-09 12:14 UTC, AdamWr commented on EnglishFilter/sections/antiadblock.txt
> +myuploadedpremium.de#%#AG_onLoad(function(){var a=new MutationObserver(function(){document.querySelectorAll(".adsbygoogle iframe").forEach(function(b){b.setAttribute("height","11");a.disconnect()})})
>How to reproduce this issue?

You need to move a mouse cursor on "Download file" button.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/101628708-7dde0980-3a20-11eb-816e-1a58d165d52b.png)

</details>

2020-12-09 12:17 UTC, ameshkov commented on EnglishFilter/sections/antiadblock.txt
> +myuploadedpremium.de#%#AG_onLoad(function(){var a=new MutationObserver(function(){document.querySelectorAll(".adsbygoogle iframe").forEach(function(b){b.setAttribute("height","11");a.disconnect()})})
Oh I see:
```
else if ($("iframe")[1].height < 10 && (Math.random() < 0.5))
```

2020-12-09 12:17 UTC, ameshkov commented
So if I am getting this right, we'd better introduce a scriptlet that can set HTML elements attributes.

Something like `set-constant`, but for attributes.

2020-12-09 12:20 UTC, ameshkov approved these changes

2020-12-09 12:24 UTC, AdamWr commented
>So if I am getting this right, we'd better introduce a scriptlet that can set HTML elements attributes.
>
>Something like set-constant, but for attributes.

I guess it would be useful.

>@AdamWr are there many rules like that?

Not some many.
If I'm not wrong some of them probably could be replaced by `$redirect=googlesyndication-adsbygoogle` and for others we will need also an option to create an `element` firstly.
For example:
```
9anime.is#%#AG_onLoad(function() { var el=document.querySelector('#sidebar > [class="widget crop text-center mgid"] > [id*="ScriptRoot"]'); var ce=document.createElement('div'); if(el) { el.appendChild(ce); ce.setAttribute("id", "MarketGidComposite180508"); } });
mellow.link#%#AG_onLoad(function() { var el=document.querySelector('[class^="flexAd"]'); var ce=document.createElement('div'); if(el) { el.appendChild(ce); ce.setAttribute("id", "frameAd"); } });
```

2020-12-09 12:58 UTC, ameshkov commented
> will need also an option to create an element firstly

Oh, this is interesting. So we may need a scriptlet like "create-bait-element" or smth like this?
Could you please supply some examples here: https://github.com/AdguardTeam/Scriptlets/issues/106

2020-12-09 13:16 UTC, slavaleleka approved these changes

2020-12-09 13:27 UTC, AdamWr commented
>Could you please supply some examples here: AdguardTeam/Scriptlets#106

Unfortunately at the moment I can't find any real examples which couldn't be fixed by the current scriptlets or redirect rules.
As I recall `9anime.is` could be a good example, but it's dead, `mellow.link` now probably could be fixed by `$redirect=noopframe`

2020-12-09 13:28 UTC, merged

2020-12-11 09:01 UTC, Yuki2718 commented
Or `myuploadedpremium.de#%#//scriptlet('prevent-addEventListener', 'mouseover')` should work (uBO solution). Initially I added `##+js(aopr, atob)` as the script happened to use window.atob to decode. But these methods have potential for FP if the function are used in other way. At least prevent-addEventListener can be narrowed down by the third parameter tho.