fix #70272 siver.com.ua
AdguardTeam/AdguardFilters pull request #70525
Opened 2020-12-21 12:49 UTC by stanislav-atr

#70272

2020-12-22 10:13 UTC, Sergey-Lyapin requested changes

2020-12-22 10:13 UTC, Sergey-Lyapin commented on RussianFilter/sections/css_extended.txt
> +siver.com.ua#?#.sidebox > div.sidetitle > span:contains("Погода")
Это в раздражители

2020-12-22 10:13 UTC, Sergey-Lyapin commented on RussianFilter/sections/css_extended.txt
> +siver.com.ua#?#.sidebox > div.sidetitle > span:contains("Купуй українське!")
Тут лучше соединить в одно правило с регекспом:
`siver.com.ua#?#.sidebox > div.sidetitle > span:contains("/Купуй українське!|Реклама/")`

2020-12-22 10:13 UTC, Sergey-Lyapin commented on RussianFilter/sections/css_extended.txt
> +siver.com.ua#?#.sidebox > div.sidetitle > span:contains("Купуй українське!")
и в обоих случаях нужно удалить .sidetitle, т.к. если удалить только span, то останется полоска.

2020-12-22 10:23 UTC, stanislav-atr commented on RussianFilter/sections/css_extended.txt
> +siver.com.ua#?#.sidebox > div.sidetitle > span:contains("Купуй українське!")
Полоска все-таки блоки разделяет как часть дизайна.

2020-12-22 17:13 UTC, Sergey-Lyapin commented on RussianFilter/sections/css_extended.txt
> +siver.com.ua#?#.sidebox > div.sidetitle > span:contains("Купуй українське!")
имхо это часть заголовка, у нее даже название класса side title

2020-12-22 17:49 UTC, Sergey-Lyapin commented on RussianFilter/sections/css_extended.txt
> +siver.com.ua#?#.sidebox > div.sidetitle > span:contains("Погода")
в widgets.txt, под этот комментарий:
`!* Weather widgets`

2020-12-23 10:36 UTC, zloyden requested changes

2020-12-23 10:36 UTC, zloyden commented on RussianFilter/sections/specific.txt
> +||eukraina.com/informer/$third-party,domain=siver.com.ua
I'd leave only the `third-party` modificator.

2020-12-23 10:59 UTC, Sergey-Lyapin commented on RussianFilter/sections/css_extended.txt
> +siver.com.ua#?#.sidebox > div.sidetitle > span:contains("Погода")
@stanislav-atr

2020-12-23 11:01 UTC, zloyden commented on RussianFilter/sections/css_extended.txt
> +siver.com.ua#?#.sidebox > div.sidetitle > span:contains("Погода")
Also please changes those ext-css rules to something like this `siver.com.ua#?##sidebar > div.sidebox:has(> div.sidetitle > span:contains("/Купуй українське!|Реклама/"))`. It's the same for the weather widget.

2020-12-23 11:12 UTC, zloyden approved these changes

2020-12-23 11:12 UTC, merged