fix #70283 obmenvsem.org
AdguardTeam/AdguardFilters pull request #70541
Opened 2020-12-21 16:44 UTC by stanislav-atr

#70283

2020-12-22 09:54 UTC, Sergey-Lyapin requested changes
Лучше заблокировать запросы к рекламным серверам и добавить домен к регекспу, который блочит сторонние скрипты

2020-12-22 10:20 UTC, stanislav-atr commented
Там два одинаковых внешне видов баннера, один загружается со скриптов, добавил домен к регексу, а второй загружается инлайново — порезал картинки.
Оба `##` правила для флажка "Реклама", в зависимости от того, откуда взялся баннер, у них разная верстка.

2020-12-22 17:30 UTC, Sergey-Lyapin commented
```
||fqurmqe6agjyofb.ru^$third-party
||icjceddecjdgbaaaafc.ru^$third-party
```
Добавь еще эти правила в adservers (регексп не сработает на всех платформах)

2020-12-23 12:52 UTC, zloyden commented on RussianFilter/sections/specific.txt
> +obmenvsem.org###page_wrap > div.item[style="padding: 5px; margin: 0;"]
Не вижу применения этого правила `obmenvsem.org###page_wrap > div.item[style="padding: 5px; margin: 0;"]`

2020-12-23 13:26 UTC, Sergey-Lyapin commented on RussianFilter/sections/specific.txt
> +obmenvsem.org###page_wrap > div.item[style="padding: 5px; margin: 0;"]
Оно ярлык "реклама" убирает на одной из страниц, имхо лучше obmenvsem.org##img[src="/static/images/nashpek.png"] использовать
@stanislav-atr

2020-12-23 14:16 UTC, zloyden commented on RussianFilter/sections/specific.txt
> +obmenvsem.org###page_wrap > div.item[style="padding: 5px; margin: 0;"]
Хм, тогда проще этим `||obmenvsem.org/static/images/nashpek.png`

2020-12-23 14:27 UTC, zloyden approved these changes

2020-12-23 14:28 UTC, merged

2020-12-23 14:28 UTC, Sergey-Lyapin commented on RussianFilter/sections/specific.txt
> +obmenvsem.org###page_wrap > div.item[style="padding: 5px; margin: 0;"]
ну там 10px пустого места останется

2020-12-23 14:33 UTC, zloyden commented on RussianFilter/sections/specific.txt
> +obmenvsem.org###page_wrap > div.item[style="padding: 5px; margin: 0;"]
Ок, убрал его. В целом норм.