fix #71629 nevasport.ru
AdguardTeam/AdguardFilters pull request #72640
Opened 2021-01-19 11:23 UTC by stanislav-atr

#71629

2021-01-20 18:54 UTC, Alex-302 requested changes

2021-01-20 18:54 UTC, Alex-302 commented on AnnoyancesFilter/sections/tweaks.txt
> +nevasport.ru#$#.main-wrapper { margin-top: 0 !important; }
не сработает с программой

2021-01-20 18:54 UTC, Alex-302 commented on RussianFilter/sections/specific.txt
> +nevasport.ru###single-sidebar
слишком широкое, потенциально ломающее. Внутри есть однозначные элементы.

2021-01-20 18:54 UTC, Alex-302 commented on SocialFilter/sections/specific.txt
> +nevasport.ru##.post-tags
много скроет. Перепроверь.

2021-01-20 18:54 UTC, Alex-302 commented on SocialFilter/sections/specific.txt
> +nevasport.ru##.post-signature__social
Это обычные ссылки.

2021-01-21 10:09 UTC, stanislav-atr commented on AnnoyancesFilter/sections/tweaks.txt
> +nevasport.ru#$#.main-wrapper { margin-top: 0 !important; }
Варианты, которые работают в десктопе, ломают мобильную верстку.

2021-01-22 17:45 UTC, Alex-302 approved these changes

2021-01-22 17:45 UTC, merged