Issue labeler
AdguardTeam/AdguardFilters pull request #72839
Opened 2021-01-21 16:48 UTC by slavaleleka

1. first of all, there is an issue with `A: Resolved` label which will be removed if filters issue was closed and now is opening (usually it happens after newer cases reported) https://github.com/AdguardTeam/ReportsWebApp/issues/112

2. also I noticed that a lot of closed issues are marked by `A: In progress`. I assume the label is just forgotten and it is not left on purpose so I've made it's auto-removing on issue close

3. I suggest to mark issue by `A: In progress` label when it got assigned

4. one more thing. I haven't done in this PR yet but thought about it —deal with label `A: Cannot reproduce` the same way as with `A: Resolved` (from [1])

2021-01-21 17:09 UTC, Alex-302 commented
2 - I use it for checking user's feedbacks) And remove this label regularly.

2021-01-22 08:30 UTC, ameshkov approved these changes

2021-01-22 17:47 UTC, Alex-302 requested changes
https://github.com/AdguardTeam/AdguardFilters/pull/72839#issuecomment-764799527

2021-01-25 10:43 UTC, Sergey-Lyapin commented
3. I think it is better to add the label manually to know when the de facto work started.

2021-01-26 16:04 UTC, Alex-302 approved these changes

2021-01-26 16:10 UTC, merged