fix #70882 krunker.io
AdguardTeam/AdguardFilters pull request #72908
Opened 2021-01-22 16:24 UTC by stanislav-atr

#70882

2021-01-26 12:59 UTC, Alex-302 commented
It does not work without AdGuard on my end
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/105848041-1e938300-5fe7-11eb-9a16-1a42116f5f28.png)

</details>

2021-01-26 15:43 UTC, stanislav-atr commented
> It does not work without AdGuard on my end

Works on my side atm. It might be better to go for direct URL `krunker.io`  as it sometimes wont load correctly if coming from `krunker.io/&game=*
`

2021-01-26 16:08 UTC, Alex-302 commented on EnglishFilter/sections/antiadblock.txt
> +! https://github.com/AdguardTeam/AdguardFilters/issues/70882
Please try to block some requests by `redirect rules`(In addition to these rules, with `important`)

2021-01-26 17:44 UTC, Alex-302 requested changes

2021-01-26 17:44 UTC, Alex-302 commented on EnglishFilter/sections/antiadblock.txt
> +@@||secure.quantserve.com/quant.js$script,redirect=nooptext,important,domain=krunker.io
exclusions?

2021-02-02 08:10 UTC, zloyden approved these changes

2021-02-02 08:10 UTC, merged