fix #72135 c.mi.com
AdguardTeam/AdguardFilters pull request #73012
Opened 2021-01-23 14:07 UTC by stanislav-atr

#72135

2021-01-26 19:28 UTC, Alex-302 requested changes

2021-01-26 19:28 UTC, Alex-302 commented on AnnoyancesFilter/sections/cookies_specific.txt
> +mi.com##.cookie-setting-bottom-bar
там ещё попап в центре может быть. Лучше `div[id^="J_cookie_settings_"]`

2021-01-27 10:04 UTC, stanislav-atr commented on AnnoyancesFilter/sections/cookies_specific.txt
> +mi.com##.cookie-setting-bottom-bar
@Alex-302, центральный не воспроизвел, добавил #$# body { overflow: visible !important } на всякий случай

2021-01-27 10:09 UTC, Alex-302 approved these changes

2021-01-27 10:09 UTC, merged

2021-01-27 10:10 UTC, Alex-302 commented on AnnoyancesFilter/sections/cookies_specific.txt
> +mi.com##.cookie-setting-bottom-bar
с центральным будет нужен.