fix #72151 newgames.com
AdguardTeam/AdguardFilters pull request #73023
Opened 2021-01-23 17:12 UTC by stanislav-atr

#72151

2021-01-26 19:03 UTC, Alex-302 requested changes
есть же готовые правила в фильтре раздражителей, только домены добавить

2021-01-27 09:38 UTC, stanislav-atr commented
> есть же готовые правила в фильтре раздражителей, только домены добавить

@Alex-302,
Похоже, они успели что-то поменять, потому что корневой div теперь с `.fc-ab-root`, посмотри у себя, пожалуйста, и я поменяю селектор
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/68852737/105972191-6c1df780-609c-11eb-9293-0132d2e04906.png)
</details><br/>

2021-01-27 10:10 UTC, Alex-302 commented
`.fc-ab-root` у меня.

2021-01-27 15:09 UTC, Alex-302 approved these changes

2021-01-27 15:09 UTC, merged