epson-event-manager-utility.en.lo4d.com
AdguardTeam/AdguardFilters pull request #73363
Opened 2021-01-27 16:10 UTC by gork7777

2021-01-27 16:12 UTC, wout-codes approved these changes

2021-01-28 06:29 UTC, zloyden requested changes

2021-01-28 06:29 UTC, zloyden commented on EnglishFilter/sections/specific.txt
> +epson-event-manager-utility.en.lo4d.com##.small
Too wide rule. It hides a lot, I'll change it.

2021-01-28 06:30 UTC, zloyden approved these changes

2021-01-28 06:31 UTC, merged