fix #73697 novelgo.id
AdguardTeam/AdguardFilters pull request #73699
Opened 2021-01-31 11:14 UTC by wout-codes

#73697

2021-02-05 11:10 UTC, Alex-302 commented
I don't see BAB script here. Can you reproduce it now?

2021-02-05 11:12 UTC, wout-codes commented
> I don't see BAB script here. Can you reproduce it now?

Yes @Alex-302 
![image](https://user-images.githubusercontent.com/76908410/107026750-21ac2180-67e6-11eb-8b8a-6f0c249ab2e7.png)

2021-02-05 11:22 UTC, Alex-302 approved these changes

2021-02-05 11:26 UTC, Alex-302 requested changes

2021-02-05 11:26 UTC, Alex-302 commented on EnglishFilter/sections/specific.txt
> +novelgo.id##div[class^="code-block-label"]
Wrong file. => foreign.txt => Indonesian

2021-02-05 11:40 UTC, wout-codes commented on EnglishFilter/sections/specific.txt
> +novelgo.id##div[class^="code-block-label"]
Fixed @Alex-302

2021-02-05 14:42 UTC, wout-codes commented on EnglishFilter/sections/specific.txt
> +novelgo.id##div[class^="code-block-label"]
@Alex-302 ?

2021-02-08 05:45 UTC, wout-codes commented
@Alex-302 @zloyden Can anyone of you merge this? Approved 3 days ago but still not merged.

2021-02-08 05:52 UTC, zloyden commented
> Approved 3 days ago but still not merged.

I guess @Alex-302 noticed it https://github.com/AdguardTeam/AdguardFilters/pull/73699#discussion_r570901529.
I'll take a look.

2021-02-08 05:52 UTC, zloyden approved these changes

2021-02-08 05:54 UTC, merged