Fix #74246 redirect-ads.com
AdguardTeam/AdguardFilters pull request #74369
Opened 2021-02-08 15:10 UTC by AdamWr

Issue - https://github.com/AdguardTeam/AdguardFilters/issues/74246

Fix popups from `hydrax/redirect-ads.com` video player.

Code - https://gist.github.com/AdamWr/4b51c6b7c2d7bd22ba2e14f5d3ffe0b4

In this case, `redirect-ads.com#%#//scriptlet("prevent-window-open")` can't be used, because it breaks website.
It's due to `win.focus();` part from their script:
```js
var win = window.open("test");
win.focus();
setTimeout(() => {
  if (win && !win.closed) {
    // [...]
  }
}, 50);

2021-02-08 15:29 UTC, slavaleleka commented
`redirect-ads.com#%#//scriptlet('prevent-window-open', '1', '', '{focus=noopFunc}')` helps me with it

2021-02-08 15:33 UTC, AdamWr commented
`redirect-ads.com#%#//scriptlet('prevent-window-open', '1', '', '{focus=noopFunc}')`
It breaks video player on my end.

2021-02-08 15:49 UTC, AdamWr commented
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/107243224-14cd3f00-6a2d-11eb-8bab-f7c9be29da3a.png)

</details>

The same happens on http://example.org/ with this rule:
`example.org,redirect-ads.com#%#//scriptlet('prevent-window-open', '1', '', '{focus=noopFunc}')`
if I run this code:
```js
var win = window.open("test");
win.focus();
setTimeout(() => {
  if (win && !win.closed) {
    console.log("Test");
  }
}, 50);
```

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/107243454-4d6d1880-6a2d-11eb-9685-f56be6aed33e.png)

</details>

2021-02-08 20:54 UTC, ameshkov commented
@slavaleleka interesting, shouldn't we implement some changes to `prevent-window-open`?

2021-02-08 20:58 UTC, ameshkov requested changes

2021-02-08 20:58 UTC, ameshkov commented on EnglishFilter/sections/general_extensions.txt
> +redirect-ads.com#%#(function(){if("function"===typeof Proxy){var a=/^./,c=function(){var b=document.createElement("iframe");b.src=a;b.style.setProperty("height","1px","important");b.style.setProperty
Please add a comment here:
`! TODO: replace with "prevent-window-open" scriptlet after https://github.com/AdguardTeam/Scriptlets/issues/117`

2021-02-08 21:05 UTC, AdamWr commented on EnglishFilter/sections/general_extensions.txt
> +redirect-ads.com#%#(function(){if("function"===typeof Proxy){var a=/^./,c=function(){var b=document.createElement("iframe");b.src=a;b.style.setProperty("height","1px","important");b.style.setProperty
Done.

2021-02-08 21:17 UTC, ameshkov approved these changes

2021-02-09 14:18 UTC, Alex-302 approved these changes

2021-02-09 14:23 UTC, merged