fix #74116 tw.iqiyi.com
AdguardTeam/AdguardFilters pull request #74705
Opened 2021-02-12 13:14 UTC by Edsuns

Fix #74116

2021-02-12 16:03 UTC, Alex-302 requested changes

2021-02-12 16:03 UTC, Alex-302 commented on AnnoyancesFilter/sections/annoyances.txt
> +iqiyi.com##iqpdiv[data-cupid=container],div[adid]
Hi.
We prefer to not add more than one selector to one rule. Please change to two rules

2021-02-15 06:32 UTC, zloyden approved these changes

2021-02-15 06:33 UTC, zloyden commented
Hi! Thanks for your contribution:)

2021-02-15 06:33 UTC, merged