fix #74888 animax.to
AdguardTeam/AdguardFilters pull request #74889
Opened 2021-02-14 11:42 UTC by wout-codes

#74888

2021-02-15 09:13 UTC, Yuki2718 requested changes
~~Hmm.. I thought I commented but apparently not~~ [EDIT] Found my comment. Add
`||animax.to/ax.js`
as `window._run` is defined by this. You can still keep the scriptlet, the site may change file path.

2021-02-15 09:15 UTC, wout-codes commented on EnglishFilter/sections/specific.txt
> +animax.*##[src*="//a.exdynsrv.com/iframe.php"]
I can reproduce it with only AdGuard App Do not why though.

2021-02-15 09:16 UTC, wout-codes commented on EnglishFilter/sections/general_extensions.txt
> +animax.*#%#//scriptlet("abort-on-property-read", "_run")
Ok sure.

2021-02-15 09:17 UTC, Yuki2718 commented on EnglishFilter/sections/specific.txt
> +animax.*##[src*="//a.exdynsrv.com/iframe.php"]
What exactly is the AdGuard App? AdGuard for Windows?

2021-02-15 09:18 UTC, wout-codes commented on EnglishFilter/sections/general_extensions.txt
> +animax.*#%#//scriptlet("abort-on-property-read", "_run")
I will still keep the scriptlet.

2021-02-15 09:18 UTC, wout-codes commented on EnglishFilter/sections/specific.txt
> +animax.*##[src*="//a.exdynsrv.com/iframe.php"]
Yes

2021-02-15 09:20 UTC, wout-codes commented on EnglishFilter/sections/specific.txt
> +animax.*##[src*="//a.exdynsrv.com/iframe.php"]
I need more evidence then I will file an issue in AdGuard for Windows Bug Tracker Repository. My goal is to make the AdGuard App support `$popup` modifier and this placeholder issue.

2021-02-15 09:40 UTC, Yuki2718 approved these changes

2021-02-15 09:41 UTC, Yuki2718 commented
Whoops, `||animax.to/ax.js` should be in specific.txt

2021-02-17 07:00 UTC, zloyden approved these changes

2021-02-17 07:01 UTC, merged