fix #74605 tuttosport.com
AdguardTeam/AdguardFilters pull request #74987
Opened 2021-02-15 16:32 UTC by stanislav-atr

#74605

2021-02-15 16:38 UTC, AdamWr commented
If I'm not wrong these requests are blocked by `AdGuard Annoyances filter`, so shouldn't it be fixed in Annoyances filter - `cookies_whitelist.txt`?

2021-02-16 05:29 UTC, zloyden requested changes

2021-02-16 05:29 UTC, zloyden commented on EnglishFilter/sections/foreign.txt
> +@@||privacy-center.org/sdk.*.js$domain=tuttosport.com
Wrong filter. Look at the @AdamWr [post](https://github.com/AdguardTeam/AdguardFilters/pull/74987#issuecomment-779335609).

2021-02-16 08:28 UTC, zloyden approved these changes

2021-02-16 08:29 UTC, merged