fix #74672 sex1014004.pixnet.net
AdguardTeam/AdguardFilters pull request #75144
Opened 2021-02-17 15:42 UTC by stanislav-atr

#74672

2021-02-24 17:59 UTC, Alex-302 requested changes

2021-02-24 17:59 UTC, Alex-302 commented on EnglishFilter/sections/foreign.txt
> +sex1014004.pixnet.net##a[href^="https://goo.gl/]
better `pixnet.net##a[onmouseover^="MM_openBrWindow"]`. Same banner on many other subdomains.
Scriptlet also can be applied to the main domain.

2021-02-25 09:21 UTC, zloyden requested changes

2021-02-25 09:21 UTC, zloyden commented on SocialFilter/sections/specific.txt
> +sex1014004.pixnet.net##.bookmark
We have similar rules with `##.bookmark`. Make one rule and I guess `pixnet.net` is better here.

2021-02-25 09:39 UTC, zloyden approved these changes

2021-02-25 09:40 UTC, merged