wiez.pl
AdguardTeam/AdguardFilters pull request #75435
Opened 2021-02-20 19:20 UTC by gork7777

2021-02-20 21:52 UTC, krystian3w requested changes
<!-- -->

2021-02-20 21:53 UTC, krystian3w commented
Maybe omitted:

```
##.post-socials-box
```

![obraz](https://user-images.githubusercontent.com/35370833/108609462-55826c00-73ce-11eb-92ba-f68e9063bb4f.png)

2021-02-21 14:53 UTC, krystian3w approved these changes

2021-02-22 11:22 UTC, AdamWr approved these changes

2021-02-22 11:22 UTC, merged