fix #76066 tribunapr.uol.com.br
AdguardTeam/AdguardFilters pull request #76068
Opened 2021-02-28 05:57 UTC by wout-codes

#76066

2021-03-01 16:31 UTC, Alex-302 requested changes

2021-03-02 00:18 UTC, wout-codes commented on SpanishFilter/sections/specific.txt
> +tribunapr.uol.com.br,veja.abril.com.br,odia.ig.com.br,especiais.g1.globo.com,tribunapr.com.br,novelasd.com,anime-tube.tv##.ads
Ok I will remove from the common rule and it above.

2021-03-02 10:29 UTC, Alex-302 approved these changes

2021-03-02 10:29 UTC, Alex-302 commented on SpanishFilter/sections/specific.txt
> +tribunapr.uol.com.br,veja.abril.com.br,odia.ig.com.br,especiais.g1.globo.com,tribunapr.com.br,novelasd.com,anime-tube.tv##.ads
Thanks.

2021-03-02 10:29 UTC, merged