fix #75593 nownews.com
AdguardTeam/AdguardFilters pull request #76099
Opened 2021-02-28 10:50 UTC by stanislav-atr

#75593

2021-03-01 18:43 UTC, Alex-302 commented on EnglishFilter/sections/foreign.txt
> +nownews.com##.adBlk
Сайт же только на китайском вроде.

2021-03-01 18:43 UTC, Alex-302 requested changes

2021-03-01 18:43 UTC, Alex-302 commented on SocialFilter/sections/specific.txt
> +nownews.com##.infoBlk
Ломаешь сайт. Проверь десктопную версию.

2021-03-02 10:29 UTC, stanislav-atr commented on SocialFilter/sections/specific.txt
> +nownews.com##.infoBlk
@Alex-302, вообще стоит удалять этот элемент? Обычно e-mail кнопки не убираем, но эта расположена не очень.

2021-03-02 10:42 UTC, Alex-302 commented on SocialFilter/sections/specific.txt
> +nownews.com##.infoBlk
Ну если блок выглядит как шарилка - то кнопка с почтой - просто остаток, соотв. лучше скрыть.

2021-03-02 10:44 UTC, Alex-302 requested changes

2021-03-02 10:44 UTC, Alex-302 commented on SocialFilter/sections/css_extended.txt
> +nownews.com#?#.titleBlk > div.infoBlk:has(> ul.share)
и так ломаешь

2021-03-02 13:21 UTC, Alex-302 approved these changes

2021-03-02 13:21 UTC, merged