fix #76418 rtvi.com
AdguardTeam/AdguardFilters pull request #76420
Opened 2021-03-03 14:14 UTC by wout-codes

#76418

2021-03-03 19:35 UTC, Alex-302 requested changes

2021-03-03 19:35 UTC, Alex-302 commented on RussianFilter/sections/css_extended.txt
> +rtvi.com#?#.aside-info:contains(adfox_)
better 
```
rtvi.com##.div-adv
rtvi.com##div[data-banner-name]
```

2021-03-04 00:24 UTC, wout-codes commented on RussianFilter/sections/css_extended.txt
> +rtvi.com#?#.aside-info:contains(adfox_)
Added.

2021-03-04 11:31 UTC, Alex-302 approved these changes

2021-03-04 11:31 UTC, merged