fromsmash.com
AdguardTeam/AdguardFilters pull request #76446
Opened 2021-03-03 22:24 UTC by gork7777

2021-03-04 06:33 UTC, wout-codes commented
@gork7777 Potential duplicate.

2021-03-04 06:50 UTC, zloyden requested changes

2021-03-04 06:50 UTC, zloyden commented on AnnoyancesFilter/sections/popups.txt
> +diziweb.net,tfc.tv,bkv.hu,catwalkyourself.com,baba-mail.co.il,egyptianstreets.com,ports.com.ua,bitfeed.co,calkalasutasayrani.com,sk7mobile.com,blogkurdu.net,opensnow.com,watch5s.rs##.modal-backdrop
This one we've investigated with @wout-codes here https://github.com/AdguardTeam/AdguardFilters/pull/76412. Please remove this changes, but you can help find obsolete domains that don't need this rule.

2021-03-05 06:21 UTC, zloyden commented
Too many different changes here, I fixed it directly.

2021-03-05 06:21 UTC, closed without merging