blocksite.co
AdguardTeam/AdguardFilters pull request #76711
Opened 2021-03-05 15:44 UTC by gork7777

issue: #76629

2021-03-09 19:38 UTC, Alex-302 requested changes
login popup is blocked

2021-03-09 21:46 UTC, gork7777 commented
`##.dialog-lightbox-widget-content` (Wait a second) do you mean this popup?

2021-03-09 21:49 UTC, Alex-302 commented
Yes.

2021-03-10 13:17 UTC, Alex-302 commented
Better do nothing here.

2021-03-10 13:17 UTC, closed without merging