fix #76277 kakoysegodnyaprazdnik.ru
AdguardTeam/AdguardFilters pull request #77048
Opened 2021-03-09 16:13 UTC by stanislav-atr

#76277

2021-03-14 18:34 UTC, Alex-302 requested changes
Сообщение про использование блокировщика не убрано
![image](https://user-images.githubusercontent.com/8361299/111079863-9caed900-8504-11eb-94af-0495559c883b.png)
а правилом сломан сайт

2021-03-15 14:29 UTC, zloyden commented on RussianFilter/sections/specific.txt
> +kakoysegodnyaprazdnik.ru##div[id] > div[style="padding-top:5px;"]
Не нашел применения этого правила.

2021-03-15 14:33 UTC, zloyden requested changes

2021-03-15 14:33 UTC, zloyden commented on AnnoyancesFilter/sections/antiadblock.txt
> +kakoysegodnyaprazdnik.ru###rtb_place
Как тебе [написал ](https://github.com/AdguardTeam/AdguardFilters/pull/77048#pullrequestreview-611724842)@Alex-302 , это правило не везде убирает детект адблока. Скриптлет тут норм `kakoysegodnyaprazdnik.ru#%#//scriptlet("prevent-addEventListener", "load", "window.google_jobrunner")` и его в языковой лучше добавить, поскольку затрагивается функционал.
Для кб платформ исключения.

2021-03-15 14:35 UTC, zloyden commented on AnnoyancesFilter/sections/antiadblock.txt
> +kakoysegodnyaprazdnik.ru###rtb_place
Посмотри еще старые правила, может есть уже неактуальные.

2021-03-16 06:44 UTC, zloyden commented
Поправил напрямую.

2021-03-16 06:44 UTC, closed without merging