Fixes Some Popups
AdguardTeam/AdguardFilters pull request #77745
Opened 2021-03-17 11:15 UTC by wout-codes

2021-03-17 12:19 UTC, wout-codes commented
I am already tempted to make this `$$script[wildcard="*function*break;case*"][min-length="30000"][max-length="85000"]` and `#%#//scriptlet("abort-current-inline-script", "String.fromCharCode", "/emZnbG9hZGVk|break;case \$\.|break;case \d{1}/")`, generic rules. There are a lot of domains already and sites uses this code most of the time to generate popups. @Alex-302 @AdamWr @zloyden What do you think?

2021-03-17 14:15 UTC, ghajini commented on EnglishFilter/sections/general_extensions.txt
> +080phds.com,123-watch.com,123moviesco.site,1kmovies.org,afilmyhouse.blogspot.com,antsmovies.com,europix.us,fmoviess.site,maamusiq.com,movi.pk,thesouthflix.com,timesofurdu.website,tnmoviez.net,yify.st
@wout-codes 
typo 
080phds.com > 1080phds.com

2021-03-17 14:18 UTC, wout-codes commented on EnglishFilter/sections/general_extensions.txt
> +080phds.com,123-watch.com,123moviesco.site,1kmovies.org,afilmyhouse.blogspot.com,antsmovies.com,europix.us,fmoviess.site,maamusiq.com,movi.pk,thesouthflix.com,timesofurdu.website,tnmoviez.net,yify.st
Thanks.

2021-03-22 09:33 UTC, wout-codes commented
@zloyden Can you review this please?

2021-03-22 14:40 UTC, zloyden commented
@wout-codes I'll review it later, there are many changes.

2021-03-22 15:20 UTC, zloyden requested changes

2021-03-22 15:20 UTC, zloyden commented on EnglishFilter/sections/general_extensions.txt
> +ovagames.com,oladblock.me,oladblock.xyz,oladblock.services,oload.space,oload.live,oload.club,openload.pw,oload.fun#%#window.open = function() {}; document.cookie = "popcashpuCap=1"; Object.defineProp
`ovagames.com - popups` without `!`.
What's the point of adding the domain here `#%#window.open = function() {}; document.cookie = "popcashpuCap=1"; Object.defineProperty(window,'turnoff',{value:true}); Object.defineProperty(window, 'preserve', { get: function() { return true; } });`?

It seems only `window.open = function() {};` is useful here, the others are not.
So, the popup is fixed by `||zxclan.com^$third-party`, but you can also add `ovagames.com#%#//scriptlet("set-constant", "window.open", "noopFunc")`.

2021-03-23 06:27 UTC, zloyden approved these changes

2021-03-23 06:32 UTC, merged