fix #77772 puhekupla.com
AdguardTeam/AdguardFilters pull request #77821
Opened 2021-03-18 09:23 UTC by wout-codes

#77772

2021-03-18 13:29 UTC, Alex-302 requested changes

2021-03-18 13:29 UTC, Alex-302 commented on EnglishFilter/sections/antiadblock.txt
> +puhekupla.com#@#.googlead
just notification. To Annoyances.

2021-03-18 13:30 UTC, wout-codes commented on EnglishFilter/sections/antiadblock.txt
> +puhekupla.com#@#.googlead
Okay.

2021-03-19 06:43 UTC, zloyden approved these changes

2021-03-19 06:44 UTC, merged