www.cicekal.net
AdguardTeam/AdguardFilters pull request #78209
Opened 2021-03-22 15:55 UTC by gork7777

issue: #78194

2021-03-22 21:16 UTC, Sergey-Lyapin requested changes

2021-03-22 21:16 UTC, Sergey-Lyapin commented on TurkishFilter/sections/whitelist.txt
> +cicekal.net#@#.share-container
please move to social whitelist

2021-03-23 15:03 UTC, gork7777 commented
This shouldn't be blocked cause this rule is blocking body of site

2021-03-24 07:11 UTC, zloyden approved these changes

2021-03-24 07:11 UTC, merged