Fix/#78092 www.hltv.org
AdguardTeam/AdguardFilters pull request #78509
Opened 2021-03-26 12:28 UTC by stanislav-atr

#78092

2021-03-26 12:45 UTC, wout-codes reviewed
These rules do nothing on my end.

2021-03-26 12:47 UTC, wout-codes reviewed
`hltv.org##div[class*="ASdvuasdr123Gazx"]` This is like to change.

2021-03-26 12:49 UTC, wout-codes reviewed
There is also a popup window which you have missed.

2021-03-30 10:12 UTC, Sergey-Lyapin requested changes
Please investigate this site again
Only these rules look necessary:

```
hltv.org##.pari-match
hltv.org##div[class*="ASdvuasdr123Gazx"]
||intersc.igaming-service.io/hltv.org.js
||hltv.org/scripts/hltv-tracking.js
```

And this site is not russian, so rules must be added to the base filter

2021-03-30 10:23 UTC, Sergey-Lyapin commented on RussianFilter/sections/specific.txt
> +hltv.org##.footer-app
We should not remove links to mobile apps in the footer.

2021-03-30 10:24 UTC, wout-codes commented
@Sergey-Lyapin @stanislav-atr Most of the ads were fixed in EasyList. Only a `GGBet` banner is on the top of the page. So I recommend to changes these rules.

```
||intersc.igaming-service.io/hltv.org.js
||hltv.org/scripts/hltv-tracking.js
hltv.org#%#//scriptlet("remove-attr", "data-href", "body[class]")
hltv.org##.featured-matches-top
```

2021-03-30 10:32 UTC, zloyden commented
@stanislav-atr also check old rules for this site.

2021-03-31 10:46 UTC, zloyden approved these changes

2021-03-31 10:46 UTC, merged

2021-03-31 10:52 UTC, Alex-302 approved these changes