Fix #78268 websdr.space
AdguardTeam/AdguardFilters pull request #78872
Opened 2021-03-30 08:35 UTC by stanislav-atr

#78268

2021-03-30 09:00 UTC, zloyden requested changes
Пропущены остатки (есть такой же в подвале)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/112962836-78333d80-914f-11eb-8824-db063fdd6e21.png)

</details><br/>

2021-03-30 09:01 UTC, zloyden commented on RussianFilter/sections/antiadblock.txt
> +websdr.space#$#div[id^="LirAreNaThErelB"] { height: 2px!important; }
Что насчет контент блокеров?

2021-03-31 09:20 UTC, stanislav-atr commented
> Пропущены остатки (есть такой же в подвале)
> 
> Screenshot:
> ![image](https://user-images.githubusercontent.com/33488229/112963386-fd1e5700-914f-11eb-9820-853bb4c94fd4.png)

@zloyden, removing these leftouts triggers antiadblock on my side, please, check this out.

2021-03-31 12:24 UTC, zloyden commented
> @zloyden, removing these leftouts triggers antiadblock on my side, both with `#$#` rule and scriptlet.

Со скриптлетом точно не повторяется.
Попробуй эти
```
websdr.space#%#//scriptlet("prevent-setTimeout", "5e3", "7000")
websdr.space#?##wrapper div.card > div.card-body > div.text-center div[id^="yandex_rtb"]:upward(div.card)
```

Для кб платформ
```
@@||an.yandex.ru/meta/$domain=websdr.space
@@||an.yandex.ru/system/context.js$domain=websdr.space
```

2021-03-31 12:34 UTC, zloyden approved these changes

2021-03-31 12:34 UTC, merged