www.annaclemens.com
AdguardTeam/AdguardFilters pull request #79148
Opened 2021-04-02 08:25 UTC by gork7777

issue: #79127

2021-04-02 08:28 UTC, wout-codes commented
@gork7777 There is a share button at the below of the article, also two newsletters.

2021-04-02 08:43 UTC, gork7777 commented
Community and Guide newsletter, right?

2021-04-02 08:48 UTC, wout-codes commented
Yeah and a share button

2021-04-07 12:13 UTC, Alex-302 requested changes

2021-04-07 12:13 UTC, Alex-302 commented on AnnoyancesFilter/sections/annoyances.txt
> +annaclemens.com##.image-block
this rule breaks content. Better remove it.

2021-04-07 12:13 UTC, Alex-302 commented on AnnoyancesFilter/sections/annoyances.txt
> +annaclemens.com##._form_27
Better block widget `||activehosted.com^$third-party`

2021-04-07 14:54 UTC, Alex-302 commented on EnglishFilter/sections/adservers.txt
> +||activehosted.com^$third-party
no. This is annoyance. Please move to this section:
https://github.com/AdguardTeam/AdguardFilters/blob/d0084bf95ad0616a03e927456c51d25d660134a6/AnnoyancesFilter/sections/annoyances.txt#L1760

2021-04-07 18:25 UTC, Alex-302 approved these changes

2021-04-07 18:26 UTC, merged