fix #79089 2gis.ru
AdguardTeam/AdguardFilters pull request #79547
Opened 2021-04-05 16:43 UTC by stanislav-atr

#79089

2021-04-05 16:52 UTC, Alex-302 commented on RussianFilter/sections/css_extended.txt
> +2gis.ru#?#div > div[class]:has(> div[style^="margin:0px undefinedpx;"] div[class] > div > div[title="Реклама"] )
Остальные домены проверил?

2021-04-05 16:53 UTC, Alex-302 commented on RussianFilter/sections/css_extended.txt
> +2gis.ru#?#div > div[class]:has(> div[style^="margin:0px undefinedpx;"] div[class] > div > div[title="Реклама"] )
заодно старые правила перепроверь

2021-04-06 08:52 UTC, stanislav-atr commented
I've changed `div[style^="margin:0px undefinedpx;"]` to `div[style]` because  default style changes to `[style^="left: 0px; transition: left 200ms"]` on some ocasions (when ad card is the only one).

2021-04-06 14:42 UTC, Alex-302 requested changes

2021-04-06 14:42 UTC, Alex-302 commented on RussianFilter/sections/css_extended.txt
> +2gis.*#?#div > div[class]:has(> div[style] div[class] > div > div[title="Реклама"] )
этим правилом ты ломаешь сайт, причём полностью.
Там есть к чему привязаться
![image](https://user-images.githubusercontent.com/8361299/113728914-2e25fb00-96ff-11eb-896c-9c3e7ac94a13.png)
![image](https://user-images.githubusercontent.com/8361299/113728948-367e3600-96ff-11eb-861a-b9545ef47dbd.png)

2021-04-15 12:32 UTC, Alex-302 requested changes

2021-04-15 12:32 UTC, Alex-302 commented on RussianFilter/sections/css_extended.txt
> +2gis.*#?#div > div[class]:has(> div[style] > div[style="min-width: 100%; max-width: 100%;"])
первая часть правила не имеет смысла. Смотри внимательнее
![image](https://user-images.githubusercontent.com/8361299/114869427-a24b5780-9dff-11eb-821e-54ab208dae4c.png)
и проверь чтоб региональные сайты не поломало.

2021-04-21 20:37 UTC, closed without merging