fix #79063 rustorka.com
AdguardTeam/AdguardFilters pull request #79607
Opened 2021-04-06 10:45 UTC by stanislav-atr

#79063

2021-04-13 13:50 UTC, Alex-302 commented on RussianFilter/sections/general_extensions.txt
> +rustorka.com,rustorka.net#%#document.cookie = “opt_js2=opt_js2; path=/;“;
зеркала не забывай
naylo.top,rustorka.com,rustorka.net,rustorkacom.lib

2021-04-15 12:34 UTC, Alex-302 requested changes

2021-04-15 12:34 UTC, Alex-302 commented on RussianFilter/sections/general_extensions.txt
> +naylo.top,rustorka.com,rustorka.net,rustorkacom.lib,rustorka.com,rustorka.net#%#document.cookie = “opt_js2=opt_js2; path=/;“;
попап 
![image](https://user-images.githubusercontent.com/8361299/114869752-079f4880-9e00-11eb-914b-a3046c20087f.png)

2021-04-15 16:05 UTC, stanislav-atr commented on RussianFilter/sections/general_extensions.txt
> +naylo.top,rustorka.com,rustorka.net,rustorkacom.lib,rustorka.com,rustorka.net#%#document.cookie = “opt_js2=opt_js2; path=/;“;
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/68852737/114901452-7d65dd00-9e1d-11eb-96c0-a3c12942a924.png)
</details><br/>
Блочится в хроме, с включенным AG даже оповещения не появляется.

2021-04-19 09:51 UTC, Alex-302 approved these changes

2021-04-19 09:51 UTC, merged