fix #78651 pikabu.ru
AdguardTeam/AdguardFilters pull request #79622
Opened 2021-04-06 13:05 UTC by stanislav-atr

#78651

2021-04-06 13:57 UTC, Alex-302 requested changes

2021-04-06 13:57 UTC, Alex-302 commented on RussianFilter/sections/specific.txt
> +pikabu.ru##.stories-feed__message
![image](https://user-images.githubusercontent.com/8361299/113722482-2400fe00-96f9-11eb-8fb4-cce4cbaa5f7b.png)
ломаешь

2021-04-15 12:26 UTC, Alex-302 commented on RussianFilter/sections/specific.txt
> +pikabu.ru##.stories-feed__message
Не вижу второго элемента в коде.

2021-04-16 13:45 UTC, stanislav-atr commented
I've checked the issue again and only found this element
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/68852737/115033108-b4e29100-9ed2-11eb-809f-97d3d7361cad.png)
</details><br/>
so i swapped the rule to 
`#?#.main__content > section.stories-feed__message:has(> div[data-sid^="partners_widget_horizontal_"])`
to remove the leftover for both extension and desktop, Chrome + Firefox.

2021-04-21 20:52 UTC, Alex-302 approved these changes

2021-04-21 20:53 UTC, Alex-302 requested changes

2021-04-21 20:53 UTC, Alex-302 commented on RussianFilter/sections/css_extended.txt
> +pikabu.ru#?##?#.main__content > section.stories-feed__message:has(> div[data-sid^="partners_widget_horizontal_"])
invalid rule

2021-04-21 20:53 UTC, closed without merging