fix #79884 irodorich.com
AdguardTeam/AdguardFilters pull request #79969
Opened 2021-04-09 15:36 UTC by stanislav-atr

#79884

2021-04-09 16:01 UTC, Yuki2718 requested changes
`##.ad` hides blog description, latest comments etc too. Better to use extended syntax so that only Amazon ads are hidden. E.g. `irodorich.com#?#.side-amazon:upward(.ad)`

2021-04-09 16:04 UTC, Yuki2718 commented
Also add
```
irodorich.com##.gadpc_header
irodorich.com##.amaprop-side
```

2021-04-12 09:17 UTC, Yuki2718 approved these changes

2021-04-14 15:18 UTC, AdamWr approved these changes

2021-04-14 15:18 UTC, merged