fix #79892 www.ownedcore.com
AdguardTeam/AdguardFilters pull request #80248
Opened 2021-04-12 11:40 UTC by stanislav-atr

#79892

2021-04-12 11:50 UTC, wout-codes approved these changes

2021-04-15 13:20 UTC, AdamWr requested changes

2021-04-15 13:20 UTC, AdamWr commented on EnglishFilter/sections/specific.txt
> +ownedcore.com###sidebar > li > div.smaller:has(> div.blocksubhead > span:contains(Sponsored Ads))
@stanislav-atr Please add `?` to this rule -> `ownedcore.com#?##sidebar > li > div.smaller:has(> div.blocksubhead > span:contains(Sponsored Ads))` and move it to `css_extended.txt`

2021-04-16 12:04 UTC, Alex-302 commented on EnglishFilter/sections/specific.txt
> +ownedcore.com##a[href^="https://brobot.me/"][target="_blank"]
It can be blocked by `ownedcore.com##.b-below-so-wrapper`

2021-04-21 20:57 UTC, Alex-302 approved these changes

2021-04-21 21:28 UTC, merged