fix #79900 downdetector.it
AdguardTeam/AdguardFilters pull request #80412
Opened 2021-04-14 09:24 UTC by stanislav-atr

#79900

2021-04-15 19:25 UTC, Sergey-Lyapin commented on EnglishFilter/sections/whitelist.txt
> +@@||googletagservices.com/tag/js/gpt.js$script,redirect=googletagservices-gpt,domain=downdetector.it
@@ is not needed here and $redirect will not work in content blockers

2021-04-20 14:56 UTC, Alex-302 requested changes

2021-04-20 14:56 UTC, Alex-302 commented on EnglishFilter/sections/whitelist.txt
> +@@||googletagservices.com/tag/js/gpt.js$domain=downdetector.it
why removed redirect tule? It can be used here.
`||googletagservices.com/tag/js/gpt.js$script,redirect=googletagservices-gpt,domain=downdetector.it`

2021-04-20 19:44 UTC, Alex-302 approved these changes

2021-04-20 19:44 UTC, merged