fix #80281 www.nickles.de
AdguardTeam/AdguardFilters pull request #80439
Opened 2021-04-14 14:01 UTC by stanislav-atr

#80281

2021-04-15 09:30 UTC, AdamWr requested changes

2021-04-15 09:30 UTC, AdamWr commented on GermanFilter/sections/antiadblock.txt
> +nickles.de#%#//scriptlet('abort-current-inline-script', 'Nickles.Account')
@stanislav-atr  It seems that this rule breaks website.
For example on `https://www.nickles.de/signup/`, "Community Livefeed" is not displayed.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/114847018-86cf5500-9ddd-11eb-8edf-5122f364add3.png)

</details>

2021-04-15 12:32 UTC, AdamWr commented
@stanislav-atr It seems that current scriptlet works fine.
By the way, this notice looks like cookie wall, so I think that it should be added to Annoyances filter.

2021-04-15 13:55 UTC, BlazDT requested changes
New rule to Annoyances filter, It is no adblock. It just asks the user if he wants to continue either free and with ads or with an account.

2021-04-19 10:44 UTC, AdamWr commented on AnnoyancesFilter/sections/antiadblock.txt
> +nickles.de#%#//scriptlet('set-constant', 'Nickles.Consent.show', 'noopFunc')
I think that it would be better to move this rule to  `annoyances.txt`, because it's not an anti-adblock script.

2021-04-19 11:40 UTC, AdamWr approved these changes

2021-04-19 11:41 UTC, merged