Created AdGuard Tracking Parameters list
AdguardTeam/AdguardFilters pull request #80517
Opened 2021-04-15 09:37 UTC by Alex-302

https://github.com/AdguardTeam/AdguardFilters/issues/57197

2021-04-15 09:41 UTC, ameshkov requested changes
Waiting for the rules:)

2021-04-15 09:41 UTC, slavaleleka requested changes
directory name ('Filter' written twice)
https://uploads.adguard.com/slbdzdrq902u.png

2021-04-15 09:46 UTC, wout-codes commented on TrackParamFilterFilter/sections/specific.txt
> +! The rules for specific sites
Since you are not indicating specifically which site, so, I think `! Rules for specific sites` sounds better.

2021-04-15 10:12 UTC, wout-codes commented
You may want to add these: 
`https://www.ebay.com/itm/Lenovo-IdeaPad-5-Laptop-14-FHD-300-nits-AMD-Ryzen-5-4500U-8GB-256GB-SSD/164805306665?_trkparms=pageci%3Af8f0415a-9dd2-11eb-94a2-f2f7c2e5628b%7Cparentrq%3Ad503d31f1780a44e512bad7afff032f0%7Ciid%3A1`
```
$removeparam=_trkparms
$removeparam=_trksid
```

`https://www.behance.net/gallery/106166637/SIM?tracking_source=search_projects_recommended`
```
$removeparam=tracking_source
```

2021-04-15 12:10 UTC, ameshkov approved these changes

2021-04-15 14:51 UTC, ameshkov approved these changes

2021-04-15 14:51 UTC, ameshkov commented
@wout-codes I think we should start with something and then add new params one by one

2021-04-19 09:09 UTC, slavaleleka approved these changes

2021-04-20 08:58 UTC, merged