fix #80265 this.kiji.is
AdguardTeam/AdguardFilters pull request #80527
Opened 2021-04-15 11:11 UTC by stanislav-atr

#80265

2021-04-15 11:30 UTC, Yuki2718 requested changes
I already added js-ur: https://github.com/AdguardTeam/AdguardFilters/commit/fe63b6ed09a44357fe82813dde4e764222d1da01
Add `this.kiji.is##.page__listPageAd` instead.
Also better to drop `-1.0.0` part which may change over time.

2021-04-15 15:54 UTC, Yuki2718 approved these changes

2021-04-16 10:44 UTC, AdamWr commented on JapaneseFilter/sections/whitelist.txt
> +@@||log.nordot.jp/js/beacon-*.js$domain=kiji.is
This request/script is blocked by AdGuard Tracking Protection filter, so I think that it would be better to add this rule to that filter list.

2021-04-16 14:06 UTC, AdamWr approved these changes

2021-04-16 14:07 UTC, merged

2021-04-19 16:29 UTC, Yuki2718 commented
It looks to be better to narrow down the blocking rule, `log.nordot.jp` is used only on `this.kiji.is` and what are worth being blocked is xmlhttprequest. I'll edit the filters.