fix #80651 fiveguys.co.uk
AdguardTeam/AdguardFilters pull request #80693
Opened 2021-04-17 01:52 UTC by wout-codes

#80651

2021-04-19 14:31 UTC, stanislav-atr commented
There is also `#js-cookie-overlay` on https://restaurants.fiveguys.co.uk/index.html

2021-04-20 11:19 UTC, stanislav-atr approved these changes

2021-04-20 13:33 UTC, Sergey-Lyapin requested changes

2021-04-20 13:33 UTC, Sergey-Lyapin commented on AnnoyancesFilter/sections/cookies_specific.txt
> +fiveguys.co.uk#$#body { overflow: visible !important; margin-right: 0px !important; }
let's use `fiveguys.co.uk#%#//scriptlet("set-cookie", "5g_cookies", "1")` instead of ext-CSS

2021-04-21 12:35 UTC, Sergey-Lyapin commented on AnnoyancesFilter/sections/cookies_specific.txt
> +fiveguys.co.uk#$#body { overflow: visible !important; margin-right: 0px !important; }
@wout-codes

2021-04-21 21:45 UTC, merged