fix #80650 brandequity.economictimes.indiatimes.com
AdguardTeam/AdguardFilters pull request #80886
Opened 2021-04-19 14:41 UTC by stanislav-atr

#80650

2021-04-23 14:14 UTC, Alex-302 requested changes
push notification is not blocked

2021-04-23 14:14 UTC, Alex-302 commented on AnnoyancesFilter/sections/popups.txt
> +indiatimes.com##.facebook-live
not reproduced

2021-04-23 14:14 UTC, Alex-302 commented on AnnoyancesFilter/sections/cookies_specific.txt
> +indiatimes.com,computacenter.com##.consent-container
not reproduced

2021-04-23 14:14 UTC, Alex-302 commented on AnnoyancesFilter/sections/annoyances.txt
> +indiatimes.com#?#.footer-card-lst > li:has(> div#subcribe_consentPopup_bottom)
do not block in footers

2021-04-26 09:13 UTC, stanislav-atr commented
> push notification is not blocked

Not reproduced on my side.

2021-04-26 09:13 UTC, closed without merging