fix #80446 www.news18.com
AdguardTeam/AdguardFilters pull request #80973
Opened 2021-04-20 09:50 UTC by stanislav-atr

#80446

2021-04-22 12:29 UTC, Sergey-Lyapin commented on EnglishFilter/sections/specific.txt
> +news18.com##.article_youtube_player
I don't see this element

2021-04-22 12:43 UTC, Sergey-Lyapin requested changes

2021-04-22 12:43 UTC, Sergey-Lyapin commented on MobileFilter/sections/specific_web.txt
> +news18.com##.article_main > div[style^="margin-bottom: 15px; background: rgb"]
please add rules for other leftovers too

2021-04-26 13:02 UTC, Alex-302 requested changes
missed social leftover `news18.com##.article_socials`

2021-04-26 13:03 UTC, Alex-302 commented
![image](https://user-images.githubusercontent.com/8361299/116086800-de58a500-a6a8-11eb-9538-a82afc88c2df.png)
also ad leftover

2021-04-26 15:58 UTC, stanislav-atr commented
I've added `news18.com##div[class^="jsx-"][style^="min-height: 1170px"]` with `style^=` as it ends with semicolon on my end, on and Alex's screenshot there is none.
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/68852737/116113622-5337d900-a6c1-11eb-8091-eea9c7f353fe.png)
</details><br/>

2021-04-26 18:04 UTC, Alex-302 approved these changes

2021-04-26 18:04 UTC, merged