fix #81170 simplyfaucet.xyz
AdguardTeam/AdguardFilters pull request #81659
Opened 2021-04-28 12:04 UTC by stanislav-atr

#81170

2021-04-28 13:24 UTC, Sergey-Lyapin requested changes

2021-04-28 13:24 UTC, Sergey-Lyapin commented on EnglishFilter/sections/antiadblock.txt
> +@@||simplyfaucet.xyz/libs/advertisement.js$domain=simplyfaucet.xyz
please add to the existing rule:
`@@/libs/advertisement.js`

2021-04-28 13:24 UTC, Sergey-Lyapin commented on EnglishFilter/sections/specific.txt
> -/^(?!.*(bootstrapcdn.com|cdn.ampproject.org|cloudflare.com|disqus.com|disquscdn.com|dmca.com|ebacdn.com|facebook.net|fbcdn.net|fluidplayer.com|fontawesome.com|github.io|google.com|googleapis.com|goog
please add adservers to adservers.txt

2021-04-28 13:24 UTC, Sergey-Lyapin commented on EnglishFilter/sections/specific.txt
> +/^(?!.*(bootstrapcdn.com|cdn.ampproject.org|cloudflare.com|disqus.com|disquscdn.com|dmca.com|ebacdn.com|facebook.net|fbcdn.net|fluidplayer.com|fontawesome.com|github.io|google.com|googleapis.com|goog
and this rule breaks captcha

2021-04-28 13:26 UTC, Sergey-Lyapin commented on EnglishFilter/sections/specific.txt
> +/^(?!.*(bootstrapcdn.com|cdn.ampproject.org|cloudflare.com|disqus.com|disquscdn.com|dmca.com|ebacdn.com|facebook.net|fbcdn.net|fluidplayer.com|fontawesome.com|github.io|google.com|googleapis.com|goog
let's add raincaptcha.com as an exclusion in this regexp (and in the same regexps in other files)

2021-04-29 09:32 UTC, zloyden approved these changes

2021-04-29 09:33 UTC, closed without merging