Fix/#83051 soft98.ir
AdguardTeam/AdguardFilters pull request #83659
Opened 2021-05-20 14:56 UTC by stanislav-atr

#83051

2021-05-20 15:02 UTC, zloyden requested changes

2021-05-25 19:09 UTC, Alex-302 commented on EnglishFilter/sections/foreign.txt
> +@@||google-analytics.com/analytics.js$domain=soft98.ir
why not to Spyware?

2021-05-27 16:58 UTC, Alex-302 commented on EnglishFilter/sections/foreign.txt
> +@@||google-analytics.com/analytics.js$domain=soft98.ir
@stanislav-atr

2021-06-04 09:40 UTC, zloyden approved these changes

2021-06-04 09:40 UTC, merged