fix #85417 sweet-express.ru
AdguardTeam/AdguardFilters pull request #86075
Opened 2021-06-16 14:39 UTC by stanislav-atr

#85417

https://sweet-express.ru/blog/vybiraem-universalnyy-desert-dlya-ugoshcheniya/

2021-06-16 15:37 UTC, Alex-302 commented
Отсток соц сетей
![image](https://user-images.githubusercontent.com/8361299/122249855-dd3a3c00-ced1-11eb-8d0f-bd90327a4ded.png)

2021-06-16 15:38 UTC, Alex-302 commented
Подписка(+см. откуда загружается)
![image](https://user-images.githubusercontent.com/8361299/122250005-fb07a100-ced1-11eb-9118-98a04562eb47.png)

2021-06-16 15:38 UTC, Alex-302 requested changes

2021-06-16 15:38 UTC, Alex-302 commented on SocialFilter/sections/specific.txt
> +sweet-express.ru##.social_network_detail
Не вижу такого в коде.

2021-06-16 23:03 UTC, Sergey-Lyapin commented on SocialFilter/sections/specific.txt
> +sweet-express.ru##.social_network_detail
по ссылке в комменте есть

2021-06-17 14:49 UTC, zloyden commented on SocialFilter/sections/specific.txt
> +sweet-express.ru##.social_network_detail
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/122420309-42566600-cf94-11eb-8899-06922e3ab6a2.png)

</details><br/>

2021-06-17 15:45 UTC, stanislav-atr commented
@Alex-302, в ишью на скрине другой сайт, я правил только заголовок. Для http://zvzda.ru/ в этот же ПР добавил.

2021-06-18 06:52 UTC, zloyden requested changes

2021-06-18 06:52 UTC, zloyden commented on AnnoyancesFilter/sections/annoyances.txt
> +zvzda##.k-new-right > h4[style="margin-top:20px;"]
Убирает лишнее. Хотя бы так `zvzda.ru##.k-new-right > div.grid-item + h4[style="margin-top:20px;"]`

2021-06-21 11:53 UTC, zloyden approved these changes

2021-06-21 11:53 UTC, merged