fix #85406 mir24.tv
AdguardTeam/AdguardFilters pull request #86079
Opened 2021-06-16 15:05 UTC by stanislav-atr

#85406

2021-06-16 15:46 UTC, Alex-302 requested changes

2021-06-16 15:46 UTC, Alex-302 commented on AnnoyancesFilter/sections/annoyances.txt
> +mir24.tv##.aside-float > div.subscriptions
Не вижу элемент.
`.aside-float > div` избыточно.

2021-06-16 15:46 UTC, Alex-302 commented on SocialFilter/sections/specific.txt
> +mir24.tv##div[style="clear:both;"] > div[style="margin-left:0; margin-right:0; text-align: center;"]
Это не соц сети, а раздражители
```
mir24.tv##div[style="clear:both;"]div[style="margin-left:0; margin-right:0; text-align: center;"]
mir24.tv##a[href="https://t.me/mir24tv"][target="_blank"]
||mir24.tv/uploaded/resources/Telegramm_1200x90.jpg
```

2021-06-18 06:40 UTC, zloyden approved these changes

2021-06-18 06:43 UTC, merged