fix #86014 m.2gis.ru
AdguardTeam/AdguardFilters pull request #86702
Opened 2021-06-24 11:36 UTC by stanislav-atr

#86014

2021-06-28 14:57 UTC, Alex-302 requested changes

2021-06-28 14:57 UTC, Alex-302 commented on AnnoyancesFilter/sections/cookies_specific.txt
> +2gis.ru##.layout__app > div.searchBar__root + div + div[class]
Опасное, и не нужное для десктопной версии.
Проверь остальные региональные сайты и лучше скрой расширенным CSS. Либо можно добавить `:empty` и оставить поддомен в урловом правиле.

2021-06-29 09:49 UTC, zloyden commented on AnnoyancesFilter/sections/cookies_specific.txt
> +m.2gis.*###application > div:has(> p > span > a[href*="privacy"])
Я бы предпочел использовать `:upward` - `m.2gis.*#?##application > div[class] > p > span > a[href$="/privacy"]:upward(div[class])`. В твоем правиле пропущено `#?#` и если ссылаться на `privacy`, то лучше как в моем примере.

2021-06-29 10:54 UTC, zloyden approved these changes

2021-06-30 06:28 UTC, merged