fix #86200 cubiq.ru
AdguardTeam/AdguardFilters pull request #86713
Opened 2021-06-24 14:01 UTC by stanislav-atr

#86200

2021-06-25 11:33 UTC, zloyden requested changes

2021-06-25 11:33 UTC, zloyden commented on AnnoyancesFilter/sections/popups.txt
> +cubiq.ru###hwp-292769
Это правило не действует.

2021-06-25 11:34 UTC, zloyden requested changes
Еще надо убрать это
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/123419052-751ae280-d5c2-11eb-83f0-37efb72c347b.png)

</details><br/>

2021-06-25 14:51 UTC, zloyden requested changes

2021-06-25 14:51 UTC, zloyden commented on AnnoyancesFilter/sections/popups.txt
> +cubiq.ru##div[id^="hwp-"]
Почему не `cubiq.ru##.hwp-bottomright` или `cubiq.ru##.notification`?
Еще про подписки говорил `cubiq.ru##.subs`

2021-06-25 17:24 UTC, stanislav-atr commented on AnnoyancesFilter/sections/popups.txt
> +cubiq.ru##div[id^="hwp-"]
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/68852737/123462701-4cf7a780-d5f3-11eb-974a-4b6607eada5a.png)
</details><br/>

2021-06-28 06:56 UTC, zloyden approved these changes

2021-06-28 06:56 UTC, merged