fix #86202 www.allmusic.com
AdguardTeam/AdguardFilters pull request #86775
Opened 2021-06-25 11:42 UTC by stanislav-atr

#86202

2021-06-28 15:45 UTC, Alex-302 reviewed
Cannot find these elements with US IP.
About anti-adblock - don't forget about iOS.

2021-06-29 10:12 UTC, stanislav-atr commented
> Cannot find these elements with US IP.
> About anti-adblock - don't forget about iOS.
`.sidebar-promo` on the main page with any IPs:
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/68852737/123779991-65a9db00-d8db-11eb-945e-55a4c60ed0a1.png)
</details><br/>

https://www.allmusic.com/newreleases
`.new-release-newsletter-promo-tile`
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/68852737/123780172-94c04c80-d8db-11eb-8a12-d90b901b843f.png)
</details><br/>

2021-06-29 10:25 UTC, zloyden requested changes

2021-06-29 10:25 UTC, zloyden commented on AnnoyancesFilter/sections/antiadblock.txt
> +@@||pagead2.googlesyndication.com/pcs/activeview$domain=allmusic.com
Just add a domain here.
```
!#safari_cb_affinity(general)
@@||pagead2.googlesyndication.com/pcs/activeview$domain=allmovie.com
```

2021-06-29 11:24 UTC, zloyden approved these changes

2021-06-29 11:24 UTC, merged