fix #86722 magazinevoce.com.br
AdguardTeam/AdguardFilters pull request #87334
Opened 2021-07-02 15:14 UTC by stanislav-atr

#86722

2021-07-02 16:33 UTC, Alex-302 requested changes

2021-07-02 16:33 UTC, Alex-302 commented on SocialFilter/sections/specific.txt
> +magazinevoce.com.br##.psocial
Странные правила. Ты же вложенное скрываешь(верно), при том что скрыл уже верхний элемент(неправильно).
![image](https://user-images.githubusercontent.com/8361299/124304428-5ab9a980-db6c-11eb-8f1a-0219b86f322b.png)

2021-07-05 07:15 UTC, stanislav-atr commented on SocialFilter/sections/specific.txt
> +magazinevoce.com.br##.psocial
@Alex-302, поправил, чтобы не убирать лишнюю кнопку.

2021-07-06 17:38 UTC, Alex-302 approved these changes

2021-07-06 17:38 UTC, merged