www.bulurum.com
AdguardTeam/AdguardFilters pull request #88689
Opened 2021-07-20 13:17 UTC by gork7777

issue: #88581

2021-07-20 21:46 UTC, Sergey-Lyapin commented
please also check the main page and some random pages
![bulurum](https://user-images.githubusercontent.com/18536328/126399610-11b9a1ac-705d-447c-88aa-42a51794f1a2.png)

2021-07-20 21:53 UTC, Sergey-Lyapin commented
remove this rule:
`bulurum.com##a[href*="advertising.bulurum.com"][target="_blank"]`
and add:
```
@@||bulurum.com/v*/Images/Mvc/home/advertise_*.png
bulurum.com##div[id^="Banner"]
bulurum.com##.MobileContainer
```

2021-07-21 06:34 UTC, zloyden requested changes

2021-07-21 06:34 UTC, zloyden commented on TurkishFilter/sections/specific.txt
> +@@||bulurum.com/v*/Images/Mvc/home/advertise_*.png
Move this to the Turkish - whitelist.txt.

2021-07-21 06:34 UTC, zloyden commented on TurkishFilter/sections/specific.txt
> +bulurum.com##.MobileContainer
Move `bulurum.com##.MobileContainer` to the Annoyances - mobile-app.txt.

2021-07-21 13:58 UTC, zloyden approved these changes

2021-07-21 13:59 UTC, merged