thg.ru
AdguardTeam/AdguardFilters pull request #98450
Opened 2021-10-29 14:08 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/98235

<details><summary>Screenshot:</summary>

<img width="517" alt="Снимок экрана 2021-10-29 в 17 06 44" src="https://user-images.githubusercontent.com/91964807/139449451-3eb454fe-4e37-4ee9-84c9-948d30c270ba.png">

</details><br/>

2021-10-29 21:15 UTC, Alex-302 requested changes

2021-10-29 21:15 UTC, Alex-302 commented on RussianFilter/sections/css_extended.txt
> +thg.ru#?#thg.ru#?#td[valign="top"] > table >  tbody > tr:has(> td > table[width="240"] > tbody > tr > td > font[color])
ошибка

2021-10-29 21:15 UTC, Alex-302 commented on RussianFilter/sections/css_extended.txt
> +thg.ru#?#thg.ru#?#td[valign="top"] > table >  tbody > tr:has(> td > table[width="240"] > tbody > tr > td > font[color])
Лучше по аналогии с правилом из русского фильтра. Или его же переделай(`:contains` поддерживает регулярные выражения)

2021-10-30 15:59 UTC, krystian3w commented on RussianFilter/sections/css_extended.txt
> +thg.ru#?#thg.ru#?#td[valign="top"] > table >  tbody > tr:has(> td > table[width="240"] > tbody > tr > td > font[color])
IMO first check every table on site.

2021-10-30 16:00 UTC, krystian3w requested changes
<!---->

2021-11-01 09:55 UTC, krystian3w approved these changes

2021-11-01 09:56 UTC, zloyden requested changes

2021-11-01 09:56 UTC, zloyden commented on RussianFilter/sections/css_extended.txt
> +thg.ru#?#td[valign="top"] > table >  tbody > tr:has(> td > table[width="240"] > tbody > tr > td > font[color])
Судя по коду, один из остатков относится к счетчикам. Это лучше добавить в Spyware - `css_extended.txt`.
`thg.ru#?#td[valign="top"] > table > tbody > tr:has(> td > table[cellpadding="0"] noindex > a[href^="http://top100.rambler.ru/"])`.
Остатки в правой колонке можно убрать также двумя правилами, но по сути через одно.
```
thg.ru#?#td[valign="top"] > table[border] > tbody > tr:has(> td > table[width] td[style] > span[class]:contains(ССЫЛКИ))
thg.ru#?#td[valign="top"] > table[border] > tbody > tr:has(> td > table[width] td[style] > span[class]:contains(ССЫЛКИ)) + tr
```

2021-11-01 10:13 UTC, zloyden requested changes

2021-11-01 10:13 UTC, zloyden commented on RussianFilter/sections/css_extended.txt
> +thg.ru#?#td[valign="top"] > table > tbody > tr:has( > td > table[cellpadding="0"] > tbody > tr > td[valign="middle"])
Это правило не нужно из-за первых двух.

2021-11-01 10:23 UTC, zloyden approved these changes

2021-11-01 10:41 UTC, zloyden approved these changes

2021-11-01 10:41 UTC, merged