com.veraxen.colorbynumber.oilpainting
AdguardTeam/AdguardFilters pull request #98710
Opened 2021-11-01 15:53 UTC by jellizaveta

https://github.com/AdguardTeam/AdguardFilters/issues/97770

<details><summary>Screenshot:</summary>

![Screenshot_20211101-185030](https://user-images.githubusercontent.com/91964807/139700768-270f1069-76b0-49e3-8bd8-b770b2f4504b.png)

![Screenshot_20211101-184931](https://user-images.githubusercontent.com/91964807/139700775-de48556a-167f-4a2a-9bea-0e99dbfe8aa8.png)

![Screenshot_20211101-185119](https://user-images.githubusercontent.com/91964807/139700788-dca9680c-99eb-47cc-aea6-99c402471213.png)

</details><br/>

2021-11-08 15:04 UTC, Alex-302 requested changes

2021-11-08 15:04 UTC, Alex-302 commented on MobileFilter/sections/specific_app.txt
> +||facebook.com^$app=com.veraxen.colorbynumber.oilpainting|com.veraxen.jigsaw|com.veraxen.jigsawpuzzlescollectionhd
```
||stats.oilpainting.colorbynumber.veraxen.com^
||adtracker.jpchd.veraxen.com
||adtracker.oilpainting.colorbynumber.veraxen.com^
||adtracker.mkjigsaw.com^
||facebook.com^$app=com.veraxen.colorbynumber.oilpainting|com.veraxen.jigsaw|com.veraxen.jigsawpuzzlescollectionhd
```
это ж аналитика. В другой фильтра надо(по файлам раскидай правильно).

2021-11-08 23:55 UTC, krystian3w commented on SpywareFilter/sections/mobile.txt
> +||adtracker.jpchd.veraxen.com
works better without end at `^`?

2021-11-09 11:07 UTC, Alex-302 approved these changes

2021-11-09 11:07 UTC, merged